### ISSUE TITLE
feinkörnige(re) Einstellung von CD-Fehlern

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#101]
Bei SelectValid und RepairCD könnte es für Aufgabensteller interessant sein, per Konfiguration dafür sorgen zu können, dass keine "wrong multiplicities" ins Spiel gebracht werden. Damit die Studierenden interessantere, strukturelle Fehler finden müssen. (Aufgabeninstanzen, wo die Falschheit einzelner Optionen einfach aus Multiplizitäten wie "*..2" folgt, sind einfacher zu lösen als andere.)

**Comment by jvoigtlaender** [comment]
Es könnte sogar noch konfigurierbar gemacht werden, ob die Studierenden denn letztlich nach Kompositions- oder nach Vererbungszyklen Ausschau halten müssen (oder vielleicht nach Kompositionszyklen, die erst durch Vererbung zustande kommen).

**Comment by jvoigtlaender** [comment]
Wäre beides interessant, aber würde dem vielleicht keine Priorität einräumen, insbesondere wenn es unklar viel Aufwand sein könnte.

**Comment by marcellussiegburg** [comment]
This is still missing:
> oder vielleicht nach Kompositionszyklen, die erst durch Vererbung zustande kommen

**Comment by jvoigtlaender** [comment]
Hier dürfte es auch bzgl. https://github.com/jvoigtlaender/modelling-tasks-internal/issues/138 interessant werden, da etwa bestimmte Einstellungen wie die für die Anzahl von Kompositionen mit den "erlaubten/erwünschten" Fehlern interagieren.

**Comment by jvoigtlaender** [comment]
Gemäß des 1. Punktes aus https://github.com/jvoigtlaender/modelling-tasks-internal/issues/85#issuecomment-766898986 könnten die `AllowedProperties` neben der Beeinflussung von `illegalChanges` in https://github.com/jvoigtlaender/modelling-tasks-internal/commit/837b6693d593645712751ec4c5e63f91ed1f15c8 auch Einfluss auf die zur Auswahl stehenden Mutationsoperationen nehmen. (Und sei es nur aus Effizienzgründen: damit nicht etwa, wenn Multiplizitätsfehler verboten sind, Alloy trotzdem sein Glück mit `changedLimit`s versucht, nur um dann im `pred classDiagram`-Aufruf wieder zurückgepfiffen zu werden.)

**Comment by marcellussiegburg** [comment]
Hierzu gibt es mehrere Umsetzungsmöglichkeiten
> oder vielleicht nach Kompositionszyklen, die erst durch Vererbung zustande kommen

1. Es gibt eine neue Eigenschaft, `noTrivialCompositionCycles`, diese könnte genutzt werden, um solche Konstellationen zu verbieten: 
![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/531939/bafb9cf7-02f3-4130-981a-c4667ed3454c)
2. Es gibt eine neue Eigenschaft, `noNonTrivialCompositionCycles`, diese könnte genutzt werden, um solche Konstellationen zu verbieten: 
![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/531939/728550ec-86b1-4312-8f14-b282f0a6f615)
3. Es gibt beide Eigenschaften, um gezielt solche Konstellationen verbieten zu können: 
![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/531939/f1ddb16b-95b9-4657-ad2f-b7fa2fd742bd)

Bei der 3. Variante gibt es zwei Varianten:
  a) Die Prädikate werden von Alloy benutzt, um jeweils die andere Situation auszuschließen (was logisch diesem entspricht:`noTrivialCompositionCycles iff not noNonTrivialCompositionCycles`).
  b). Die Prädikate werden beide an den Nutzer weitergegeben, was es zusätzlich ermöglicht, auch die oben unter 3. gezeigte Situation gezielt hervorzurufen.

Ich glaube, ich wäre für 3a). Wobei dann noch dahin gestellt sei,  ob es einen Fakt geben sollte, der erzwingt, dass 3. niemals auftaucht (also etwa `not noCompositionCycles implies (noTrivialCompositionCycles iff not noNonTrivialCompositionCycles)`).

Vielleicht wäre dann auch eine Änderung der herausgegebenen `Property`(ies) sinnvoll von `CompositionCycles` zu `TrivialCompositionCycles` und `NonTrivialCompositionCycles` oder spezifischer zu `CompoistionCyclesWithoutInheritances` und `CompositionCyclesIncludingInheritances`. Aufgabenspezifisch müsste wohl aufgepasst werden, dass die Eigenschaften sinnvoll verwendet werden. (Bei `NameCdError` sollte beispielsweise vermutlich noch immer einfach nur nach einem `Kompositionszyklus` gefragt werden? Aber vielleicht sollte steuerbar sein, welcher Art der Zyklus sein sollte?)
Eventuell könnte das Prädikat `noCompositionCycles` dann auch ganz verschwinden?

**Comment by jvoigtlaender** [comment]
Die Semantik von 3. wird mir nicht so recht klar. Also warum erst die Kombination von `noTrivialCompositionCycles :: Bool` und `noNonTrivialCompositionCycles :: Bool` erlauben würde, die dort gezeigte Konstellation zu verhindern. Das Gegenteil scheint der Fall zu sein. Dort kommen doch beide Arten Zyklus drin vor, also schon Verbot eines davon würde dieses Beispiel ausschließen.

War vielleicht umgekehrt gemeint `hasTrivialCompositionCycles :: Bool` und `hasNonTrivialCompositionCycles :: Bool` und es ging nicht um das Verbieten von 3., sondern um das Erzwingen von 3.? (Aber 3. enthält ja zwei "Fehlermutationen", oder? Kann sowas überhaupt generiert werden? Bzw. wenn man es als `NameCdError`-Aufgabe nimmt, gibt es überhaupt eine korrekte Antwort, also eine Menge von Beziehungen, für die jeweils das Entfernen *einer beliebigen* davon zu einer Reparatur des Diagramms führt?)

Wie wäre es denn mit folgender Modellierung:
- Es bleibt hinsichtlich der Properties bei dem, was es schon gibt. Also `CompositionCycles`, keine Verfeinerung davon.
- Es gibt einen Parameter `anyCompositionCyclesInvolveInheritance :: Maybe Bool`. Setzt man den auf `Nothing`, bleibt alles wie bisher. Setzt man den auf `Just True`, dann wird 1. ausgeschlossen. (Also angezeigte fehlerhafte CDs haben entweder gar keinen Kompositionszyklus oder einen der 2. Art.) Und setzt man den Parameter auf `Just False`, dann wird 2. ausgeschlossen. (Also angezeigte fehlerhafte CDs haben entweder gar keinen Kompositionszyklus oder einen der 1. Art.)

(Diagramme der 3. Art könnten nur auftreten, wenn der neue Parameter auf Nothing gesetzt ist. Aber wie oben angemerkt, scheint mir doch, dass diese 3. Art aus anderen Gründen sowieso schon ausgeschlossen ist.)

**Comment by marcellussiegburg** [comment]
Die Intention meines Vorschlags kann ich jetzt auch nicht mehr rekonstruieren.

> Kann sowas überhaupt generiert werden?

Ja, der Fall ist natürlich äußerst unwahrscheinlich. Es müsste aber bei RepairCd/ SelectValidCd den Fall geben, wenn das gegebene Klassendiagramm falsch repariert wird und eine "ReverseRelationship" eingebaut wird, der "CompositionCycle" aber nicht behoben. Dann könnte als "Reparatur" das Einfügen der zuvor noch nicht vorhandenen Komposition angeboten werden.
