### ISSUE TITLE
Check different-names

### ISSUE THREAD

**Issue by marcellussiegburg** [fmidue/modelling-tasks#105]
It seems possible that names can be interchangeably be used in some cases, e.g.
<img width="334" alt="image" src="https://user-images.githubusercontent.com/531939/111915189-4ba76380-8a75-11eb-8389-2c771baccac2.png">

The instance provides only one solution:
```haskell
DifferentNamesInstance {
  cDiagram = "autotool-tasks/12-different-names10-cd.svg",
  oDiagram = "autotool-tasks/12-different-names10-od.svg",
  mapping = fromList [("a","v"),("b","z"),("c","y"),("d","w"),("e","x")]
  }
```

**Comment by marcellussiegburg** [comment]
Above mentioned class diagram may be represented in Haskell as
```haskell
cd0 :: ([String], [DiagramEdge])
cd0 = (
  ["A", "B", "C", "D"],
  [("D", "C", Inheritance),
   ("A", "B", Assoc Association "e" (0, Nothing) (1, Just 1) False),
   ("B", "D", Assoc Composition "a" (0, Just 1) (1, Just 1) False),
   ("D", "A", Assoc Association "d" (1, Just 1) (0, Nothing) False),
   ("A", "C", Assoc Aggregation "b" (1, Just 2) (1, Just 1) False),
   ("C", "B", Assoc Aggregation "c" (1, Just 2) (1, Nothing) False)
   ]
  )
```
Calling Alloy using this `cd0` (and appropriate transformations of the task) returns the following alloy instance (reduced to the relevant part)
```alloy
this/FName={a$0, b$0, c$0, d$0, e$0}
this/a={a$0}
this/e={e$0}
this/d={d$0}
this/b={b$0}
this/c={c$0}
this/Obj={A$0, B$0, D$0}
this/Obj<:get={A$0->b$0->D$0, A$0->e$0->B$0, B$0->a$0->D$0, D$0->c$0->B$0, D$0->d$0->A$0}
this/A={A$0}
this/B={B$0}
this/C={}
this/D={D$0}
```
which could in fact represent the above OD.

**Comment by marcellussiegburg** [comment]
Considering these observations it is in fact so, that #40 seems to be relevant here as well. For our Different names task this means: We have to
1. either tell the students that navigation directions are opposite here for compositions and aggregations
2. or reverse all associations before passing the OD to Alloy. Requiring a reverse of the links corresponding to associations as well. (as is done for aggregations, compositions)

**Comment by jvoigtlaender** [comment]
I don't get your conclusions, or their actual relevance for the bug.

Don't we already tell students, for the different-names task, that aggregations and compositions are to be navigated from part to whole? Or what do you mean by "are opposite here"?

Also, when are we ever "passing the OD to Alloy". Aren't ODs only ever read from Alloy, never written to Alloy?

And regardless of the issue of which directions arrows point to when visualizing links, I don't see how the problem manifested by the above example could ever arise if the implementation follows the strategy from the MoHoL paper, specifically including step 6:
![image](https://user-images.githubusercontent.com/5853832/112822916-dba66800-9088-11eb-804b-57276da5ec4b.png)

**Comment by marcellussiegburg** [comment]
> Don't we already tell students, for the different-names task, that aggregations and compositions are to be navigated from part to whole? Or what do you mean by "are opposite here"?

Yes. If they would be navigable from the whole toward the part. This issue would not occur.

> Also, when are we ever "passing the OD to Alloy". Aren't ODs only ever read from Alloy, never written to Alloy?

True. I am sorry for the confusion. It is of course the ***CD*** that I meant for reversing associations. (before step 6), i.e. *or reverse all associations before passing the **CD** to Alloy*.

> I don't see how the problem manifested by the above example could ever arise if the implementation follows the strategy from the MoHoL paper, specifically including step 6:

Because the Alloy implementation treats directions as follows: Compositions and aggregations are navigable from the whole toward the part. This line indicates this:
```alloy
this/Obj<:get={A$0->b$0->D$0, A$0->e$0->B$0, B$0->a$0->D$0, D$0->c$0->B$0, D$0->d$0->A$0}
```
(This represents the links retrieved from Alloy (without renaming))
Thus, permutations of step 4 do not prevent having a class as whole of an aggregation (or a composition) and as a target of an association with a sub class (or super class) of the class at the other end of the aggregation (or composition). But rather the opposite, i.e preventing classes being whole of a connection and source of an association with a sub class (or super class) of the class at the other end of the former connection.

**Comment by jvoigtlaender** [comment]
I don't see how https://github.com/jvoigtlaender/modelling-tasks-internal/commit/a69e6fed52935610d5e26130ae1c6e7be9e2ddcc can actually have fixed this.

**Comment by jvoigtlaender** [comment]
Warum ich es für unmöglich halte, dass https://github.com/jvoigtlaender/modelling-tasks-internal/commit/a69e6fed52935610d5e26130ae1c6e7be9e2ddcc diesen Fehler behoben hat:

Der Commit hat ja einzig einen Effekt darauf, was als `cd0` genommen wird. Und alles, was zuvor als `cd0` hätte auftreten können, kann auch nach diesem Commit noch als `cd0` auftreten, und umgekehrt.

Die gesamte restliche Funktion baut nur auf diesem `cd0` auf, nicht darauf, wie es erhalten wurde (insbesondere, dass es vorher ein pre-`cd0` gab, in welchem dann bestimmte Kanten umgedreht wurden; es findet auch nie wieder im Code ein Zugriff auf das pre- `cd0` statt). Also die Erzeugung des zu Grunde liegenden `cd0` ist für den Rest des Codes eine Black Box. Und diese Black Box kann nach Anwendung dieses Commits exakt die gleichen Dinge liefern wie vor Anwendung dieses Commits. Also wie soll da der Commit einen Fehler behoben haben, der zuvor bestand?

**Comment by marcellussiegburg** [comment]
These last two commit finally fix the behaviour. As it is really using the original CD and reversing all links in the OD (aggregation and composition links were reversed before; now associations are reversed additionally). Furthermore it reverses the limits as well.

For reproducibility:
Generating an ambiguous example was before possible using
```haskell
runExceptT (differentNames defaultDifferentNamesConfig {
  useAllRelationships = Just True,
  Modelling.CdOd.DifferentNames.classConfig = ClassConfig {classes = (4,4),
  aggregations = (2,Just 2),
  associations = (2,Just 2),
  compositions = (1,Just 1),
  inheritances = (1,Just 1)},
  Modelling.CdOd.DifferentNames.maxInstances = Just 100
  } 1 1)
```
generating (CD and OD with ambiguous matching):
![foobar-cd](https://user-images.githubusercontent.com/531939/148553992-cd75b418-6a85-4dcc-8648-c2b0cb25e6cd.png) ![foobar-od](https://user-images.githubusercontent.com/531939/148554109-71df1c5f-c34e-4084-89c4-614a42889f50.png)
The same example generated after the first of the aforementioned commits the CD and OD with non-ambiguous matching)
![foobar2-cd](https://user-images.githubusercontent.com/531939/148554128-bfc4fe09-f587-45aa-991c-66fe7fce3553.png) ![foobar2-od](https://user-images.githubusercontent.com/531939/148554141-1a424fa6-90ce-4e5a-b3ce-281dda98abe8.png)
Whats still wrong here is e.g. that the limits between `B` and `D` of edge `a` got reversed. It is irrelevant in this case but important in other cases. This was fixed by the last of the aforementioned commits. Unfortunately the commit itself breaks reproducibility of this example.

Lastly an example which is generated correctly after the the last commit with the last scenario:
![foobar5-cd](https://user-images.githubusercontent.com/531939/148564817-a8dc64e1-29a5-4c09-ae84-7d2df0e0c427.png) ![foobar5-od](https://user-images.githubusercontent.com/531939/148564846-3ed0b073-44bb-4b44-82d6-07fb42f9edcf.png)
[with this instance:
```haskell
DifferentNamesInstance {
  anonymousObjects = True,
  cDiagram = ([("C",[]),("B",[]),("A",["C"]),("D",[])],[(Aggregation,"b",(0,Just 2),"A","D",(1,Nothing)),(Aggregation,"c",(0,Just 2),"B","D",(0,Just 1)),(Association,"e",(1,Nothing),"A","B",(1,Just 1)),(Association,"a",(2,Nothing),"C","D",(0,Just 1)),(Composition,"d",(1,Just 1),"B","C",(2,Just 2))]),
  generatorValue = 1195161109281883289,
  oDiagram = (["C$0","A$0","B$0","D$0"],[(1,3,"z"),(2,0,"y"),(2,1,"y"),(2,1,"v"),(2,3,"x"),(3,0,"w"),(3,1,"w")]), showSolution = False,
  mapping = [(Name {unName = "a"},Name {unName = "w"}),(Name {unName = "b"},Name {unName = "z"}),(Name {unName = "c"},Name {unName = "x"}),(Name {unName = "d"},Name {unName = "y"}),(Name {unName = "e"},Name {unName = "v"})],
  usesAllRelationships = Just True
  }
```
]
