### ISSUE TITLE
issues from other repos

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#106]
Some of them might be covered already by issues here. But some consolidation is needed, I think:
- https://github.com/jvoigtlaender/alloy-cd-od-paper/issues/13
- https://github.com/marcellussiegburg/alloy-cd-paper/issues/29

The second one essentially consists of several "mini-issues".

**Comment by jvoigtlaender** [comment]
Ich vermute, allenfalls relevant für den Moment ist hier die Frage, ob bei allen Aufgaben, bei denen ein Highlighting existiert, in der jeweiligen Aufgabenstellung auch auf diese Highlighting-Funktionalität hingewiesen wird.

**Comment by marcellussiegburg** [comment]
At the moment a blocker for the first issue (jvoigtlaender/alloy-cd-od-paper#13) is marcellussiegburg/modelling-tasks#2

**Comment by jvoigtlaender** [comment]
A student pointed me to the mismatch between arrows for navigation directions in the lecture slides vs. in the sample exams. The latter, of course, were rendered via Autotool ...

**Comment by marcellussiegburg** [comment]
Should this issue gain priority (and maybe even fixed before first CD-OD exercises are created in Autotool this semester)?

**Comment by jvoigtlaender** [comment]
Can you estimate the effort? Is it realistic to fix it near-term? (At least it does not impact configurations. So it shouldn't disrupt operation of tasks even if deployed at some in-between point.)

**Comment by marcellussiegburg** [comment]
It is hard to tell. I once did this a long time ago (https://github.com/jvoigtlaender/modelling-tasks-internal/tree/uml-arrows) but it could then not be merged. I do not know how much of this work can be reused or whether stuff has to be re-implemented. Also, to regain highlighting some reuse (or reimplementation) of https://github.com/jvoigtlaender/modelling-tasks-internal/blob/dev/src/Modelling/PetriNet/Reach/Group.hs would be required. But besides the latter it should be rather straight forward.

**Comment by jvoigtlaender** [comment]
I guess: Go for it.

**Comment by marcellussiegburg** [comment]
The issues are resolved besides this comment: https://github.com/marcellussiegburg/alloy-cd-paper/issues/29#issuecomment-584502903
I.e. the naming of `0..*` in RepairCd. I think it is okay to keep it that way (especially considering that default multiplicities could be changed — in case it should refer to that fact instead?).
@jvoigtlaender If you think this should be addressed nevertheless, you may reopen this issue.

**Comment by jvoigtlaender** [comment]
Just remind me: Does the setting of a default multiplicity only suppress it in the diagrams or also in the verbalizations?

That is, if `0..*` is the default multiplicity and hence an association in the CD with that multiplicity will be displayed without it, will the task text still say something like "the association so-and-so with multiplicity `0..*`" (despite "`0..*`" not being visible in the picture)?

**Comment by marcellussiegburg** [comment]
Currently it does suppress it only in the diagram. Verbalisations will still refer to `0..*` (regardless what default multiplicity is set) for both removals and additions.
> (despite "0..*" not being visible in the picture)?

Yes

**Comment by jvoigtlaender** [comment]
I think that means that for tasks which verbalize associations (only `RepairCd`?), when their setting is such that reference is made to multiplicities of stuff in the diagram (this might not always be the case, due to referencing existing associations by name), the config checker should make sure that all default multiplicities are set to `Nothing`, so that they are not suppressed in the diagrams.
