### ISSUE TITLE
how-multiple-choice are the PickC* tasks?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#107]
This line: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/0905a1beaca0da5fe794eecd627e65e54e20df4a/src/Modelling/PetriNet/ConcurrencyAndConflict.hs#L193
and this one: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/0905a1beaca0da5fe794eecd627e65e54e20df4a/src/Modelling/PetriNet/ConcurrencyAndConflict.hs#L212
suggest that there is more than one Petri net presented that don't have concurrency/conflict.

But there are only ever two choices of Petri net presented at all, right? One that does have a concurrency/conflict and one that doesn't. Then the formulation should use singular.

(I was going to simply replace "(and the other Petri nets don't!)" by "(and the other Petri net doesn't!)" in both these lines, but wanted to check whether I am missing anything.)

**Comment by marcellussiegburg** [comment]
How about changing this task type in a similar direction as it is done with the math tasks, i.e. allowing for multiple wrong Petri nets (by specifying so within the configuration)? Nevertheless this issue would persist for formulation for both, Math and PickC tasks, where phrasing should be changed if number of wrong instances equals 1.

**Comment by jvoigtlaender** [comment]
Right, concretely actionable at the moment would be to enhance the phrasing with an explicit check in the code, doing pluralization only if indeed more than one wrong instance.

**Comment by marcellussiegburg** [comment]
related to #100
