### ISSUE TITLE
(optionally) ensure that in DifferentNames-Task all relationships get used

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#113]
That is, have a configuration parameter, of type `Bool` or `Maybe Bool`, by which it is possible to control whether some relationship from the CD might (or in some cases, even should) be "absent" from the concrete links in the OD.

This is related to one of the "sub-issues" from https://github.com/marcellussiegburg/alloy-cd-paper/issues/29.

**Comment by jvoigtlaender** [comment]
Relevant wäre im Moment nur der "prevent that a relationship is absent from the links" Teil, nicht der potentielle "deliberately make it so that a relationship is absent from the links" Teil.

Und das auch nur abhängig vom "Klausurerzeugungsmodus".

**Comment by jvoigtlaender** [comment]
There was some uncertainty whether currently the extra enforcement from https://github.com/jvoigtlaender/modelling-tasks-internal/commit/dce76489a7820dea3f7d6fcae107e6317f01a724 is really necessary. 

Also, there is now this "leftover": https://github.com/jvoigtlaender/modelling-tasks-internal/blob/a8e12a052cd3f2c274838a86011367745449e623/src/Modelling/CdOd/DifferentNames.hs#L215

**Comment by jvoigtlaender** [comment]
In light of the previous comment above, suggesting that maybe "all of them get used" was already implicitly enforced elsewhere (i.e., it was "extra" in https://github.com/jvoigtlaender/modelling-tasks-internal/commit/dce76489a7820dea3f7d6fcae107e6317f01a724), it would be good to now make the "Gegenprobe", i.e., check that if the new parameter `usesAllRelationships` is set to `Just False`, indeed task instances are generated that do *not* use all relationships.

**Comment by marcellussiegburg** [comment]
I did (manually) check that `Just False` indeed enforces that not all relationships get used. Most relevant are in fact these (modified) lines
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/d822ff523ec475aeaca5096631a136e3f5ed57b8/src/Modelling/CdOd/DifferentNames.hs#L324-L325 which decide which solutions to accept finally as part of the generate-and-test approach used.
Before the change it was this single line:
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/097ee0527cd156e3624f660e11cde741f08fe404/src/Modelling/CdOd/DifferentNames.hs#L314

**Comment by jvoigtlaender** [comment]
I see. Of course, "indeed task instances are generated that do not use all relationships" is not the same as "indeed enforces that not all relationships get used". :smile:

The latter would also hold if no task instances are generated (that is, if the generate-and-test would always run into the re-generation case).
