### ISSUE TITLE
Konsistenz zwischen Eingabeformaten

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#114]
Spezifisch, ob Transitions- (evtl. auch Stellen-) Namen mit oder ohne Anführungszeichen einzugeben sind:

![image](https://user-images.githubusercontent.com/5853832/112623070-2bd4be80-8e2c-11eb-8e5d-ba8ea26055d1.png)

vs.

![image](https://user-images.githubusercontent.com/5853832/112623104-35f6bd00-8e2c-11eb-95e5-a9eba37e4e5a.png)

**Comment by jvoigtlaender** [comment]
Dies wäre aus Konsistenzgründen wirklich gut.

Ich wäre für die Version ohne Anführungszeichen.

Ich nehme an, eine Umsetzung würde auf einen Schlag für alle `Pick/Find-Conflict/Concurrency` Aufgaben für Einheitlichkeit sorgen.

Allerdings würde es selbst dann noch Unterschiede im "Namens-Format" zu anderen Aufgabentypen geben, da insbesondere im `CD-OD-DifferentNames` Task jetzt die Namen von Relationships etc. in einfachen Anführungszeichen anzugeben sind, also etwa `'a'`, nicht `a`. (Beim `CD-OD-Match` Task ist sogar mit doppelten Anführungszeichen zu arbeiten, aber da geht es auch wirklich um einen String, das ergibt also sehr viel Sinn.)

*Edit:*

Der DifferentNames-Task verwendet aktuell keine einfache Anführungszeichen mehr, sondern doch wieder doppelte Anführungszeichen, wegen https://fmidue.slack.com/archives/DP6ACM4S2/p1630080817034900?thread_ts=1630068406.030000&cid=DP6ACM4S2

Allerdings haben doppelte Anführungszeichen auch ihre Tücken, etwa https://fmidue.slack.com/archives/DP6ACM4S2/p1630223053056900?thread_ts=1630068406.030000&cid=DP6ACM4S2

Also vielleicht sollten alle Aufgaben, auch DifferentNames und MatchCdOd, auf alle möglichen Arten von Anführungszeichen verzichten.

**Comment by marcellussiegburg** [comment]
Der letzte commit adressiert das Format bei DifferentNames. Das hier ist jetzt z.B. eine gültige Eingabe für diese Aufgabe
```Haskell
[(b,y),(c,x),(defauLt1,z)]
```
Allerdings stellt sich bei MatchCdOd schon eher die Frage, was denn dort eine gültige Eingabe sein soll. Bisher wird dort ein Format vom Typ `[(Int, String)]` verwendet, also zum Beispiel
```Haskell
[(1, "ab"), (2, "bcd")]
```
Die Frage ist, wie das "neue" Format aussehen könnte/sollte. Mein Vorschlag wäre `[(Int, NameList)]`: (mit `newtype NameList = NameList { unNameList :: [Name] }` und spezieller `Read` Instanz)
```Haskell
[(1, a b), (2, b c d)]
```
Der Nachteil ist vielleicht, dass das nicht intuitiv für Haskell-Datentyp-Schreibweise ist? (Für die Haskeller:innen sieht das aus wie mehrstellige Funktionen?)
Eine mögliche Alternative `[(Int, Name)]` wäre allerdings mehr verbose:
```Haskell
[(1, a), (1, b), (2, b), (2, c), (2, d)]
```
[Insbesondere hinter dem Hintergrund der Anfrage des anderen Lehrstuhls würde ich das jetzt dringlich umsetzen wollen.]
@jvoigtlaender: Hast du eine Meinung / Präferenz / Alternative?

**Comment by jvoigtlaender** [comment]
Ich schätze, ich wäre bei `MatchCdOd` für `[(1,ab),(2,bcd)]`. Also ohne Anführungszeichen, aber auch ohne (Notwendigkeit für) Leerzeichen. Also meinetwegen darf man auch `a b c` schreiben, aber ebenso sollte `abc` erlaubt sein? Hier besteht ja kein Verwechslungspotential zwischen `default` und `d e f a u l t`, da es immer einzelne Zeichen sind, wodurch die Objektdiagramme benannt werden. Keine „allgemeinen Namen“.
