### ISSUE TITLE
Kontrolle über SelfLoops in Objektdiagrammen

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#118]
Bei den Aufgabentypen, wo ODs vorkommen, könnte über eine Konfigurationsoption gesteuert werden, ob Links von Objekten zu sich selbst vorkommen dürfen, müssen, oder es egal ist.

**Comment by jvoigtlaender** [comment]
Hängt wohl ein bisschen vom "Klausurerzeugungsmodus" ab.

**Comment by jvoigtlaender** [comment]
Beim `MatchCdOd` task hätte ich wohl eigentlich gemeint, dass „Selbstlinks dürfen/müssen vorkommen“ zu interpretieren ist als „Selbstlinks dürfen/müssen unter den angezeigten Objektdiagrammen vorkommen“. Jetzt ist es aber in der Implementierung wohl so, dass wenn „müssen“ eingestellt ist, *in allen* angezeigten Objektdiagrammen jeweils mindestens ein Selbstlink vorkommen muss.

**Comment by marcellussiegburg** [comment]
> Jetzt ist es aber in der Implementierung wohl so, dass wenn „müssen“ eingestellt ist, *in allen* angezeigten Objektdiagrammen jeweils mindestens ein Selbstlink vorkommen muss.

Ja, im Moment wird das für alle ODs gefordert. Für eine feinere Auswahl, ist wohl genaueres Überlegen notwendig (soll das für bestimmte Kombinationen gelten oder werden einfach (potenziell) doppelt so viele ODs generiert - einmal mit einmal ohne und dann wird gezielt mit einer bestimmten Auswahlfunktion kombiniert?).

**Comment by jvoigtlaender** [comment]
Mein Vorschlag (kurzfristig, und wahrscheinlich sogar langfristig - außer es entsteht spezifischer Bedarf, gerade bei `MatchCdOd` unbedingt Selfloops erzwingen zu wollen) wäre:
- In `DifferentNames` bleibt es so wie jetzt (aber eventuell wird `allowSelfLoops` in `selfLoopsExist` oder so umbenannt).
- In `MatchCdOd` wird aus `allowSelfLoops :: Maybe Bool` ein `allowSelfLoops :: Bool`, wobei die `Just True`-Variante wegfällt (und `Nothing` zu `True` wird).

**Comment by marcellussiegburg** [comment]
Diese Parameter existieren in der Form nicht mehr. Stattdessen wurde `hasSelfLoops` als Bestandteil von `ObjectProperties` eingeführt.
Die daraus abgeleitete Lösung ist: in `DifferentNames` ändert sich nichts. In `MatchCdOd` wird `hasSelfLoops = Just True` via Checker zurückgewiesen.
