### ISSUE TITLE
Bewertungsfunktionen der "Klausuraufgaben" in Autotool erhalten/einbauen

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#125]
Es gibt in Autotool ja auch das Konzept der abgestuften Bewertung. Bisher nutzen wir das gar nicht. (?)

Für die Aufgaben, für welche jetzt im Rahmen der Klausur Überlegungen zur Teilbepunktung angestellt werden, könnten die entsprechenden Funktionen auch in Autotool übernommen werden.

**Comment by jvoigtlaender** [comment]
Für einige spezielle Aspekte, siehe Thread https://fmidue.slack.com/archives/DP6ACM4S2/p1617987784013300?thread_ts=1617270167.043500&cid=DP6ACM4S2.

Insbesondere müssten manche "Grenzen" wohl an bestimmte instanzspezifische Größen (z.B. bei Aufgaben mit Transitionssequenzen als Antwort: Länge der Musterlösung, oder der Einreichung, oder der per Konfiguration des Aufgabentyps eingestellten Maximallänge oder so) gekoppelt werden.

**Comment by marcellussiegburg** [comment]
Hier sollen die Bewertungskriterien für alle Aufgabentypen aus der Klausur des Wintersemesters übernommen werden (und auch schon als Grundlage für die Vergabe von Bonuspunkten dieses Semester verwendet werden)?

Es gibt die Möglichkeit im Autotool Teilpunkte zu vergeben. Allerdings können Punkte nur für als korrekt angesehene Lösungen vergeben werden. Mit dem Update aus Leipzig entfällt die Markierung der Lösung als rot/grün, daher sollte zumindest niemand mehr in falscher Sicherheit gewähnt werden.
D.h. hier müssten wir uns entscheiden, ab wann eine Einreichung als "korrekt" angesehen wird (und was "korrekt" dann überhaupt bedeutet); die "korrekten" Einreichungen können dann mit Punkten versehen werden.

**Comment by jvoigtlaender** [comment]
Ob in allen Fällen die Punktverteilung auch für den Übungsbetrieb sinnvoll ist, überblicke ich erstmal auch nicht. 

Aber wir könnten Erfahrungen damit sammeln. Und es hat ja nicht gleich starke Konsequenzen wie in der Klausur. 

Als Schwelle für „(teil)korrekt“ bietet sich sicher 50% an.
