### ISSUE TITLE
Throw random permutations of classes (and maybe of associations/aggregations/compositions) at RepairCD tasks

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#131]
For example, if the task instance currently contains this (invalid) CD:
![image](https://user-images.githubusercontent.com/5853832/123149332-7254ac00-d461-11eb-974c-968102ae5628.png)
then perform random shuffles on `[A,B,C,D]` and on `[x,y,z]`, and output the correspondingly "renamed" task instance instead.

Of course, the names output in the answers that the students have to choose from also have to be adapted accordingly.

Also, depending on the `printNames` option, the shuffling of `x`, `y`, ... could sometimes be skipped. (As in https://github.com/jvoigtlaender/modelling-tasks-internal/issues/127#issue-928482870, maybe its not worth, or even counterproductive, to do such skipping.)

**Comment by jvoigtlaender** [comment]
This one can be closed now?

**Comment by marcellussiegburg** [comment]
I have not considered this part here, yet (the shuffling is performed every time at the moment):
> Also, depending on the printNames option, the shuffling of x, y, ... could sometimes be skipped. (As in #127 (comment), maybe its not worth, or even counterproductive, to do such skipping.)

**Comment by jvoigtlaender** [comment]
Yeah, but unless this causes an efficiency problem (which surely it doesn't, compared to all the other effort going into generation), there cannot really be any harm in randomly renaming the associations even when they are not getting shown.
