### ISSUE TITLE
Throw random permutations of classes and (certain) associations/aggregations/compositions at DifferentNames tasks

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#133]
For example, if the task instance currently looks like this:
![image](https://user-images.githubusercontent.com/5853832/123153744-51db2080-d466-11eb-8aca-11820ff56b91.png)
then perform random shuffles on `[A,B,C,D]` and on
1. either `[a,b,c,d]`
2. or `[w,x,y,z]`

and output the correspondingly "renamed" task instance instead.

Of course, also the information about what is the correct answer needs to be adapted per the used permutation/shuffle.

It shouldn't be necessary to shuffle both 1. and 2. above, because that would not add extra entropy.

But whether it would be better (in terms of adding variation) to shuffle 1. or to shuffle 2., I cannot judge right now - would require more analysis of the generation process, I think.

**Comment by jvoigtlaender** [comment]
Of course, some care is needed if https://github.com/jvoigtlaender/modelling-tasks-internal/issues/134 is also done, because any "non-anonymous" object names should fit to the class names (after their shuffling).

**Comment by jvoigtlaender** [comment]
Since #134 is not marked with the exam label, the last comment above can be ignored for the moment.

Also, the question from the comment before that, whether it would be better to shuffle 1. or to shuffle 2., could be simply resolved by shuffling both. (That cannot do harm, even if it does not increase entropy.)

So for the moment, all three lists `[A,B,C,D]`, `[a,b,c,d]` and `[w,x,y,z]` could be shuffled.

(And the issue of non-anonymous objects just noted down and taken up again in case #134 is done sometime later.)

**Comment by jvoigtlaender** [comment]
The shuffling code probably needs to be revisited in case the idea from #113 about "optionally ensure that some relationship from the CD is absent from the concrete links in the OD" is acted upon.

**Comment by jvoigtlaender** [comment]
Also interesting in the future (and for other "throw random permutations ... issues", e.g. https://github.com/jvoigtlaender/modelling-tasks-internal/issues/131) is whether the renaming of entities has any effect on the layouting of the resulting diagrams. (Could be the case if GraphViz somehow uses alphabetic order of node names for deciding placement of nodes or so.)

**Comment by marcellussiegburg** [comment]
It seems to have no influence
<img width="69" alt="image" src="https://user-images.githubusercontent.com/531939/130447789-b3ae31ca-68aa-4817-be70-4bce8f0bec3e.png"><img width="71" alt="image" src="https://user-images.githubusercontent.com/531939/130447840-d9eb9abc-0bb3-4b07-8c08-c2f446dfc7bf.png">

**Comment by marcellussiegburg** [comment]
In contradiction to the statement of the initial description of how to resolve this issue

> then perform random shuffles on [A,B,C,D] and on
>
> 1. either [a,b,c,d]
> 2. or [w,x,y,z]

[...]

> It shouldn't be necessary to shuffle both 1. and 2. above, because that would not add extra entropy.

The current implementation does shuffle both, which probably is not a problem. It does in fact not add entropy, but it adds (visual) variety to both graphs.
(The anticipated issue of https://github.com/jvoigtlaender/modelling-tasks-internal/issues/133#issuecomment-903702122 is not present.)
What is not yet done (but probably could be done as well) is switching layouts of graphs (in contrast to see https://github.com/jvoigtlaender/modelling-tasks-internal/issues/133#issuecomment-903724272). I guess changing the order of class names or the order of associations would influence the appearance of the graph.
The important question is would we want this? The benefit of similar graphs is that we can inspect one task and see how (about) it would look like for other variants. On the other hand would changing layouts add (visual) variety.

**Comment by jvoigtlaender** [comment]
> I guess changing the order of class names or the order of associations would influence the appearance of the graph.

Can you check whether that is actually the case? If it isn't, then nothing further needs to be decided here, since any "layout randomization" would then not seem possible via "GraphViz input mangling" and instead would have to be relegated to #155.

> The important question is would we want this? The benefit of similar graphs is that we can inspect one task and see how (about) it would look like for other variants.

That aspect is only relevant in "exam-on-paper" mode? The cheap way out would be to introduce a configuration parameter. This would also be relevant in #155.

**Comment by marcellussiegburg** [comment]
> Can you check whether that is actually the case?

Yes, it is the case:

Changing the order of nodes (can) change(s) the overall layout:
![cd1](https://user-images.githubusercontent.com/531939/212293095-d7bbabde-2241-4636-bfc5-5ccf75b1220a.svg)
```Haskell
([("A",[]),("D",[]),("B",[]),("C",[])],...)
```

![cd2](https://user-images.githubusercontent.com/531939/212293285-5d13327a-24c9-4311-967d-d6f4a8ca2aa1.svg)
```Haskell
([("D",[]),("A",[]),("B",[]),("C",[])],...)
```

And more subtle: changing the order of edges with the same direction, changes their order.
![od1](https://user-images.githubusercontent.com/531939/212292482-fe3ff3a1-2062-42ff-8f6b-8a2956fcade3.svg)
```Haskell
(["C$0","B$0","B$1","B$2"],[(0,1,"y"),(0,2,"y"),(0,3,"y"),(0,0,"x"),(0,3,"z")])
```

![od2](https://user-images.githubusercontent.com/531939/212292948-ef8a6467-4eac-4b43-b942-fad8c8f58bd9.svg)
```Haskell
(["C$0","B$0","B$1","B$2"],[(0,1,"y"),(0,2,"y"),(0,3,"z"),(0,0,"x"),(0,3,"y")])
```

The latter could be interpreted as not even a layout change (although I do not know, if there are cases where the layout would change for such a change).

**Comment by jvoigtlaender** [comment]
Okay, the visual change in the class diagrams is quite worthwhile (in terms of adding variation between otherwise identical tasks), in particular if so cheaply obtained. On the other hand, there is no guarantee of visual changes, as also witnessed by the situation on the object diagrams.

So I would opt for adding a Boolean configuration parameter of the kind `allowLayoutMangling`, and if that one is set, these permutations of "nodes and edges" are performed.

It probably applies to more task types than just this specific one.

If #155 gets implemented, the parameter could be turned into a `perform...` rather than `allow...`, and would then affect both this permutation and whatever #155 implements.
