### ISSUE TITLE
Not just anonymous objects in in DifferentNames task?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#134]
I guess the `Just 1000` in https://github.com/jvoigtlaender/modelling-tasks-internal/blob/2490f8b185ca1fe7cfacf283359e13749f7735d9/src/Modelling/CdOd/DifferentNames.hs#L138 is a cheat to avoid depictions like the following one (which appeared in the MoHoL paper)?
![image](https://user-images.githubusercontent.com/5853832/123155716-bd25f200-d468-11eb-81c0-724f4158c6df.png)
... because of fear that the `a` in the object diagram might get confused with the `a` association in the class diagram.

On the one hand, I am not sure the "all objects anonymous" should really always be enforced here. (Maybe in an exam, but not in normal exercises?)

But even *if* that's intended, it shouldn't be done by a `Just 1000` cheat, I think.

So, refactor the `drawOdFromInstance` function/interface a bit?

More generally, introduce a configuration option also for the user of the task type, by allowing them to set whether or not object names may be used?

**Comment by marcellussiegburg** [comment]
I was about to introduce the following data type for configuring the appearance of ODs:
```
data OdDrawSettings
  = OdDrawSettings {
    -- | this proportion is used when randomly distributing anonymous objects
    anonymousObjectProportion :: !(Int, Int),
    printLinkDirections :: !Bool,
    printLinkNames :: !Bool
    }
```
However there might be an argument, that `anonymousObjectProportion` should actually be a property of `ObjectProperties` and that the `Object` data type should instead have a property `isAnonymous`, which then is persistent within the `ObjectDiagram` (i.e. direct instances would contain this information persistent). This would have an impact on drawing of ODs as no shuffling would be required any more (as this would happen after/during the generation of an OD).

**Comment by jvoigtlaender** [comment]
Sounds reasonable (not having randomness during the drawing).
