### ISSUE TITLE
Throw random permutations of classes and associations/aggregations/compositions at MatchCdOd tasks

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#136]
For example, if the task instance currently looks contains this:
![image](https://user-images.githubusercontent.com/5853832/123159384-3de6ed00-d46d-11eb-9570-5e5e744ae66c.png)
and this:
![image](https://user-images.githubusercontent.com/5853832/123159418-48a18200-d46d-11eb-8203-892939db689d.png)
(and one further CD and four further ODs), then perform random shuffles on `[A,B,C,D]` and on `[x,y,z]`, and output the correspondingly "renamed" task instance instead.

~~For the object names of non-anonymous objects, care as in https://github.com/jvoigtlaender/modelling-tasks-internal/issues/133#issuecomment-867113338 is needed (independently of https://github.com/jvoigtlaender/modelling-tasks-internal/issues/134).~~

A possible block at the moment might be the decision of whether to do the shuffling/renaming now for `getRandomTask` or for `getRandomTask'`, or for both. (See https://github.com/jvoigtlaender/modelling-tasks-internal/issues/61.)

**Comment by jvoigtlaender** [comment]
In the case of `getRandomTask'`:
1. Maybe these lines: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/0e026962dfe121bc19ddef4999fae36f97334b71/src/Modelling/CdOd/MatchCdOd.hs#L233-L234 already do the relevant job?
2. But maybe in this line: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/0e026962dfe121bc19ddef4999fae36f97334b71/src/Modelling/CdOd/MatchCdOd.hs#L224 a permutation of `[1,2]` should be added, randomly switching the order of the two class diagrams (and then also adapt the answer checker accordingly, of course)?

**Comment by jvoigtlaender** [comment]
Für den Moment würde ich vorschlagen, nur `[x,y,z]` zu permutieren (weil es bzgl. `[A,B,C,D]` das Problem mit der Benennung der nicht-anonymen Objekte gibt).

(Wenn es für `getRandomTask` praktikabel ist.)

**Comment by marcellussiegburg** [comment]
I do not see the point of excluding `[A,B,C,D]` of the permutation. Anonymising happens during the drawing of ODs. Thus, renaming should not affect it, if all CDs and ODs are renamed likewise. Or do I miss something?

**Comment by jvoigtlaender** [comment]
Then I simply didn't know anymore that a name like `a1` is never stored, but instead is simply computed from `A` when needed. (That's how it is?)

**Comment by marcellussiegburg** [comment]
Yes, e.g. this `Od` representation in Haskell
```haskell
(["A$0","A$1","B$0","D$0"],[(2,3,"y"),(3,0,"z"),(3,1,"z")])
```
is drawn as 
<img width="214" alt="image" src="https://user-images.githubusercontent.com/531939/130626071-117a8a3a-c420-4e5d-8254-876143cbc2dd.png">

**Comment by jvoigtlaender** [comment]
Well, this particular example is not so informative, since in it every object is anonymous. The interesting bit is de-anonymization, not anonymization.

**Comment by marcellussiegburg** [comment]
I just recognised, I confusingly answered your question. So `a1` would be stored in the datatype as `A$1` but if randomly chosen during drawing, the information would be thrown away. I.e. it would be named either `a1 : A` or `: A`.

**Comment by jvoigtlaender** [comment]
So the important bit is to rename "objects" `["A$0","A$1","B$0","D$0"]` to `["B$0","B$1","C$0","D$0"]` when "classes" `A`, `B`, `C`, `D` are renamed to `B`, `C`, `A`, `D`.

**Comment by jvoigtlaender** [comment]
Might still be something to do here after switching from `getRandomTask` to `getRandomTask'`.

**Comment by marcellussiegburg** [comment]
> Might still be something to do here after switching from getRandomTask to getRandomTask'.

This is not the case (anymore).

But the same question as in https://github.com/jvoigtlaender/modelling-tasks-internal/issues/133#issuecomment-1379290348 arises. (i.e. Would we like to have different graph layouts after shuffling?)
