### ISSUE TITLE
Refactor `transform`, `getFourParts` etc.

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#143]
See this discussion: https://github.com/jvoigtlaender/modelling-tasks-internal/commit/1eec9a41a9ec9e61ae427f5a341f8dd1a78bfb71#r55429208

While at it, would also make sense to refactor these lines: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/b3cbf27f47a4e8e3acd5a31fe1661e8f40ea585a/alloy/od/template.als#L51-L53 out into something that can be turned on/off on demand. In particular since for the `SelectValidCD` and `RepairCD` tasks, the "object diagram instance existence checking" shouldn't really care about whether or not those object diagrams contain many isolated objects.

Possibly this other fact: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/b3cbf27f47a4e8e3acd5a31fe1661e8f40ea585a/alloy/od/template.als#L45-L49 should then be unconditionally reinstated (or this one should be used for `SelectValidCD` and `RepairCD`, while the other fact from above is used for tasks that involve showing object diagrams to the students).

**Comment by marcellussiegburg** [comment]
For the latter see c7db45980db9fc87a0b50928aef582b4e9e3391e
