### ISSUE TITLE
Possible wrong answers for MatchCdOd in specific case

### ISSUE THREAD

**Issue by marcellussiegburg** [fmidue/modelling-tasks#144]
In the light of #40 navigation directions of Aggregations/Compositions are opposite to Associations in the CD2Alloy-part. The workaround of fixing the directions during print does resolve the issue in most cases. But in MatchCdOd we always refer to 2 class diagrams which could lead to wrong semantics.

Diving into this might probably be easier considering the task generation process. First, a random CD0 is generated. Then we select 3 random modifications. Now imagine we choose 2 modifications of adding an edge; once an association and the other one being an aggregation or composition, but both between the same (sub)classes.

E.g. adding an aggregation for `A`s of `B`s to get CD1 and an association from `A` to `B` to get CD2, for simplicity lets assume they have both same limits. The interesting part starts when we call CD2Alloy in order to get ODs. We might get an OD which is instance of CD1 but not of CD2 where we have a link going from some `B` to some `A` or an instance of CD2 but not CD1 where we have a link going from some `A` to some `B`. On drawing there is no issue: in the former case we simply reverse the edge, in the latter case we keep the direction, but there is the issue. When we want to solve the task we cannot distinguish both, i.e. in both cases we would assume the OD belongs to both CD1 *and* CD2. A similar issue arises with one of the new edges being added reversed.

This may be addressed either by solving #40 or by introducing another hack.

Edit: fix association / aggregation order

**Comment by jvoigtlaender** [comment]
Did you mix up "association" and "aggregation" in the paragraph "E.g. adding an ..." above?

**Comment by jvoigtlaender** [comment]
I'm not convinced by the counterexample. I'm trying to get to grips with it following the kind of reasoning from https://github.com/jvoigtlaender/modelling-tasks-internal/issues/105.

So you are saying that CD1 got a relationship as follows:
```haskell
cd1 :: ([String], [DiagramEdge])
cd1 = (
  ["A", "B", ...],
  [...,
   ("A", "B", Assoc Aggregation "x" (1, Just 1) (1, Just 1) False),
   ...
   ]
  )
```
and  CD2 got a relationship as follows:
```haskell
cd2 :: ([String], [DiagramEdge])
cd2 = (
  ["A", "B", ...],
  [...,
   ("A", "B", Assoc Association "x" (1, Just 1) (1, Just 1) False),
   ...
   ]
  )
```
I don't see how from this we
> might get [when we call CD2Alloy] an OD which is instance of CD1 but not of CD2 where we have a link going from some B to some A or an instance of CD2 but not CD1 where we have a link going from some A to some B

Because neither could 
```
this/Obj<:get={B$0->x$0->A$0, ...}
```
result from running `CD1 and (not CD2)`, nor could
```
this/Obj<:get={A$0->x$0->B$0, ...}
```
result from running `(not CD1) and CD2`.

The former cannot happen, because on the Alloy side `B$0->x$0->A$0` would not result from "must satisfy `cd1 = ... ("A", "B", Assoc Aggregation "x" ...) ...`". (Since for CD2Alloy, this aggregation would be navigable from A objects to B objects, not the other way round.)

And the other case also cannot "happen", because on the Alloy side having `A$0->x$0->B$0` would contradict "satisfies `(not CD1)`". (Again, since for CD2Alloy, the aggregation in `cd1` is navigable from A objects to B objects, so requesting `not CD1` means that `A$0->x$0->B$0` is prevented - if there are no other violations of `CD1` that Alloy can find, to satisfy `not CD1`).

**Comment by jvoigtlaender** [comment]
Oh, or maybe your point is that `B$0->x$0->A$0` need not "result" from "must satisfy `cd1 = ... ("A", "B", Assoc Aggregation "x" ...) ...`", but could still be present for other reasons?

**Comment by jvoigtlaender** [comment]
No, I don't get it.

**Comment by marcellussiegburg** [comment]
I could manually generate a problematic instance using (part of) the generation process.

The example can be reproduced by performing the following operations within ghci:

```haskell
let cd1 = ([("A",[]),("B",[])],[(Aggregation, "x", (1, Just 1), "B", "A", (1, Just 1))]) :: Syntax; cd2 = ([("A", []),("B", [])],[(Association, "x", (1, Just 1), "A", "B", (1, Just 1))]) :: Syntax
let oc = ObjectConfig {links = (0,Just 3), linksPerObject = (0,Just 3), objects = (2,3)}
let alloyFor cd nr = Modelling.CdOd.CD2Alloy.Transform.transform (toOldSyntax cd) [] oc (Modelling.CdOd.MatchCdOd.presenceOfLinkSelfLoops defaultMatchCdOdConfig) False nr ""
let runCommand x = createRunCommand x 2 oc
let parts1 = alloyFor cd1 "1"; parts2 = alloyFor cd2 "2"; parts1and2 = mergeParts parts1 parts2; combined1and2 = combineParts parts1and2; cd1not2 = runCommand "cd1 and (not cd2)" parts1and2; cd2not1 = runCommand "cd2 and (not cd1)" parts1and2
instances1not2 <- getInstances Nothing Nothing (combined1and2 ++ cd1not2)
instances2not1 <- getInstances Nothing Nothing (combined1and2 ++ cd2not1)
Right i1not2 <- runExceptT $ mapM alloyInstanceToOd instances1not2
Right i2not1 <- runExceptT $ mapM alloyInstanceToOd instances2not1
let inst = MatchCdOdInstance { diagrams = M.fromList [(1, cd1), (2, cd2)], Modelling.CdOd.MatchCdOd.generatorValue = 0, instances = M.fromList [('a',([1], head i1not2)), ('b',([2], head i2not1))], Modelling.CdOd.MatchCdOd.showSolution = False }
matchCdOdTask "/tmp/" inst `withLang` English
```

This generates four Graphs:

CD1:
```haskell
([("A",[]),("B",[])],[(Aggregation,"x",(1,Just 1),"B","A",(1,Just 1))])
```
<img width="221" alt="image" src="https://user-images.githubusercontent.com/531939/214087401-36408c22-4488-4881-bcdd-675b893649f4.png">

CD2:
```haskell
([("A",[]),("B",[])],[(Association,"x",(1,Just 1),"A","B",(1,Just 1))])
```
<img width="216" alt="image" src="https://user-images.githubusercontent.com/531939/214087686-b84fee3c-4c2f-4835-8de7-0bacfeda839e.png">

ODa:
```haskell
(["A$0","B$0"],[(1,0,"x")])
```
<img width="438" alt="image" src="https://user-images.githubusercontent.com/531939/214088364-083ab3c5-35c0-4425-a821-cafabe0f2f12.png">

ODb:
```haskell
(["A$0","B$0"],[(0,1,"x")])
```
<img width="434" alt="image" src="https://user-images.githubusercontent.com/531939/214088570-0ff3c0cc-b838-44aa-b4d6-8643ae293564.png">

The (additional) weird thing here is that the latter OD does not even match to either CD, this bug appears, because the decision if an edge should be reversed is being made by checking to which kind of relationship the link name matches, in this case it is both Aggregation and Association (one is calling for a reversion the other is not), as they are both entered into a Map the information for one gets lost.

If we get fresh names for both CDs, both issues resolve. I.e. if we rename the association in CD2, we get:

CD2:
```haskell
([("A",[]),("B",[])],[(Association,"y",(1,Just 1),"A","B",(1,Just 1))])
```
<img width="144" alt="image" src="https://user-images.githubusercontent.com/531939/214103698-52ac5fba-14de-4f88-b8c9-1094c076e4b7.png">

ODb:
```haskell
(["A$0","B$0"],[(0,1,"y")])
```
<img width="438" alt="image" src="https://user-images.githubusercontent.com/531939/214103291-66329621-79a0-4346-a7a6-e86b494cd0d4.png">

But this makes the issue in the former case present: As both ODs are identical (if drawn correctly), both should have been associated with both CDs, not with either.


A resolution (for both issues) here would also be to reverse associations before sending the CD to CD2Alloy and then reverting it back again when finally drawing the OD.
