### ISSUE TITLE
obviate "extra check" for hasAssociationAtOneSuperclass?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#149]
If I recall correctly, after https://github.com/jvoigtlaender/modelling-tasks-internal/commit/53462e8155dcbb00f4fc7d760f64921a71dd455c and https://github.com/jvoigtlaender/modelling-tasks-internal/commit/376f77decc4c03c109eefeaa544502931ae3d0fb, this: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/36cf84f966aea8ccf1f06c7d95329d093a780b17/src/Modelling/CdOd/Generate.hs#L38-L39 should not have been necessary.

Indeed, https://github.com/jvoigtlaender/modelling-tasks-internal/commit/de00743933056d5ba637548c5959137f94d73fb8#r55289667 calls that a "bug".

Fix that bug? (So that it does not remain lurking and maybe bite later.)

Or would all that be obviated by https://github.com/jvoigtlaender/modelling-tasks-internal/issues/61 anyway?

**Comment by marcellussiegburg** [comment]
Yes, tackling this instead/before resolving #61 would add redundant work.

**Comment by marcellussiegburg** [comment]
This is now legacy code which ended up here
https://github.com/jvoigtlaender/modelling-tasks-internal/blob/09bb3852fdc770e8db9da3b02fe33a540d63abe6/legacy-app/generate/Modelling/CdOd/Generate/Generate.hs#L40-L41
(Behind the scenes this property is now enforced using Alloy: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/09bb3852fdc770e8db9da3b02fe33a540d63abe6/src/Modelling/CdOd/CdAndChanges/Transform.hs#L45-L49)
