### ISSUE TITLE
implement generation of a full exercise task

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#15]
... replacing the current `random-task` implementation.

Here is how I envision the process, given a `ClassConfig`:

1. Generate a random class diagram `cd1`. It is fine if it has `anyRedEdge`.
2. From `cd1`, generate a `cd2` via random mutation, still within the given `ClassConfig`. It must not have `anyRedEdge`, so if necessary repeat 2. (Or if no valid mutations exist, go back to 1.)
3. Again from `cd1`, generate a `cd3` via random mutation, still within the given `ClassConfig`. It must not have `anyRedEdge`, so if necessary repeat 3. (No need to check whether `cd2` and `cd3` are different. If they happen to be equal, that will be flagged later on, anyway.)
4. Generate instances for `cd2 and not cd3`. Shuffle them randomly.
5. Generate instances for `cd3 and not cd2`. Shuffle them randomly.
6. Generate instances for `cd2 and cd3`. Shuffle them randomly.
7. We are aiming to take `5` instances overall from the fronts of the lists produced in 4., 5., 6., subject to the constraint that at most `3` are taken from the same list. If that is not possible, go back to 1. If it is possible, make a random such selection.
8. Create pictures for:
    - `cd2`
    - `cd3`
    - the `5` selected instances, named in such a way that we know for each which of the lists 4., 5., 6. it came from

**Comment by marcellussiegburg** [comment]
I assume steps 1, 2, and 3 include checking if cd1, cd2, and cd3 respectively actually generate models.

**Comment by jvoigtlaender** [comment]
Not necessarily. For one thing, cd1 will never be used to generate actual instances. And for cd2 and cd3, what matters is that the objective of step 7 can be met.

Of course, an early test is possible for cd2 and cd3. If either of them has no instance, the objective of step 7 cannot be met. But thst might be premature optimization. (Or not even optimization at all, since checking cd2 and cd3 for satisfiability is extra work that in positive cases cannot be reused.)
