### ISSUE TITLE
refactor Petri-Config-Types

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#151]
I've been thinking for a while that in particular `BasicConfig` is overboarded.

One natural restructuring would be to move those options that affect https://github.com/jvoigtlaender/modelling-tasks-internal/blob/36cf84f966aea8ccf1f06c7d95329d093a780b17/src/Modelling/PetriNet/Types.hs#L484-L489 out of `BasicConfig`. I guess that means these: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/36cf84f966aea8ccf1f06c7d95329d093a780b17/src/Modelling/PetriNet/Types.hs#L372-L375 But maybe there are also other reasonable restructurings.

Also in light of the fact that the config types for the Reach* tasks (as those develop further) could share some parts, with each other and with the other Petri config types.

**Comment by jvoigtlaender** [comment]
Unter anderem wäre dabei umzusetzen, dass `useDifferentGraphLayouts` nicht bei Aufgaben angeboten wird, die nur genau einen Graph anzeigen.

**Comment by jvoigtlaender** [comment]
Die Option `graphLayout` sollte künftig vielleicht `graphLayouts` heißen.

**Comment by marcellussiegburg** [comment]
> Unter anderem wäre dabei umzusetzen, dass `useDifferentGraphLayouts` nicht bei Aufgaben angeboten wird, die nur genau einen Graph anzeigen.

adressed by e6b81e3d
