### ISSUE TITLE
reproducability of random choices

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#152]
... shuffling, specifically, but possibly also relevant more generally.

We had this exchange: https://github.com/jvoigtlaender/modelling-tasks-internal/commit/b3cbf27f47a4e8e3acd5a31fe1661e8f40ea585a#r55459356. At that specific place, the issue seems to have since been resolved. (?)

But maybe not everywhere. For example, the following once are similarly "dangerous"? https://github.com/jvoigtlaender/modelling-tasks-internal/blob/a557484bdde22b158f14ed9b475b41d4103ec6b1/src/Modelling/CdOd/MatchCdOd.hs#L207-L208

**Comment by marcellussiegburg** [comment]
To ensure this, **every** call to `shuffle.*` should be performed within an unspecific `MonadRandom` context or within `RandT`.

As this is a potentially recurring problem: Maybe a custom variant of `MonadRandom` without IO could be defined to ensure appropriate usage on the type level (by not having an instance for `IO`)? Issue is that essentially a reimplementation of even more (like `RandT` would be required).

**Comment by jvoigtlaender** [comment]
An alternative to:
- "make it so that the `m` from a `MonadRandom m =>` context is never directly instantiated to `IO`" (so that randomness does not happen in `IO`, only in more controlled settings)

might be:
- "make it so that no randomness is provided via `MonadRandom m`, only at more specialized types"

That means, for example, and crucially, that `shuffleM :: MonadRandom m => [a] -> m [a]` wouldn't be imported anywhere, only a re-typed version `shuffleM :: (Monad m, RandomGen g) => [a] -> RandT g m [a]` of it.

And a lot of other re-typings would follow from that. Basically, adding the above, then forbidding the import of `Control.Monad.Random.MonadRandom` anywhere (which could theoretically even be checked by CI - brute-forcish if need be, by preventing the string `MonadRandom` from appearing in any file anywhere, except a single white-listed file where the "retyping from one `shuffleM` to another `shuffleM`" and possibly a few other according adjustments happen), would then lead to also functions like `shuffleInstance :: (MonadThrow m, MonadRandom m) => MatchCdOdInstance -> m MatchCdOdInstance` and `takeRandomInstances :: (MonadRandom m, MonadFail m) => Map [Int] [a] -> m (Maybe [([Int], a)])` be retyped to `shuffleInstance :: (Monad m, RandomGen g) => MatchCdOdInstance -> RandT g m MatchCdOdInstance` and `takeRandomInstances :: (Monad m, RandomGen g) => Map [Int] [a] -> RandT g m (Maybe [([Int], a)])`, respectively, so that ultimately randomness will be guaranteed to never happen at `IO`. Or would there be a way that down the line this could be accidentally compromised as well (despite the mentioned import/usage checks)?

**Comment by jvoigtlaender** [comment]
Another possible alternative might be to work with checks (by code inspection) at the interface between Autotool and this repository. That is, whenever integrating a task in Autotool, make sure that the function being called for this is not typed in a way that supports randomness.

For example, currently `nameCdErrorGenerate :: NameCdErrorConfig -> Int -> Int -> IO NameCdErrorInstance` is called from Autotool. That type would not anymore be allowed at that point. Instead, the function would have to be given a type of the form `nameCdErrorGenerate :: (MonadFail m, MonadWhatnot m, ...) => NameCdErrorConfig -> Int -> Int -> m NameCdErrorInstance`. Crucially, neither `MonadRandom` nor `MonadIO` would be allowed to appear inside `...`, because both would allow to smuggle in uncontrolled randomness (instead of relying on one of the two `Int`s being a seed to be used for controlled randomness).

Of course, some extra work would be needed to still enable the function to do `IO` stuff it really needs to do, like calling Alloy. For this, the `call-alloy` package (or an adapter here in this repo) would have to define a `MonadAlloy` class, and `MonadAlloy m` be added to the function's context above. And, of course, there would be a `MonadAlloy IO` instance (so that Autotool can still simply call `nameCdErrorGenerate` at `IO`). But still, since the type of `nameCdErrorGenerate` contains neither `MonadIO` nor `MonadRandom`, no improper use of `IO`/entropy would be possible inside it, and we could see that by just looking at its type once.

I think that the one check (per task type) on the boundary between Autotool and `modelling-tasks` would be sufficient to be sure that randomness stays reproducable. Since after switching the type of, say, `nameCdErrorGenerate` from `... -> IO ...` to the more polymorphic type, this would ripple through to all other relevant functions. If `nameCdErrorGenerate` uses some function `f`, then that function now also neither can have `IO` as return type, nor can involve `MonadRandom` (because in both cases, the more polymorphic `nameCdErrorGenerate` wouldn't be able to call it). Hence, any uses of "unguarded `shuffleM`" in `f` or in functions being called from `f` would be weeded out.

**Comment by marcellussiegburg** [comment]
I agree on the second approach being a good idea for this problem. Which is now described in the separate issue #242. As implementing it would lead to finding misbehaviour of any kind regarding the issue here as well, I propose closing this issue in favour of #242.
