### ISSUE TITLE
(Optionally?) prevent composition constellations with no objects as part

### ISSUE THREAD

**Issue by marcellussiegburg** [fmidue/modelling-tasks#159]
This should affect mainly RepairCd and SelectValidCd where students have to decide if a class diagram is correct.

Consider this diagram:
![class diagram with inherited composition](https://user-images.githubusercontent.com/531939/142634149-9eed022c-5faf-4a2a-988e-f09f13dbe076.png)
There is no possible Object for C, because it would have to be part of `B` and `D`, which in fact is not be possible (violating a part can only be member of one whole).

When we generate a class diagram that possible violates such rules (maybe there are more such subtle rules we have not yet thought of?) then we could still get an instance via CD2Alloy that is allowed but ignores the conflicting part. Consider for instance this slight variation of the diagram above:
![class diagram with inherited composition and independent link](https://user-images.githubusercontent.com/531939/142634388-d0f0330e-79c7-4228-ba3b-8379c4507507.png)
We could still have object diagrams, that consist only of `B`s and `D`s. (Could / should we, somehow prevent such constellations? - better than limiting the number of isolated objects in CD2Alloy)

**Comment by jvoigtlaender** [comment]
One possible criterion might be ("syntactically" on the CD level instead of "semantically" on the OD level): 

- No class may **part**icipate in more than one composition (including inherited ones) if at least one of those compositions has a 1 at the other (diamond shaped) end.

If that condition would be used, also in the DifferentNames and MatchCdOd tasks, https://github.com/jvoigtlaender/modelling-tasks-internal/issues/158 would become "irrelevant".

**Comment by marcellussiegburg** [comment]
Should this property be used in repairCd and selectValidCd? Or is it to subtle (as it is not clear whether the CDs should be syntactically or semantically correct)?

**Comment by marcellussiegburg** [comment]
In RepairCd and SelectValidCd `completelyInhabited` has to be set to `True`. Rendering this issue obsolete (as the Situation is thus prevented). Furthermore `hasCompositionsPreventingParts` is set to `Just False` in these cases preventing even the generation of such class diagrams.
