### ISSUE TITLE
strengere Bewertungsfunktion? (oder mehr in die Syntaxprüfung packen?)

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#161]
Ich bin nicht sicher, ob es eher etwas Spezifisches für einen konkreten Aufgabentyp ist, oder eine generelle Frage der Abgrenzung von Syntax- vs. Semantik-Tests.

Jedenfalls, etwa bei https://autotool.fmi.uni-due.de/route/einsendung/15/229 sind die 50% Punkte doch irgendwie "zu Unrecht geschenkt". Es wurde ganz offenkundig nicht mal versucht, die Aufgabe zu lösen. Wäre die Eingabe `[0, 9]` als "syntaktisch unkorrekt" zurückgewiesen worden (weil nicht aus den vorhanden Optionen ausgewählt wurde), hätte es keine Punkte gegeben.

**Comment by marcellussiegburg** [comment]
Diese konkrete Eingabe wird durch Semantik-Checks abgewiesen. Ich denke, dass dieses Issue obsolet ist (falls doch nicht: bitte erneut öffnen oder besser noch ein neues Issue mit dem konkreten Bewertungsproblem anlegen).
