### ISSUE TITLE
Rename useAllRelationships parameter in DifferentNames-Task

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#162]
From a user perspective (as a lecturer configuring such a task), `useAllRelationships = Nothing` and `useAllRelationships = Just False` sound as if it might then happen that for example there are 8 relationships but only 5 of them are used.

But that's not possible, right? It will only ever be the case that at most one relationship is not used in the OD.

So it would probably be clearer (in particular for future users who don't know anything about the implementation), to have the configuration option be called something like `ignoreSomRelationship` or `dropOneRelationship` or something in that spirit. (And, of course, switching the interpretation of the `Bool`, then.)

**Comment by jvoigtlaender** [comment]
Whereas it probably does not make sense to rename the corresponding property `usesAllRelationships` in the concrete (non-randomized) instances of that task. Because for hand-written instances it is likely indeed possible to give cases where more than one relationship is ignored in the OD. (?)

But does it make sense that this property in the concrete instances type is a `Maybe Bool`? Shouldn't it just be a `Bool`? Since a concrete instance either does or does not use all relationships. There is no "maybe" involved.

**Comment by jvoigtlaender** [comment]
> Since a concrete instance either does or does not use all relationships. There is no "maybe" involved.

Or maybe the point is that even for a concrete instance one might not want to *disclose* to students that definitely nothing is dropped, even when it happens to be the case that nothing is dropped?

**Comment by jvoigtlaender** [comment]
Still, even then the `usesAllRelationships` parameter in concrete instances could be replaced by essentially the value of `fromMaybe False current-usesAllRelationships`.

**Comment by marcellussiegburg** [comment]
> It will only ever be the case that at most one relationship is not used in the OD.

Yes. (Ignoring more than one relationship would require further (probably major) changes.)

> So it would probably be clearer [...] to have the configuration option be called something like [...] `dropOneRelationship`. [...] (And, of course, switching the interpretation of the Bool, then.)

I agree.

> Whereas it probably does not make sense to rename the corresponding property `usesAllRelationships` in the concrete (non-randomized) instances of that task. Because for hand-written instances it is likely indeed possible to give cases where more than one relationship is ignored in the OD. (?)

Yes, renaming for manually created instances itself is counter-intuitive if they ignore more than one relationship.

> But does it make sense that this property in the concrete instances type is a `Maybe Bool`? Shouldn't it just be a `Bool`? 

Yes, it should be `Bool`. (As you rightfully justified already. Unless we want to tell students in the one missing case explicitly that one relationship is not matching to any link or something similar.)
