### ISSUE TITLE
Strategien zur Lesbarkeit von Objektdiagrammen

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#164]
Wegen potentiell problematischer Fälle wie:
![image](https://user-images.githubusercontent.com/5853832/149465777-cb74d4fa-aa83-4fb4-bca6-9b922f7efa70.png)

Eine Herangehensweise wäre beim Zeichnen. Also irgendwie dafür sorgen, dass größere (im Verhältnis zur Schriftgröße) Abstände zwischen den Knoten gesetzt werden. Das würde bestimmte Überlappungen von Labels/Kanten/Knoten reduzieren können. Ob das auf GraphViz- oder Haskell-Ebene passieren könnte, hängt wohl noch von anderen Entwicklungen ab.

Ein anderer Aspekt ist einfach die schiere Anzahl der Links hier. Sicher wären es weniger Links, wenn schon für die Klassenkonfiguration geringere Zahlen gesetzt würden (für Anzahlen von Beziehungen, und evtl. für erlaubte Multiplizitäten). Aber selbst dann ist unter Umständen noch ein Anschwellen im Objektdiagramm möglich. Der eigentliche Punkt ist wohl, dass es in MatchCD und DifferentNames zwar jeweils einen Einstellungsparameter `maxObjects` gibt, aber kein `maxLinks`.

Damit sind Objektdiagramme die einzigen, bei denen dieser Aspekt der Diagrammkomplexität nicht unter Kontrolle des Aufgabenstellers ist. (?)

(Bei Klassen- und Objektdiagrammen hat der Nutzer wohl jeweils in der Aufgabenkonfiguration Parameter zur Verfügung, über welche die maximale Anzahl von darzustellenden Kanten recht explizit gesteuert werden kann.)

**Comment by jvoigtlaender** [comment]
Im Sinne der Steuerung der Vergleichbarkeit ("gleich schwer") verschiedener aus der gleichen Konfiguration erzeugter Instanzen stellt sich natürlich auch die Frage, ob es neben `maxObjects/maxLinks` auch `minObjects/minLinks` geben sollte.

**Comment by marcellussiegburg** [comment]
Die Darstellung wird sich sicherlich noch etwas ändern, wenn der Wechsel auf `diagrams` erfolgt ist.

Weitere Einschränkungen wären auch noch `min/maxLinksPerObject`, um einschränken zu können, wie viele Kanten aus einem Objekt selbst herausgehen (das ist sicherlich insbesondere bei erlaubten/forcierten self-loops wünschenswert).

**Comment by jvoigtlaender** [comment]
> auch noch `min/maxLinksPerObject`, um einschränken zu können, wie viele Kanten aus einem Objekt selbst herausgehen

Stimmt, das könnte auch interessant sein.

Es müsste dann sicher gut mit Defaults gearbeitet werden, damit Aufgabenersteller nicht überfordert sind, so viele verschiedene Detailparameter zu setzen.

Auch etwas Analoges zum Einschränken, wie viele Kanten in ein Objekt **hineingehen**, wäre ja noch denkbar. (oder, zusammenfassend, wie viele Kanten pro Objekt anliegen dürfen)

**Comment by jvoigtlaender** [comment]
Mindestens `maxLinks` bei `MatchCdOd` und bei `DifferentNames` müsste vor der Klausur wohl noch eingeführt werden.

**Comment by marcellussiegburg** [comment]
Die Steuerung ist momentan über zahlreiche Parameter möglich: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/e3f27f832fa544924b3867b0febdd3f676ed67fd/src/Modelling/CdOd/Types.hs#L564-L571 Die Darstellung hat sich durch den Wechsel auf `diagrams` verbessert. Ich sehe momentan nicht die Notwendigkeit, weiter einzuschreiten.
