### ISSUE TITLE
Default-Multiplizitäten nicht immer unterdrücken

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#166]
Beim Ausdruck von Klassendiagrammen sollte durch die Aufgabenkonfiguration gesteuert werden können, ob Default-Multiplizitäten unterdrückt werden. Also letztlich wohl, ob diese beiden Zeilen: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/32e0170cba85d28063d08af770f98643daf10141/src/Modelling/CdOd/Output.hs#L44 https://github.com/jvoigtlaender/modelling-tasks-internal/blob/32e0170cba85d28063d08af770f98643daf10141/src/Modelling/CdOd/Output.hs#L75 wirklich jeweils eine leere Rückgabe haben sollen.

Hintergrund ist unter anderem, dass die Festlegung der Defaults ("1..1" bei Kompositionen, "0..*" ansonsten) erstmal nur für unsere Lehrveranstaltung gilt. Andernorts wird zum Beispiel "0..1" als Default angesehen.

**Comment by marcellussiegburg** [comment]
Ist hierfür vielleicht die Einführung von 3 Konfigurationsparametern sinnvoll?:
```Haskell
  aggregationDefaultMultiplicity :: Maybe (Int,  Maybe Int),
  associationDefaultMultiplicity :: Maybe (Int,  Maybe Int),
  compositionDefaultMultiplicity :: Maybe (Int,  Maybe Int),
```
`Nothing` bedeutet dann, dass keine Defaults angezeigt werden, und ansonsten wird die entsprechend angegebene Multiplizität als default angesehen.
(Und standardmäßig ist der default gesetzt auf:
```Haskell
  aggregationDefaultMultiplicity = Just (0, Nothing),
  associationDefaultMultiplicity = Just (0, Nothing),
  compositionDefaultMultiplicity = Just (1, Just 1), 
```
also "unsere" Defaults)

**Comment by jvoigtlaender** [comment]
Hiermit:
> dass keine Defaults angezeigt werden

meinst du "dass keine Defaults" existieren, und daher **alles** angezeigt wird?

**Comment by jvoigtlaender** [comment]
Grundsätzlich guter Vorschlag.

Es müsste dann noch in den Konfigurations-Checkern sichergestellt werden, dass nicht jemand was völlig unsinniges konfiguriert. Also zum Beispiel `compositionDefaultMultiplicity = Just (0, Nothing)` sollte verboten sein, weil es in UML gar nicht erlaubt ist. Und selbst etwa `aggregationDefaultMultiplicity = Just (2, Just 2)`, obwohl in UML eine legale Multiplizität, wäre vielleicht eher zurückzuweisen (weil niemand bei klarem Verstand seine Aufgaben so konfigurieren sollte)? Man kann es aber natürlich darauf beschränken, nur die in UML wirklich verbotenen Sachen zurückzuweisen.

Ein anderer Aspekt ist der Name der Optionen. Vielleicht könnte noch klar gemacht werden, dass sich das nur auf das (Weglassen von) Anzeigen bezieht? Jemand externes, der erstmals so eine Aufgabe zu konfigurieren hat, könnte bei Optionsname `aggregationDefaultMultiplicity` in einer Klassenkonfiguration, ja auch vermuten, dass damit irgendwie semantischer Einfluss auf die Generierung genommen wird. Also etwa dass die meisten im gewürfelten Multiplizitäten denjenigen Wert haben werden, weil das die DefaultMultiplicity ist.

**Comment by marcellussiegburg** [comment]
`aggregationOmittedDefaultMultiplicity` etc.?

**Comment by jvoigtlaender** [comment]
Ja, trifft es.

**Comment by marcellussiegburg** [comment]
Mir ist aufgefallen, dass hier prinzipiell Interpretationsspielraum bleibt. Beabsichtigt ist, dass sich `aggregationOmittedDefaultMultiplicity` und `compositionOmittedDefaultMultiplicity` nur auf die "Ganzen" Enden beziehen und dass an den "Teilen" die `associationOmittedDefaultMultiplicity` gilt. Macht das `compositionWholeOmittedDefaultMultiplicity` klarer?

**Comment by jvoigtlaender** [comment]
Ja, das klingt plausibel. Für `aggregation` dann wohl auch `aggregationWholeOmittedDefaultMultiplicity`.

**Comment by marcellussiegburg** [comment]
Das ist für den produktiven Einsatz vorbereitet, der nächste Schritt wäre, die Instanzen anzupassen, dass die neu erschaffene Eigenschaft `CdDrawSettings` in den Instanzen (und auch Konfigurationen) direkt auftaucht. (Dabei kann prinzipiell noch infrage gestellt werden, ob das auch bei `DifferentNames` und `MatchCdOd` sinnvoll ist (da die Werte von `withNavigations` und `withNames` hier immer auf `True` gesetzt sein müssen.) Es müssten noch Checks für die Konfigurationen eingeführt werden, die überprüfen, ob `CdDrawSettings` sinnvoll eingestellt sind.
