### ISSUE TITLE
about the formula for integer bitwidth

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#17]
I think some fine-tuning would make sense, which probably would also require obtaining some more information from concrete class diagrams.

Specifically, double the number of objects should be covered (in most, but not all cases, this is covered by `numClasses * numObjects`?).

Also, the maximal concretely occurring multiplicity value should be covered.

And, shouldn't there be a "plus 1" at the end, or a "times 2" before taking the log? After all, if we want to cover the integer value `10`, then bitwidth `4` is not enough (despite `log 2 10` being smaller than `4`). Because with `4` bits, we do not cover the positive integer `10`.

**Comment by marcellussiegburg** [comment]
To your last point:
Yes, there should be a time 2 before adding 1. That was actually what I typed when doing test calculations. (as I can see in my ghci log)

However, I am not sure what you mean by doubling the number of Objects. If the size is still enough for 10 Objects?

**Comment by jvoigtlaender** [comment]
The formula `mul[2, #{o : Obj | no o.get and no get.o}]` occurs in the Alloy code, so the value `2 * maxObjects` should be representable. It is not necessarily a given that `numClasses * maxObjects` covers this.

**Comment by marcellussiegburg** [comment]
Ah, I see.
This suggests that `max (2 * numClasses * maxObjects) (4 * maxObjects) + 1` would be enough.
I will think about the `2 * numClasses * maxObjects + 1` case again, considering current constraints within Template.txt and possible class diagrams.

**Comment by jvoigtlaender** [comment]
Yeah, something like this. We can also play with this later. The one remaining issue is: What if the concrete class diagram contains a multiplicity `1..100`? Then the value `100` will occur in the Alloy file, so should be within the range of representable integers. It does not in an obvious way depent on `numClasses` or `maxObjects`.

**Comment by marcellussiegburg** [comment]
Multiplicities are not configurable at the moment. That is why this could not happen. Should they be configurable as well? And if, In which way?

**Comment by jvoigtlaender** [comment]
I was writing this:

What do you mean by "this could not happen"?

`Transform.hs` contains this code:
```haskell
 makeAssoc att from name to (low, Just up) = "  ObjLU" ++ att ++ "[" ++ from ++ subsCD ++ ", " ++ name ++ ", " ++ to ++ subsCD ++ ", " ++ show low ++ ", " ++ show up ++ "]"
```
The `up` value ends up in the Alloy file. It could be `100` in principle. At least it is not constrained by `maxObjects` or `numClasses`.

My point is not some additional configurability, but that the values occurring for multiplicities in the `associations` part of a "class diagram syntax" should be taken into account.

**Comment by jvoigtlaender** [comment]
But then I realised:

I had a misunderstanding of what the searchspace is about. It changes how many associations there can be in a class diagram, not the multiplicities. Makes sense now.

**Comment by marcellussiegburg** [comment]
Okay, so I conclude: for now it would be okay, to use the suggested formula?

**Comment by jvoigtlaender** [comment]
Yes.
