### ISSUE TITLE
"defaultNet" is handled wrong?

### ISSUE THREAD

**Issue by marcellussiegburg** [fmidue/modelling-tasks#175]
The current defaultNet consists of `givenPlaces`, `givenTransitions`, `defaultFlow` and `defaultTokens`. However, there is no constraint forbidding `defaultFlow` between e.g. `Places` not being element of `givenPlaces` and `Transitions`. Furthermore, the parser currently completely ignores `givenPlaces` and `givenTransitions` parsing always `Places` and `Transitions`. At the moment this does not seem to lead to major errors, because it seems to always hold that `givenPlaces = Places` and `givenTransitions = Transitions`. At least adding the constraint
```Alloy
  some (Places - givenPlaces) or some (Transitions - givenTransitions)
```
does not lead to any instance (even if this is the only constraint of the predicate besides sizes for `Transitions` and `Places`).
This seems to be the case, because `givenPlaces` is the only subclass of `Places` which leads to Alloy never picking any `Places` which are no `givenPlaces` the equivalent holds for `Transitions`. This could be lifted, by adding
```Alloy
abstract sig addedPlaces extends Places{}
abstract sig addedTransitions extends Transitions{}
```
which in turn seems to allow Alloy picking values of `givenPlaces` and `addedPlaces` and thus allowing `givenPlaces` being a proper subset of `Places`.
If this happens, this could lead to returned instances violating constraints due to a missing fact like
```Alloy
all n : Nodes - givenNodes | no n.defaultFlow.Int and no defaultFlow.Int.n
```
Furthermore, parsing of instances at the Haskell side would require amendment as it would lead to isolated nodes if `givenPlaces` and `givenTransitions` remain untreated.

**Comment by jvoigtlaender** [comment]
Can you explain in what context those observations were made?

With https://github.com/jvoigtlaender/modelling-tasks-internal/blob/dev/alloy/petri/PetriAdditions.als loaded or not?

I actually think that everything is as it should be. What exactly is the problem?

**Comment by marcellussiegburg** [comment]
I think, I stumbled across this when checking retrievable instances due to changes made for #82. This happened indeed with `PetriAdditions.als` not loaded. My assumption was probably that Pick-Tasks would allow for such changes. As only `givenPlaces` are picked anyway in this case it seems to not lead to any unexpected errors.
