### ISSUE TITLE
optionales Erzwingen/Verbieten der Beteiligung von Source Transitions an Nebenläufigkeiten

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#176]

**Comment by jvoigtlaender** [comment]
... ist aber vielleicht schon durch das Erzwingen/Verbieten der *Existenz* von Source Transitions abgedeckt

**Comment by jvoigtlaender** [comment]
... zumindest beim FindConcurrency-Task, nicht bei PickConcurrency

**Comment by marcellussiegburg** [comment]
(see also #177)

**Comment by jvoigtlaender** [comment]
Erzwingen der Existenz von Source Transitions bei einem PickConcurrency-Task hieße, dass zwei Petrinetze zu generieren sind, von denen:
- eines eine Source Transition und keine weitere überhaupt aktivierte Transition enthält
- das andere eine Source Transition und noch genau eine weitere aktivierte Transition enthält

Das ist schon recht spezifisch. Kann man machen. Aber das Ermöglichen des Verbietens von Source Transitions scheint der wichtigere Punkt zu sein.
