### ISSUE TITLE
bei Pick-Tasks die Existenz von Source Transitions verbietbar machen?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#177]
Da Source Transitions bei der Suche nach Konflikten ignoriert werden können, kann es zu von vornherein verschieden schweren Instanzen kommen, indem eine Studierende zufällig viele Source Transitions in den angezeigten Petrinetzen hat, eine andere nicht.

**Comment by marcellussiegburg** [comment]
I think this is very reasonable. Maybe all `AdvConfig` constraints should be enabled for both Pick-Tasks? For PickConcurrency Tasks source transitions can also make it easier. Sink transitions and self-loops could be enforced or disabled in both cases for other reasons.

**Comment by jvoigtlaender** [comment]
Im Prinzip ja. Ein Nachteil könnte sein, dass die Implementierung aller `AdvConfig`s für die Pick-Tasks ziemlichen Code-Overhead erzeugt. Denn die Bedingungen müssten dann wohl für beide anzuzeigenden Netze erzwungen werden (damit keine Strategie möglich ist wie "wenn ich die Config kenne und nur eines der angezeigten Petrinetze einen Self-Loop hat, dann weiß ich, welches Netz das zu pickende ist"). Und dafür existieren wohl noch keine Prädikate, sondern das ist Alloy-seitig nur für das "nicht-default" Netz vorbereitet, was bei den Find-Tasks ausreicht.

Mein minimaler Vorschlag in diesem Issue ist more modest und vor allem spezifischer:
- betrifft nur source transitions
- will sie nur verbietbar, nicht auch erzwingbar, machen

Das ginge mit weniger Aufwand.

**Comment by jvoigtlaender** [comment]
Angesichts https://github.com/jvoigtlaender/modelling-tasks-internal/issues/176#issuecomment-1202992708 scheint der minimal desirable change zu sein: Source Transitions bei PickConflict und PickConcurrency verbietbar machen.
