### ISSUE TITLE
zusätzliche Ausgabe von Klassendiagrammen mit Assoziationsnamen (und eventuell Navigationsrichtungen) in SelectValidCD-Feedback

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#209]
Sagen wir, so etwas taucht in einer Aufgabenstellung auf:
![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/c599e493-f1a0-46a3-a714-0c53ac786cda)
Assoziationen/Aggregationen/Kompositionen sind nicht benamt.

Jetzt wird gefragt, ob es valide ist.

**Comment by jvoigtlaender** [comment]
Sagen wir, es ist valide, aber die Eingabe behauptet, es sei nicht valide.

Nun wird im Feedback ein passendes Objektdiagramm ausgegeben (als Beleg für die Validität).

Aus bekannten Gründen kann es schwierig sein, die Passung nachzuvollziehen. Wir verwenden ansonsten bei Passungs-Aufgaben ja absichtlich immer benamte Assoziationen. Hier ist das Ausgangs-Klassendiagramm dahingehend aber nicht benamt.

Vorschlag wäre nun: Im Feedback wird das Klassendiagramm nochmals ausgegeben, aber mit Namensbeschriftung der Assoziationen. Dann wird (wie bisher) ein Objektdiagramm ausgegeben, ebenfalls mit Namensbeschriftung der Links.

**Comment by jvoigtlaender** [comment]
Ein ähnliches Argument könnte auch noch für die Navigationsrichtungen gelten, da auch ohne diese ja die Passung CD<->OD manchmal nicht so klar ist. Also es könnte, wenn in der Aufgabenstellung die Navigationsrichtungen unterdrückt waren, für die Feedback-Ausgabe doch die Anzeige von Navigationsrichtungen eingeschaltet werden, um die Passung nachvollziehbarer zu machen.

(Scheint mir allerdings nicht ganz so wichtig wie bzgl. der Namen.)

**Comment by jvoigtlaender** [comment]
Auch noch, umgekehrt: Sagen wir, der Klassendiagrammkandidat ist nicht valide, aber die Eingabe behauptet, er sei valide.

Dann wird ein Grund für den Fehler ausgegeben, in der Art "Wenn eine Assoziation zwischen As und Bs mit den Multiplizitäten so-und-so entfernt würde, (erst) dann wäre es valide." Das wird so umschrieben, weil keine Assoziationsnamen im Diagramm stehen, auf die Bezug genommen werden könnte.

Da wäre es ja aber auch möglich, den Kandidaten nochmal auszugeben, diesmal mit Assoziationsnamen, und dann zu schreiben: "Wenn Assoziation x entfernt würde, ...".

Fraglich ist vielleicht noch, ob das immer passieren sollte, oder nur wenn relevant. Also wenn etwa der auszugebende Grund ist: "Wenn eine Vererbung zwischen A und B entfernt würde", dann ist es nicht relevant/hilfreich, das Klassendiagramm nochmal mit benamten Assoziationen auszugeben, weil dies ja gar nichts zur Interpretation des Feedbacks beiträgt.

(Ob Navigationsrichtungen ein- oder ausgeschaltet sind, ist für diesen Fall des Feedbacks wahrscheinlich egal.)

**Comment by marcellussiegburg** [comment]
Ich verstehe den Teil der validen Klassendiagramme des Issues so:
> Vorschlag wäre nun: Im Feedback wird das Klassendiagramm nochmals ausgegeben, aber mit Namensbeschriftung der Assoziationen. Dann wird (wie bisher) ein Objektdiagramm ausgegeben, ebenfalls mit Namensbeschriftung der Links.

Hier sollte das Klassendiagramm **immer** noch einmal mit Namen angezeigt werden, wenn sich Feedback auf Namen bezieht.
> Also es könnte, wenn in der Aufgabenstellung die Navigationsrichtungen unterdrückt waren, für die Feedback-Ausgabe doch die Anzeige von Navigationsrichtungen eingeschaltet werden, um die Passung nachvollziehbarer zu machen.

Hier sollte das Klassendiagramm **nur** mit Navigationsrichtungen angezeigt werden, **wenn** es in der Aufgabenkonfiguration **so festgelegt** wurde (= neuer Parameter).

**Comment by jvoigtlaender** [comment]
> Hier sollte das Klassendiagramm immer noch einmal mit Namen angezeigt werden, wenn sich Feedback auf Namen bezieht.

... sofern in der ursprünglichen Aufgabenstellung die Anzeige dieser Namen unterdrückt war.

**Comment by jvoigtlaender** [comment]
Wobei "wenn sich Feedback auf Namen bezieht" ja gar nicht unbedingt explizit zutrifft, wenn einfach nur ein Objektdiagramm angezeigt wird. Da wird nicht explizit auf Namen bezogen, aber sie sind eventuell nötig zum Verständnis.

**Comment by jvoigtlaender** [comment]
> Hier sollte das Klassendiagramm nur mit Navigationsrichtungen angezeigt werden, wenn es in der Aufgabenkonfiguration so festgelegt wurde (= neuer Parameter).

Hier bin ich mir tatsächlich unsicher. Also ob wirklich ein neuer Parameter für einen totalen Nischenfall (die Anzeige der Richtungen war ausgeschaltet, aber ein Klassendiagramm wurde fälschlich als invalide deklariert, und wir möchten jetzt deshalb ein Objektdiagramm dafür anzeigen, aber machen uns Sorgen, dass dieses ohne Navigationsrichtungen nicht klar genug passend ist) gerechtfertigt ist. Er ist so speziell, dass ich mir nicht mal einen guten Namen dafür überlegen könnte.

Also vielleicht lassen wir es erst mal ohne neuen Parameter.

Dann blieben zwei mögliche Verhaltensweisen:
1. Es wird die ursprüngliche Konfiguration respektiert. Also wenn die Aufgabenstellung keine Navigationsrichtungen ausgab, dann wird das auch im Feedback nicht geändert.
2. Es wird vorsichtshalber im Feedback mit Navigationsrichtungen gearbeitet, ohne Beeinflussungsmöglichkeit durch Konfiguration.

Vielleicht lieber die 1. Variante. Denn bei der 2. Variante könnte ja der Einwand kommen: "Na ja, okay, mit diesem Pfeil jetzt ist das als valides Klassendiagramm zu erkennen. Aber die Aufgabenstellung hatte dort keine Pfeilspitze. Dadurch war es irgendwie nicht klar, ob der Kandidat legal ist. Es lag an der fehlenden Spitze, dass ich gesagt habe, der Kandidat sei invalide."

**Comment by jvoigtlaender** [comment]
Ich hatte das oben nur auf die Klassendiagramme bezogen, aber genaugenommen ist zumindest das mit den Pfeilspitzen wohl auch für Objektdiagramme relevant. Aktuell gibt es etwa zu 

![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/aca7d205-4ba0-49fb-83ff-2e432fc89f97)

folgendes Feedback:

![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/a2ee1087-76c7-4dad-85c4-f9e3b6d5eacb)

Zu den Reichtungen für `x` und `w` im Objektdiagramm gibt es im Klassendiagramm keine Entsprechung. Hätte dann hier, weil Klassendiagramm ohne Navigationsrichtungen, auch das Objektdiagramm im Feedback ohne Navigationsrichtungen ausgegeben werden sollen? (Für die Aggregationen und Kompositionen wäre dass gewissermaßen ein Informationsverlust, denn für diese gibt es im Klassendiagramm wegen der Rauten ja eine Richtung.)

**Comment by marcellussiegburg** [comment]
Ich denke, konsistenter Weise sollten die Pfeilspitzen weggelassen werden, wenn diese im ursprünglichen Klassendiagramm nicht existierten. Letztlich könnte durch diese Information wieder herausgerechnet werden, wie die Navigationsrichtung im ursprünglichen Klassendiagramm war und somit das Argument gelten:
> "Na ja, okay, mit diesem Pfeil jetzt ist das als valides Klassendiagramm zu erkennen. Aber die Aufgabenstellung hatte dort keine Pfeilspitze. Dadurch war es irgendwie nicht klar, ob der Kandidat legal ist. Es lag an der fehlenden Spitze, dass ich gesagt habe, der Kandidat sei invalide."

Ja, es gibt dann einen Informationsverlust. Bei den Kompositionen müsste die verlorene Information aber immer wiederherstellbar sein (durch das Zyklenverbot). Und bei den Aggregationen sollte die Information nur bei einem Zyklus nicht wiederherstellbar sein. (Das müssten sich die Studierenden dann selbst überlegen und aktiv nachvollziehen.)

**Comment by jvoigtlaender** [comment]
> Ich denke, konsistenter Weise sollten die Pfeilspitzen weggelassen werden, wenn diese im ursprünglichen Klassendiagramm nicht existierten.

Ja, ich stimme zu. Ist eine Änderung zum aktuellen Verhalten, aber in Richtung Einheitlichkeit und "least surprise".

**Comment by jvoigtlaender** [comment]
Dieser Teil wurde noch nicht umgesetzt, oder?

https://github.com/jvoigtlaender/modelling-tasks-internal/issues/209#issuecomment-1814397756
