### ISSUE TITLE
Anzeige von Selbstbeziehungen in Klassendiagrammen problematisch

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#211]
Zum Beispiel bei meiner Instanz von `RepairCd`-`Task07` wird im Feedback dies angezeigt:

![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/d372ad39-357f-4db0-8893-98b789f1c61c)

Hinzugefügt wurde: 

![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/6d450e67-f430-4f55-86fa-380e73d564da)

Also dieser Teil:

![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/8616b075-bbb2-4b8e-8b6e-ca2c856c1654)

Das ist aber extrem schwer zu sehen.

Ist das immer ein Problem (auch bei anderen Aufgabentypen), wenn `selfRelationships = True` oder `selfInheritances = True` gesetzt wird?

**Comment by marcellussiegburg** [comment]
Das Problem tritt leider auf, weil das Layout mittels `Graphviz` nicht perfekt zu dem von `diagrams` gezeichneten passt. Eventuell wäre eine Möglichkeit hier die Größe des zu zeichnenden Kantenbogens irgendwie zu berechnen und dann entsprechend zu agieren (zum Beispiel die Austrittswinkel anzupassen).
Das Problem tritt potenziell prinzipiell auf, wenn Selbst-Beziehungen existieren.

**Comment by marcellussiegburg** [comment]
Die bisherigen Anpassungen haben Veränderung gebracht:
![example](https://github.com/user-attachments/assets/4fbf9c04-e615-4d4b-9b56-34e2549b8fd3)
Ein paar Extrembeispiele:
![cd](https://github.com/user-attachments/assets/12e2007e-0834-4bc1-a6df-9afabc079713)
![od](https://github.com/user-attachments/assets/d02fa00c-80cc-4d83-965b-850a571e7bcd)
Da die Self-Relationships bei den CDs gezählt werden, könnte ein solches CD im Moment gar nicht auftauchen.
Was das OD betrifft, halte ich die Lesbarkeit für ausreichend.

**Comment by marcellussiegburg** [comment]
Es gibt momentan keine Garantie dafür, dass nicht doch ein problematischer Fall, wie im Issue gezeigt, auftaucht.
Insbesondere wurde das hier gar nicht verfolgt:
> Eventuell wäre eine Möglichkeit hier die Größe des zu zeichnenden Kantenbogens irgendwie zu berechnen und dann entsprechend zu agieren

Ich konnte durch zufälliges Ausprobieren keinen solchen, problematischen Fall erzeugen. Ich schlage vor, in den Übungen Selbstzyklen wieder zuzulassen, bis ein solches Problem wieder auftaucht und dann dieses Issue wieder (oder ein neues) zu öffnen. [Vielleicht tritt der Fall jetzt auch nicht mehr auf.]
