### ISSUE TITLE
Worries about impact of various "composition constraints" on tasks

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#215]
Bin mir nicht sicher, wie ernst die Sorgen sein sollten, aber in der Vorbereitung der Besprechung von Beispielen, und auch im Kontext der Probleme mit den Kompositionszyklen bin ich nochmal bzgl. einiger "Randfälle" stutzig/unsicher geworden.

Es geht so um Fälle wie:

1. 
![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/0615f204-890f-4615-9d1c-2fbde8861fd9)
2. 
![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/4af5efd0-b1d6-45d4-8f2a-3acaf7d5adb1)
3. 
![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/ea439444-ce2f-41fa-9808-b411565804fc)
4. 
![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/4e9e7ed5-8843-4e89-bbe0-f978b742b98f)
5. 
![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/8903c2f0-6bfc-4c59-8b13-0c146b266f9e)

Vor allem erstmal bei Aufgaben zur Korrektheit von Klassendiagrammen.

Also etwa der 1. Fall, wird der als inkorrekt angesehen, und kommt auch in Aufgaben der SelectValidCd/RepairCD/Fehler-Finden Familie vor?

Er würde rausgefiltert werden, wenn man Objektbewohntheit verlangt und gleichzeitig verlangt, dass alle Beziehungen benutzt werden müssen. Also würde sowas zumindest bei Setzen dieser Optionen nicht mehr als korrektes Klassendiagramm angezeigt, richtig? Aber kommt es umgekehrt als inkorrektes Klassendiagramm vor? Und/oder kann solch eine Situation "aus Versehen" in einem sowieso schon inkorrekten Klassendiagramm für die Fehler-Finden-Aufgabe entstehen, und dann haben die Studierenden die Wahl zwischen zwei möglichen Fehlern (bzw. einer der Fehler, den es aus ihrer Sicht gibt, wird vielleicht gar nicht zur Auswahl aufgelistet)?

Ab dem 2. Fall wird es hakliger. Schon allein weil selbst in der Vorlesung das etwas ambivalent gehalten wird, ob sowas nun inkorrekt ist, oder nur korrekt-aber-nie-sinnvoll (weil man die eine von den beiden Kompositionen nie beleben kann, da immer die andere zwangsweise verwendet wird). Also insbesondere wenn es in einer Fehler-Finden-Aufgabe neben dem "eigentlichen" Fehler vorkäme, wäre das korrekte Verhalten des Aufgabentyps eventuell fraglich (aber auch schon bei RepairCD).

Der 3. Fall ist wahrscheinlich doch in jeder Hinsicht unproblematisch, er wird ja auch in der Vorlesung explizit positiv mit Beispielen belegt.

Beim 4. Fall bin ich mir hinsichtlich der "Objektbewohntheit" nicht ganz sicher, wie es sein müsste und wie die Alloy-Formalisierung es tatsächlich macht (das könnte also dann auch für DifferentNames etc. relevant sein). Also dürfte etwa ein Objekt der Teil-Klasse gleichzeitig über beide Beziehungen mit einem Objekt der Ganzes-Klasse verbunden sein? Es gilt ja "jedes Teil gehört nur zu einem Ganzen". Das schließt "gleichzeitige Verwendung beider Beziehungen" eigentlich aus. Aber auch in dem Fall, wo sie beide zum gleichen Ganzes-Objekt führen? Das kommt dann ja stark auf die Formalisierung an, ob man ausdrückt "nur ein ausgehender Kompositions-Link" oder "nur ein Objekt, das durch Kompositions-Links erreicht wird".

Und selbst wenn man den 4. Fall ausschließt durch Konfigurationsoption "keine Doppelbeziehungen", kann es wegen Vererbung (siehe 5. Fall) ja implizit doch auftreten.

Und dieses implizit-über-Vererbung aus dem 5. Fall könnte ja auch im 1. und 2. Fall (wenn dort A und B in einer Vererbungsbeziehung stünden) die Situation nochmal verkomplizieren, also ob man diese dann als gültig oder ungültig ansehen muss, ob das aus der Objektbewohntheit (bzw. deren Scheitern) folgt, und wie sich letztere überhaupt verhält in solchen Fällen, wo beide Kompositionen zum "selben" Ganzen führen. Und dann ist wieder die Frage, ob dadurch Entscheidungen etwa bei der Fehler-Finden-Aufgabe immer eindeutig zu treffen sind...

**Comment by jvoigtlaender** [comment]
Zur Erinnerung: Selbst Fälle wie der 1. oben werden bei den Aufgaben zur Korrektheit von Klassendiagrammen nicht als "Fehlerkandidat" produziert (sondern allenfalls als "UML-korrekter Kandidat" verhindert).

**Comment by marcellussiegburg** [comment]
> Aber kommt es umgekehrt als inkorrektes Klassendiagramm vor?

Der konkrete Grund, dass das nicht passiert, ist, dass es nicht als Eigenschaft bei der Klassendiagrammgenerierung in Alloy formuliert ist. Dementsprechend kann ein solches Klassendiagramm zunächst (prinzipiell alle genannten Fälle) als korrektes Klassendiagramm generiert werden.

> Er [der 1. Fall] würde rausgefiltert werden, wenn man Objektbewohntheit verlangt und gleichzeitig verlangt, dass alle Beziehungen benutzt werden müssen. Also würde sowas zumindest bei Setzen dieser Optionen nicht mehr als korrektes Klassendiagramm angezeigt, richtig? 

Genau.

Die Fälle 2 bis 5 würden prinzipiell als gültig angesehen werden und es könnten (je nach konkreter Ausprägung und Konfiguration) auch ODs generiert werden.

> Also dürfte etwa ein Objekt der Teil-Klasse gleichzeitig über beide Beziehungen mit einem Objekt der Ganzes-Klasse verbunden sein? Es gilt ja "jedes Teil gehört nur zu einem Ganzen". Das schließt "gleichzeitige Verwendung beider Beziehungen" eigentlich aus. Es gilt ja "jedes Teil gehört nur zu einem Ganzen". Das schließt "gleichzeitige Verwendung beider Beziehungen" eigentlich aus. Aber auch in dem Fall, wo sie beide zum gleichen Ganzes-Objekt führen?

Das sehe ich auch so. Ich würde das auch im letzteren Fall so sehen. Die Formalisierung lässt momentan auch nicht zu, dass dasselbe Teil-Objekt beide Beiziehungen erhält. Wenn das in der Vorlesung anders (oder nicht genau betrachtet wird), ist das vielleicht sogar bei allen Aufgabentypen relevant.

Die Fälle sind sicherlich alle unwahrscheinlich (wenn nicht explizit darauf abgezielt wird). Dennoch sollten sie wohl formal klar geregelt sein. Es gibt hier meines Erachtens 3 Kategorien, denen die Situation jeweils zuzuordnen ist, die die Behandlung beeinflusst:
a. Es ist eindeutig ein Fehler!
b. Es ist eindeutig erlaubt!
c. Die Situation sollte gemieden werden!

Zu a. würde ich vorschlagen, einen Konstruktor für eine (ungültige) Klassendiagramm-Eigenschaft einzuführen, die dann explizit aktiviert werden kann. Dafür wird eine Formalisierung in der Generierung der Klassendiagramme erstellt. Bei b. wäre nichts zu unternehmen, alternativ könnte eine erlaubte Eigenschaft formalisiert werden, die explizit ein und ausgeschaltet werden kann (Steuerung des Schwierigkeitsgrads). Bei c. würde ich dafür auch eine Formalisierung erstellen, die immer aktiv wäre und solche Situationen generell vermeidet.

Mein Vorschlag für die Zuordnung dieser Fälle wäre:

1. a.
2. c.
3. b.
4. c.
5. c.

Letztlich hängt die Entscheidung dieser Einteilung wohl davon ab, wie genau diese Fälle zukünftig in der Vorlesung betrachtet werden sollen. (Zum Beispiel könnten 4. und 5. auch der Kategorie b zugeordnet werden, wenn diese Frage hier betrachtet wird:
> Aber auch in dem Fall, wo sie beide zum gleichen Ganzes-Objekt führen?

)

**Comment by marcellussiegburg** [comment]
Dieser Kommentar https://github.com/jvoigtlaender/modelling-tasks-internal/issues/159#issuecomment-2163488245, wirkt sich auch hier aus. Bei `SelectValidCd` und `RepairCd` kann 1. demzufolge (momentan) nicht auftreten. `hasCompositionsPreventingParts` ist nur bei `NameCdError` auf `Nothing` gesetzt, wenn es um die Suche nach einer Behebung eines Problems geht. Es sollte kein Problem sein, das dort auch zu verbieten, das kann getan werden, wenn die gewünschte Behandlung dieses Falls klar ist. Ansonsten kann 1. nie auftreten – bei keiner der Aufgaben!

*Auch in Kombination mit Vererbungen verhindert `hasCompositionsPreventingParts` diesen Fall!*

*Edit: Ergänzung*

**Comment by marcellussiegburg** [comment]
Durch die Forderung `usesEveryRelationshipName` wird effektiv bei `NameCdError`, `SelectValidCd` und `RepairCd` verhindert, dass 2. auftreten kann. (Allerdings erst beim Suchen eines Objektdiagramm – hier wäre eventuell Optimierungspotenzial.) Bei den anderen beiden Aufgabentypen `MatchCdOd` und `DifferentNames` kann dieser Fall auftreten.

**Comment by marcellussiegburg** [comment]
4. Kann momentan bei `MatchCdOd`, `SelectValidCd` und `RepairCd` nicht auftreten. Bei den anderen beiden Aufgabentypen `DifferentNames` und `NameCdError` aber schon.

**Comment by marcellussiegburg** [comment]
3. und 5. können momentan überall potenziell auftreten.

**Comment by jvoigtlaender** [comment]
Also erstmal, diesem hier stimme ich zu:

> Mein Vorschlag für die Zuordnung dieser Fälle wäre:
> 
> 1. a.
> 2. c.
> 3. b.
> 4. c.
> 5. c.

Dann zu den einzelnen Fällen.

-------

Zum 1. Fall entnehme ich hieraus:
> `hasCompositionsPreventingParts` ist nur bei `NameCdError` auf `Nothing` gesetzt, wenn es um die Suche nach einer Behebung eines Problems geht. Es sollte kein Problem sein, das dort auch zu verbieten, das kann getan werden, wenn die gewünschte Behandlung dieses Falls klar ist. Ansonsten kann 1. nie auftreten – bei keiner der Aufgaben!

dass er nie auftreten wird (ggfs. nachdem du noch das "`hasCompositionsPreventingParts` ist nur bei `NameCdError` auf `Nothing` gesetzt" verändert hast). Das bedeutet insbesondere auch, dass diese Situation auch nicht in einem absichtlich inkorrekten Klassendiagramm vorkommen wird, richtig? Verzichten wir darauf, diesen Fall auch bewusst als Fehlerfall abzufragen. Insbesondere bräuchten wir dies dann nicht machen:
> Zu a. würde ich vorschlagen, einen Konstruktor für eine (ungültige) Klassendiagramm-Eigenschaft einzuführen, die dann explizit aktiviert werden kann. Dafür wird eine Formalisierung in der Generierung der Klassendiagramme erstellt.

-------

Zum 2. Fall entnehme ich hieraus:
> Durch die Forderung `usesEveryRelationshipName` wird effektiv bei `NameCdError`, `SelectValidCd` und `RepairCd` verhindert, dass 2. auftreten kann. (Allerdings erst beim Suchen eines Objektdiagramm – hier wäre eventuell Optimierungspotenzial.) Bei den anderen beiden Aufgabentypen `MatchCdOd` und `DifferentNames` kann dieser Fall auftreten.

dass noch Anpassungsbedarf besteht.

Zunächst mal zur Vergewisserung: Der Ausschluss des Vorkommens in `NameCdError`, `SelectValidCd` und `RepairCd` bezieht sich auch auf Vorkommen in inkorrekten Klassendiagrammen (also etwa in den Distraktoren in `SelectValidCd`)? Es kann nicht vorkommen, dass in einem der angezeigten inkorrekten Klassendiagramme solch eine 2. Situation vorkommt? (Der `usesEveryRelationshipName`-Effekt dürfte dort ja nicht wirken, da für inkorrekte Klassendiagramme kein Objekt-Bewohntheits-Test stattfindet.)

Bezogen auf die beiden Aufgabentypen `MatchCdOd` und `DifferentNames` (aber eventuell würde es auch obigen Punkt obsolet machen): Würde das durch folgenden Vorschlag aus https://github.com/jvoigtlaender/modelling-tasks-internal/issues/159#issuecomment-974159305 adressiert?
> One possible criterion might be ("syntactically" on the CD level instead of "semantically" on the OD level): 
> 
> - No class may **part**icipate in more than one composition (including inherited ones) if at least one of those compositions has a 1 at the other (diamond shaped) end.

Das würde einfach jedes Vorkommen von etwas wie der 2. Situation ausschließen, egal ob nun in korrekten oder in inkorrekten Klassendiagrammen. (Es würde es wohl auch überflüssig machen, bezüglich der 1. Situation noch irgendwas hinsichtlich  "`hasCompositionsPreventingParts` ist nur bei `NameCdError` auf `Nothing` gesetzt" zu unternehmen.)

---------

Zum 3. Fall ist offenbar nichts zu unternehmen.

------

Zum 4. und 5. Fall:

Wäre es vielleicht am besten, diese auch einfach syntaktisch auszuschließen, für sowohl korrekte als auch inkorrekte Klassendiagramme, in ähnlicher Weise wie der oben zitierte Vorschlag aus #159 zum 2. Fall?

**Comment by marcellussiegburg** [comment]
Danke für das Feedback.
___
Zum 1. Fall
> Das bedeutet insbesondere auch, dass diese Situation auch nicht in einem absichtlich inkorrekten Klassendiagramm vorkommen wird, richtig?

Ja, genau
___
Zum 2. Fall
>Zunächst mal zur Vergewisserung: Der Ausschluss des Vorkommens in NameCdError, SelectValidCd und RepairCd bezieht sich auch auf Vorkommen in inkorrekten Klassendiagrammen (also etwa in den Distraktoren in SelectValidCd)? Es kann nicht vorkommen, dass in einem der angezeigten inkorrekten Klassendiagramme solch eine 2. Situation vorkommt?

Doch, dieser Fall kann in inkorrekten Klassendiagrammen auftauchen, d.h. in diesen Klassendiagrammen gibt es einen von uns (eindeutig) als ungültig angesehenen Grund plus die genannte Situation.

> Würde das durch folgenden Vorschlag aus https://github.com/jvoigtlaender/modelling-tasks-internal/issues/159#issuecomment-974159305 adressiert?

Ja
___
Zum 4. und 5. Fall

> Wäre es vielleicht am besten, diese auch einfach syntaktisch auszuschließen, für sowohl korrekte als auch inkorrekte Klassendiagramme, in ähnlicher Weise wie der oben zitierte Vorschlag aus https://github.com/jvoigtlaender/modelling-tasks-internal/issues/159 zum 2. Fall?

Ich stimme zu.
___
Damit ist das weitere Vorgehen:
- [x] für 1: "`hasCompositionsPreventingParts` ist nur bei NameCdError auf Nothing gesetzt" verändern
- [x] für 2: Behebung entsprechend https://github.com/jvoigtlaender/modelling-tasks-internal/issues/159#issuecomment-974159305
- [x] für 4 und 5: Behebung analog zu https://github.com/jvoigtlaender/modelling-tasks-internal/issues/159#issuecomment-974159305

**Comment by jvoigtlaender** [comment]
Ist das 1. Vorgehensitem denn überhaupt nötig, wenn das 2. gemacht wird?

**Comment by marcellussiegburg** [comment]
Semantisch ist es nicht notwendig, allerdings ist der Aufwand (sehr) gering und es dokumentiert das gewünschte Verhalten. (Falls z.B. in Zukunft doch noch eine andere Entscheidung bzgl. Fall 2 getroffen werden möchte/sollte.)

**Comment by jvoigtlaender** [comment]
Okay. Mich wundert nur, dass es gemäß des Zusatzes ", wenn es um die Suche nach einer Behebung eines Problems geht" ja scheinbar nicht so ist, dass diese Änderung etwas mit den anzuzeigenden Diagrammen zu tun hat. Sondern in einer "anderen" Phase wirkt. So gesehen dokumentiert es also auch nicht unbedingt das gewünschte Verhalten hinsichtlich der generierten Diagramme, sondern beschränkt eher irgendwie den Semantik-Check?

**Comment by marcellussiegburg** [comment]
Letztlich beschränkt es die Diagramme, die bei der Behebung des Problems entstehen also nicht nur den Semantik-Check. Aber vielleicht hat es trotzdem wirklich weniger mit diesem Issue zu tun. Die momentan durchgeführte Lockerung des Constraints sollte eigentlich gar keinen Einfluss haben (da sowieso nur etwas entfernt wird – dementsprechend kann und sollte die Zeile entfernt werden).

**Comment by marcellussiegburg** [comment]
Ich habe zwei weitere Fälle für 2 identifizieren können (wenn Vererbungen dazu kommen)
2a) ![2a](https://github.com/user-attachments/assets/60cd372c-a235-4487-bc2f-55d0d23898e0)

2b) ![2b](https://github.com/user-attachments/assets/e8e5db8f-99ab-4a9d-8bc8-b2bdba1e3991)
Ich denke, dass 2a) gemieden werden sollte, 2b) aber nicht unbedingt.
(Analog existiert ein Fall, der meiner Meinung nach noch gravierender als 2a ist und verboten sein müsste – an beiden Kompositionen eine 1)

**Comment by jvoigtlaender** [comment]
> Ich denke, dass 2a) gemieden werden sollte, 2b) aber nicht unbedingt.

Kann ich nachvollziehen.

Sind diese Fälle aber echt neu bzw. nicht schon durch Entscheidungen weiter oben ausgeschlossen?

> - No class may **part**icipate in more than one composition (including inherited ones) if at least one of those compositions has a 1 at the other (diamond shaped) end.

Das bereits würde ja 2a) und 2b) syntaktisch verhindern.

Oder geht es gerade darum, dass es sowohl 2a) als auch 2b) als auch den schlimmeren Fall mit beide Multiplizitäten genau 1 ausschließt, obwohl 2b) vielleicht doch gar nicht ausgeschlossen werden sollte?

**Comment by marcellussiegburg** [comment]
Ich bin auf diese Fälle bei der Umsetzung gestoßen und habe mich gefragt, wie damit umgegangen werden sollte. Letztlich ist es wohl legitim, pauschal einfach mehr Fälle auszuschließen, als die, die wir als streitbar (oder falsch) ansehen. Mir waren diese konkreten Fälle vorher nur nicht bewusst, daher habe ich sie festgehalten, um zu klären, was damit passieren sollte.
Ich werde diese Fälle alle entsprechend dem Plan ausschließen.
