### ISSUE TITLE
"Spezifizitätsrelation" zwischen Antwortoptionen bei NameCdError-Aufgaben

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#219]
Bei Aufgabeninstanz https://autotool.fmi.uni-due.de/route/aufgabe/354 hatten per PINGO zwar über die Hälfte der Studierenden als spezifischsten Grund wie intendiert `e) Kompositionszyklus` ausgewählt, aber doch relativ dicht gefolgt von `b) Selbstbeziehung, die keine Vererbung ist`.

Es ergab sich dann noch eine kurze Diskussion mit einem Studierenden, der sehr darauf beharrte, es könne nicht gesagt werden, dass in der Situation 

<img width="67" alt="image" src="https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/083bfefe-c72e-46cd-9551-18910356a04b">

"Kompositionszyklus" spezifischer ist als "Selbstbeziehung".

Und irgendwie muss(te) ich ihm da Recht geben. Sowohl "Kompositionszyklus" als auch "Selbstbeziehung" sind spezifischer als ein Konzept "Beziehungszyklus", aber zwischen den beiden gibt es keine allgemeinere und spezifischere Variante. Sie sind eigentlich unvergleichbar. (Und zwar meint in unserem Generator/Formalisierung wohl "Selbstbeziehung" etwas ohne Vermittlung durch Vererbungen, aber das ist nach außen ja nicht sichtbar und kann legitim auch anders interpretiert werden.)

Am einfachsten zu adressieren wäre das Problem wahrscheinlich, indem einfach nie (bzw. nie in relevanter Weise) diese beiden Optionen zusammen angeboten werden. Also in etwa wie folgt:
- `checkNameCdErrorInstance` verhindert gleichzeitiges Auftreten von `CompositionCycles` und `SelfRelationships` (zumindest dann wenn eines der beiden auch als die intendierte Antwort markiert ist)
- `nameCdErrorGenerate` packt niemals beide Gründe in die `errorReasons` (bzw. packt `SelfRelationships` nicht auch dazu wenn `CompositionCycles` als richtige Antwort gedacht ist)
- eventuell muss `checkNameCdErrorConfig` noch irgendwelche Vorkehrungen treffen, damit `nameCdErrorGenerate` das immer schaffen kann (könnte ja etwa wegen gewünschter Anzahl an Auswahlmöglichkeiten problematisch werden)

Neben `CompositionCycles`/`SelfRelationships` gibt es wohl noch weitere Paarungen, die aktuell auftreten könnten, aber das gleiche Problem hervorrufen können. Mindestens `CompositionCycles`/`ReverseRelationships`.

*More fancy:* Statt bei der Generierung direkt immer das gleichzeitige Auftreten des potentiellen "Alternativgrunds" zu verbieten, könnte prinzipiell auch feingliedriger vorgegangen werden. Also etwa wenn sich aus dem Rest der Aufgabenkonfiguration ergibt, dass auf jeden Fall ein Kompositionszyklus der Form

<img width="124" alt="image" src="https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/f6e4f5ec-0f5a-429d-9550-65ade82e298b">

vorkommen wird, dann wäre es okay, neben `CompositionCycles` auch `SelfRelationships` (aber nicht `ReverseRelationships`) anzubieten, da Auswahl von `SelfRelationships` ja unabhängig von der Frage der Spezifizität nicht zutreffend wäre.

**Comment by marcellussiegburg** [comment]
Die Entscheidungen zu #215 haben auch mit diesem Issue zu tun, denn wenn in der Vorlesung Fall 1,2 oder 3 als (eindeutig) ungültig angesehen werden, so könnte auch die `DoubleRelationship` als mögliche Fehlerursache gesehen werden, wenn entsprechende Kompositionen durch Vererbungen weitergereicht werden. Diese Fälle sollten dann auch explizit bei der Generierung verhindert werden.

**Comment by marcellussiegburg** [comment]
Im Prinzip kann eine Selbstbeziehung auch als eine Doppelbeziehung interpretiert werden. Selbst wenn das so ist, würde ich sagen, dass die Selbstbeziehung spezifischer ist.
![Selbstkomposition durch Vererbung](https://github.com/user-attachments/assets/33a9d2d5-88c5-47bc-a6d2-797e4eca001c)
Wenn das so interpretiert werden kann, hätte das aber auch zur Konsequenz, dass wenn `SelfRelationship` (durch Vererbung) ausgeschlossen werden soll, auch `DoubleRelationship` (durch Vererbung) ausgeschlossen werden müsste.

**Comment by marcellussiegburg** [comment]
[Dasselbe würde wohl auch für `ReverseRelationship` gelten. Im konkreten und (relevanten) Fall von Kompositionen ist das wohl doch kein Problem durch die Limitierung auf 1 an der A-Seite (es sei denn, es wird von woanders noch eine Selbst-Komposition her geerbt, aber der Fall lässt sich dann nicht mehr durch Entfernen einer Beziehung beheben, wäre für diesen Aufgabentyp also auch nicht relevant).]

**Comment by marcellussiegburg** [comment]
Ich bin mir nicht sicher, ob dieser Check hier den Aufwand wert ist:
> - checkNameCdErrorInstance verhindert gleichzeitiges Auftreten von CompositionCycles und SelfRelationships (zumindest dann wenn eines der beiden auch als die intendierte Antwort markiert ist)

In den meisten Fällen werden unsere Instanzen wahrscheinlich generiert. Manuelle Instanzen werden wohl auch aus generierten übernommen und dann angepasst. Die Gründe, warum dieser Check problematisch ist, lauten:
1. Der Aufgabentyp hier speichert den Aufgabentext in der Aufgabeninstanz. Die Idee dahinter ist mehr Flexibilität, der Nachteil ist jedoch, dass die angebotenen Optionen nicht eindeutig identifiziert werden können, falls Anpassungen vorgenommen werden. Wenn die intendierten Antworten geprüft werden sollen, dann müssten die Texte in der Instanz abgeglichen werden, hier kann natürlich einfach ein Abgleich mit der angebotenen Default-Übersetzung erfolgen (aber jede Abweichung – selbst von Formatierungen; oder nach Anpassungen der Übersetzung – würde nicht berücksichtigt werden).
2. Es existiert keine Infrastruktur, um den semantischen Check des Klassendiagramms durchzuführen. D.h. es müssten entweder Checker geschrieben werden, (die essenziell das überprüfen, was der Generator via Alloy bei generierten Instanzen sichergestellt hat); oder es müsste auch Alloy verwendet werden, um die Instanz zu prüfen. Für letzteres wäre aber eine Anpassung (wenigstens eine Ausnahme für diesen Aufgabentyp) der Infrastruktur notwendig, sodass IO im Checker überhaupt verwendet werden kann.

Ich sehe beides nicht als eine unüberwindbare Barriere, allerdings stellt sich mir die Frage, ob der Aufwand gerechtfertigt wäre.

**Comment by jvoigtlaender** [comment]
> Die Entscheidungen zu #215 haben auch mit diesem Issue zu tun, denn wenn in der Vorlesung Fall 1,2 oder 3 als (eindeutig) ungültig angesehen werden, so könnte auch die `DoubleRelationship` als mögliche Fehlerursache gesehen werden, wenn entsprechende Kompositionen durch Vererbungen weitergereicht werden. Diese Fälle sollten dann auch explizit bei der Generierung verhindert werden.

Das wäre jetzt obsolet, weil 1. und 2. Fall (sowie auch 4. und 5. Fall) einfach nie überhaupt vorkommen würden, weder in korrekten noch in inkorrekten Diagrammen, richtig?

**Comment by jvoigtlaender** [comment]
> Im Prinzip kann eine Selbstbeziehung auch als eine Doppelbeziehung interpretiert werden.

Das verstehe ich nicht, auch nicht anhand des gemalten Beispiels. Gemäß https://github.com/jvoigtlaender/modelling-tasks-internal/blob/8f1854af84cac992a00eeeb6b0d99dfaefeaa2d6/src/Modelling/CdOd/NameCdError.hs#L887-L921 beziehen sich `DoubleRelationships` und `ReverseRelationships` immer auf "Nicht-Vererbungsbeziehungen".

**Comment by jvoigtlaender** [comment]
An dem gemalten Beispiel frage ich mich allerdings gerade, ob alle Studierenden die Verbalisierung https://github.com/jvoigtlaender/modelling-tasks-internal/blob/8f1854af84cac992a00eeeb6b0d99dfaefeaa2d6/src/Modelling/CdOd/NameCdError.hs#L925-L927 korrekt interpretieren würden. Die Komposition da ist ja eine relevante Selbstbeziehung (richtig?), aber Studierenden könnte der subtile Unterschied zwischen "Selbstbeziehung, die keine Vererbung ist" (oben zutreffend) und "Selbstbeziehung, die nicht durch Vererbung entsteht" (oben nicht zutreffend) entgehen. (Also sie könnten meinen, der Fehlergrund `SelfRelationships` läge hier nicht vor, da ja doch eine Vererbung im Spiel ist?)

**Comment by jvoigtlaender** [comment]
Bzgl. dieses Punktes hier:
> 1. Der Aufgabentyp hier speichert den Aufgabentext in der Aufgabeninstanz. Die Idee dahinter ist mehr Flexibilität, der Nachteil ist jedoch, dass die angebotenen Optionen nicht eindeutig identifiziert werden können, falls Anpassungen vorgenommen werden. Wenn die intendierten Antworten geprüft werden sollen, dann müssten die Texte in der Instanz abgeglichen werden, hier kann natürlich einfach ein Abgleich mit der angebotenen Default-Übersetzung erfolgen (aber jede Abweichung – selbst von Formatierungen; oder nach Anpassungen der Übersetzung – würde nicht berücksichtigt werden).

wäre es nicht sowieso besser (völlig unabhängig von diesem Issue hier), in https://github.com/jvoigtlaender/modelling-tasks-internal/blob/8f1854af84cac992a00eeeb6b0d99dfaefeaa2d6/src/Modelling/CdOd/NameCdError.hs#L394 statt des `Map Language String` jeweils `Reason` zu haben? Gemäß https://github.com/jvoigtlaender/modelling-tasks-internal/blob/8f1854af84cac992a00eeeb6b0d99dfaefeaa2d6/src/Modelling/CdOd/NameCdError.hs#L195-L196 würde man dadurch ja nichts an Flexibilität einbüßen, aber allgemein hätte man mehr Information in der Instanz (etwa für diesen Fall hier, aber potentiell auch andere Zwecke) wenn doch der `PreDefined`-Konstruktor von `Reason` vorliegt.

**Comment by marcellussiegburg** [comment]
Ja, das stimmt, ein Beispiel mit DoubleRelationships vs. selbstBeziehung wäre
![image](https://github.com/user-attachments/assets/ce3d90fc-7271-4a65-afac-c1bf80dd6f56)
[(Bzw. schon auch ohne die Verbung zwischen A und B), aber diese Situation würde jetzt schon durch die Entscheidungen zu #215 nicht mehr auftreten]

**Comment by jvoigtlaender** [comment]
Den 2. Punkt oben verstehe ich überhaupt nicht. Inwiefern müsste für die erwähnte Überprüfung einer `NameCdErrorInstance` denn ein semantischer Check (mittels Alloy oder anderweitig) gemacht werden? Es wäre doch nur zu überprüfen, ob etwa jemand `CompositionCycles` als den intendierten Fehlergrund in eine Instanz geschrieben hat, aber gleichzeitig auch `SelfRelationships` als Option aufführt.

**Comment by jvoigtlaender** [comment]
Ich bin mir nicht sicher, worauf sich
> Ja, das stimmt, 

bezieht (https://github.com/jvoigtlaender/modelling-tasks-internal/issues/219#issuecomment-2333840778 oder https://github.com/jvoigtlaender/modelling-tasks-internal/issues/219#issuecomment-2333851186), aber in 
![image](https://github.com/user-attachments/assets/4f6faa76-f45c-42bd-9c9d-83d2f52298dc)
sehe ich eigentlich gar keine Selbstbeziehung.

**Comment by marcellussiegburg** [comment]
> Den 2. Punkt oben verstehe ich überhaupt nicht. Inwiefern müsste für die erwähnte Überprüfung einer NameCdErrorInstance denn ein semantischer Check (mittels Alloy oder anderweitig) gemacht werden? Es wäre doch nur zu überprüfen, ob etwa jemand CompositionCycles als den intendierten Fehlergrund in eine Instanz geschrieben hat, aber gleichzeitig auch SelfRelationships als Option aufführt.

Weil beide Gründe durch https://github.com/jvoigtlaender/modelling-tasks-internal/commit/8f1854af84cac992a00eeeb6b0d99dfaefeaa2d6#diff-c845e9c8311bcce3b7be852cc8eb9ac3fe11ef74a6141bf70c0d2d72e3cffdedR151-R159 in generierten Instanzen auftauchen dürfen, wobei sichergestellt wird, dass es eindeutig bleibt. Dieses Kriterium müsste hier dann auch überprüft werden.

**Comment by jvoigtlaender** [comment]
Ah okay, also es wurde vom ersten Kommentar hier in dem Issue etwas wie das "More fancy" umgesetzt, insbesondere wird in `nameCdErrorGenerate` gar nicht wie darüber insinuiert generell verhindert, dass bei echtem Fehlergrund `CompositionCycles` auch noch `SelfRelationships` angeboten wird. Sondern nur wenn das problematisch wäre. Und dieses "problematisch" auch noch nach der Generierung zu erkennen, ist selbst problematisch. Macht Sinn.

**Comment by marcellussiegburg** [comment]
> Die Komposition da ist ja eine relevante Selbstbeziehung (richtig?)

Nein, die Komposition ist keine relevante Selbstbeziehung im Sinne der aktuellen Alloy-Modellierung. Mein Verdacht war, dass es aber so interpretiert werden könnte. Der Fehlergrund in diesem Beispiel wäre Kompositionszyklus. Selbstbeziehungen sind generell kein Fehlergrund, abgesehen von Selbstvererbungen.

Letztlich ist die Relevanz aber nicht gegeben:
- ein Fehlergrund (im Sinne der Alloy-Modellierung) existiert nur, wenn es sich um Kompositionen handelt (d. h. ein Kompositionszyklus); diese Situation wird nun jedoch ausgeschlossen (nach den bisherigen Umsetzungen zu diesem Issue)
- die genannte Situation kann in genau dieser Form gar nicht auftreten, weil ein Constraint das verhindert https://github.com/jvoigtlaender/modelling-tasks-internal/blob/88a2363dab9e805706c29338afc37e8442855a75/alloy/cd/generate.als#L207-L208 (eine ähnliche Situation könnte über eine weitere Indirektion (via Vererbung) auftreten, wäre aber wegen des vorherigen Punktes auch irrelevant)

Ich habe keine weiteren, problematischen Kombinationen gefunden.
