### ISSUE TITLE
printSolution-Option für PetriNet-Reach-Aufgaben

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#220]
... wäre zum Beispiel hier hilfreich gewesen: https://autotool.fmi.uni-due.de/route/einsendung/398/726 (vor allem wenn die Studierende ansonsten nachfragt, was denn eine mögliche Lösung gewesen wäre).

**Comment by marcellussiegburg** [comment]
duplicate to #181
