### ISSUE TITLE
diverse Typ- und Feldnamen in "Eingabesyntax" (z.B. `actionNames` vs. `objectNodeNames`)

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#222]
Es ist aus Studierendensicht bei der Eingabe wahrscheinlich merkwürdig, dass in https://github.com/jvoigtlaender/modelling-tasks-internal/blob/e34f81a1e351d35e79d4dcc71d681ac3642196e6/src/Modelling/ActivityDiagram/MatchAD.hs#L124-L133 alle außer das erste Feld ein `Node` enthalten. Also warum es nicht auch `actionNodeNames` heißt.

Andererseits wird in den Folien aktuell tatsächlich von "Aktionen" und "Objektknoten" gesprochen, nicht von "Aktionsknoten" und "Objektknoten". Der Zug, es dabei zu belassen, ist mit https://github.com/jvoigtlaender/modelling-tasks-internal/issues/202 in gewissem Sinne abgefahren. Also vielleicht sollte auch in Folien und anderen Materialien weitgehend zu "Aktionsknoten" übergegangen werden.

**Comment by jvoigtlaender** [comment]
Nach nochmaligem Gegen-Checken mit dem Lehrveranstaltungsmaterial, folgende Umbenennungsvorschläge (rein für die Felder des obigen Daten- und somit auch Eingabetyps):
- `actionNames` -> `actionNodeNames`
- `numberOfForkNodes` -> `numberOfForks`
- `numberOfJoinNodes` -> `numberOfJoins`

In der Tat sehen die Gabelungen und Vereinigungen ja weniger wie Knoten aus (und im erklärenden Text steht wohl auch bewusst "Anzahl jeder anderen Art von Komponente" statt "Anzahl jeder anderen Art von Knoten"; den Folien folgend wäre der passendste Begriff eigentlich "Element").

**Comment by jvoigtlaender** [comment]
Die `numberOf...`-Felder sollten wahrscheinlich zu `countOf...` umbenannt werden, dem englischen Aufgabentext folgend, der jetzt auch von "the count of each other kind of element" spricht.

**Comment by jvoigtlaender** [comment]
Auch in https://github.com/jvoigtlaender/modelling-tasks-internal/blob/88182aa38434bcfbfa457c22120bcb8bc3a5c737/src/Modelling/ActivityDiagram/FindSupportST.hs#L154-L158 wäre dann Verwendung von `countOf...` sinnvoller.

**Comment by jvoigtlaender** [comment]
Sowohl in https://github.com/jvoigtlaender/modelling-tasks-internal/blob/88182aa38434bcfbfa457c22120bcb8bc3a5c737/src/Modelling/ActivityDiagram/FindSupportST.hs#L154 als auch in https://github.com/jvoigtlaender/modelling-tasks-internal/blob/88182aa38434bcfbfa457c22120bcb8bc3a5c737/src/Modelling/ActivityDiagram/MatchPetri.hs#L226-L234 sind (wenn diese Typen als Eingabesyntax verwendet werden) die Vorkommen von `ST` merkwürdig. Diese beiden Initialen standen wohl mal als Abkürzung für "Stellen" und "Transitionen". Aber da die Feldbezeichner ansonsten alle englisch sind, wären eher "Places" und "Transitions" naheliegend, also `PT`.

**Comment by jvoigtlaender** [comment]
In `MatchPetriSolution` wären außerdem andere Umbenennungen in Analogie zu `MatchADSolution` sinnvoll, mindestens:
- `forkNodes` -> `forks`
- `joinNodes` -> `joins`

**Comment by jvoigtlaender** [comment]
Auch: überall "support" -> "auxiliary", um den Begriffen aus Vorlesung/Übung (und ggfs. Übersetzungsdokumenten) treu zu sein.

**Comment by jvoigtlaender** [comment]
Eventuell wäre statt `supportSTs` -> `auxiliaryPTs` auch -> `auxiliaryNodes` sinnvoll. Und entsprechend `FindSupportSTSolution` -> `FindAuxiliaryNodesSolution`.

**Comment by marcellussiegburg** [comment]
Wegen #248 wurde `ST` zu `PetriNode` umbenannt. Ich würde das hier beibehalten und z.B. entsprechend noch spezifischer `FindSupportSTSolution` -> `FindAuxiliaryPetriNodesSolution` umbenennen, wenn es keine Einwände gibt.
