### ISSUE TITLE
"Verzweigungsbedingungen" bei AD-Aufgaben

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#224]
Die scheinen immer überall hinzugefügt zu werden, wohl immer einfach als `[X]` und `[Y]`:

![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/4822167f-9dfc-48e9-8bdc-e895e290a256)

Vielleicht sollte man die optional "ausschalten" können?

Zum einen werden sie ja bisher einfach nicht genutzt, also die Aufgaben nehmen inhaltlich keinen Bezug auf diese Bedingungen (anders als entsprechende schriftliche Übungsaufgaben).

Zum anderen könnten sie sogar "schädlich" sein, wenn Studierende da zuviel Semantik reininterpretieren. In dem konkreten Beispiel könnte man etwa auf den Gedanken kommen, dass `[X]` entweder gilt oder nicht gilt, und sich das auch nicht ändern kann (weil nichts zu irgendwelchen auslösenden Bedingungen für eine Änderung gesagt wird). Dann könnte man meinen, dass jede komplette Aktionsfolge nur genau ein `I` enthalten darf. Mit dem Argument, dass man entweder mit `[X]` durchmarschiert, oder `[X]` eben nicht gilt, man deshalb sich immer im Kreis dreht und deshalb der Ablauf nicht endet.

Oder seien zufällig an beim zweiten Verzweigungsknoten `[X]` und `[Y]` vertauscht. Dann könnte eine Interpretation sein, dass wenn gerade `[X]` galt, und darauf sofort ein weiterer Verzweigungsknoten kommt, dort immer noch `[X]` gelten muss und daher der Weg nach unten nicht frei ist. Etc.

Wir haben einfach keine Semantik für diese Bedingungen, aber das hält Studierende vielleicht nicht unbedingt von solchen vom Wesentlichen ablenkenden Interpretationen ab. Durch Verstecken der Bedingungen ließe sich das vermeiden.

**Comment by jvoigtlaender** [comment]
Ein anderes Beispiel, wo Abhängigkeiten vermutet werden könnten ("Wenn `E` genommen wurde, dann muss danach nochmal die gesamte Schleife kommen. Erst wenn `A` genommen wurde, geht es nach unten raus in Richtung `D`."), ist sowas:

![2cd443469f432530a6cf5a0b](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/1c0a6794-9823-4b57-8254-714eb2aaaaf2)

**Comment by marcellussiegburg** [comment]
Dann sollte die Option vielleicht bei jeder Aufgabe vorhanden sein. Bei `MatchAD` existiert eine solche Option bereits (z.B. ist sie hier aktiv: https://autotool.fmi.uni-due.de/route/aufgabe/407#konfiguration).
