### ISSUE TITLE
Subtilität zu "in das Terminieren aller Abläufe des Diagramms resultierende Aktionsfolge"

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#238]
Siehe https://autotool.fmi.uni-due.de/route/einsendung/418/936

Es könnte in der Tat argumentiert werden, dass die Aufgabenstellung hier nicht präzise genug ist, bzw. aus gewisser Perspektive etwas Unmögliches verlangt.

Denn hier ist es in der Tat so, dass welche Folge auch immer man angibt, es nicht so ist, dass *alle* Abläufe damit terminieren. Es gibt immer auch noch eine Möglichkeit, nach der gewählten Folge weiterzumachen.

Eventuell ist das durch irgendwelche Forderungen an das Diagramm vermeidbar. (Es würde reichen, vor dem äußeren Endknoten immer noch einen Aktionsknoten zu haben, von dem aus es nur zum Ende geht, nicht nochmal nach weiter oben.)

Eventuell ist aber auch einfach eine bessere Aufgabenformulierung zu finden. Das Problem scheint das "alle Abläufe" zu sein. Es klingt so wie eine Quantifizierung über alle realisierbaren Ausführungen. Gemeint ist aber eher "alle Unterabläufe einer bestimmten Ausführung". Also einfach "alle Flüsse" statt "alle Abläufe"?

**Comment by marcellussiegburg** [comment]
Ich denke nicht, dass es vorteilhafter ist, zu fordern, dass immer ein Aktionsknoten am Ende steht. Daher bin ich für die Lösung mit der Umformulierung.
> Also einfach "alle Flüsse" statt "alle Abläufe"?

Ja, das sollte meiner Meinung nach auch reichen.
