### ISSUE TITLE
potentiell Doppelkanten bei CD-Generierung

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#239]
Hierzu:

>  Der Generator würde soetwas (wenn ich mich nicht irre) derzeit nicht generieren, weil momentan keine identische Kanten zweimal vorkommen können, falls das wirklich so ist, sollte das vermutlich (wenigstens für Vererbungen) geliftet werden (damit auch wirklich Doppelvererbungen generiert werden können und nicht nur in händischen Instanzen existieren).

könnte ein separates Issue angelegt werden. Im Fall von Vererbungen spielt dann ja auch noch das Feature "Multiple inheritance erlaubt oder nicht" hinein.

Und ja, vielleicht ergeben sich dort dann noch weitere Umformulierungsnotwendigkeiten (nachdem die hiesigen erstmal adressiert sind).

_Originally posted by @jvoigtlaender in https://github.com/jvoigtlaender/modelling-tasks-internal/issues/210#issuecomment-1931786827_

**Comment by marcellussiegburg** [comment]
Ich habe mir diesen Punkt noch einmal genauer angeschaut. Meine Ergebnisse:
- Der Generator kann Doppelkanten generieren (die Wahrscheinlichkeit dafür ist sehr gering).

  Aufgrund dessen wie der Generierungsprozess gestrickt ist, dürfte dadurch eine in dadurch hervorgerufene Fehlformulierung momentan nicht auftreten. (Grund: die Doppelkante ist eine erlaubte Eigenschaft, die explizit erlaubt werden muss, und tritt somit erst in einem veränderten Klassendiagramm, also nach Anwendung einer Änderung auf)
- Doppelte Vererbungskanten können nicht auftauchen. Hier ist wohl die Frage, ob wir das prinzipiell wollen. Wenn ja, dann entstehen wohl noch mehr Fragen, mindestens: Wie soll das ursprünglich auftreten und behoben werden (im Kontext der momentanen Umsetzung mittels **einer** ungültigen Eigenschaft)?

**Comment by jvoigtlaender** [comment]
> Der Generator kann Doppelkanten generieren

Was genau wird denn in diesem Kontext unter einer Doppelkante verstanden? 

Sind zum Beispiel
> zwei Assoziationen `x` und `y` mit gleicher Richtung und jeweils den gleichen Multiplizitäten an den Enden

ein Fall von "Doppelkante"?

**Comment by marcellussiegburg** [comment]
Ja, das wäre ein solcher Fall, wenn Beziehungstyp, Herkunft, Ziel und Multiplizitäten übereinstimmen (und das sollte momentan auch der einzige sein, weil die Namen beim Parsen eindeutig vergeben werden und kein Name mehrfach vergeben wird).

*Dass das die einzigen sind, gilt nur im Kontext der problematischen Formulierungen. Als Doppelkanten werden ansonsten bereits aufgefasst, wenn Herkunft und Ziel identisch sind.*

*Edit: Ergänzung*

**Comment by marcellussiegburg** [comment]
Ich muss meine Aussage noch etwas weiter einschränken. Meine Analyse bezog sich auf `RepairCd` und `SelectValidCd`. Auf `NameCdError` trifft das nicht zu, dort wird die legale Eigenschaft schon von Anfang an mit der illegalen verbunden. Hier kann es also zu einer irreführenden Formulierung kommen.

**Comment by jvoigtlaender** [comment]
Okay, zerlegen wir das Problem in Unterprobleme, bzw. klären erstmal die Situation bzgl. Vererbungen:

Doppelvererbungen werden bisher nie erzeugt, richtig? Ändern wir das nicht, zumal sowieso der Status von multiple inheritance in UML vs. in der Vorlesung etwas schwammig ist. Bzw., ich nehme dazu in der Vorlesung keine wirkliche Stellung, aber multiple inheritance kommt einfach in Aufgaben nie vor.

Ergo darf auf Vererbung immer mit DefiniteArticle Bezug genommen werden. Aber IndefiniteArticle ist auch nicht schlimm.

**Comment by jvoigtlaender** [comment]
Das Argument, bzgl. `RepairCd` und `SelectValidCd`, ist irgendwie dass nur in veränderten Klassendiagrammen Kanten mit gleichem Ursprung und gleichem Ziel vorkommen. Ich verstehe noch nicht, warum daraus folgt, dass Bezugnahme mit DefiniteArticle immer safe ist. Weil man nie auf Kanten in den veränderten Klassendiagrammen Bezug nimmt? Auch nicht im neuen "clever Feedback" für `RepairCd` und `SelectValidCd`?

**Comment by marcellussiegburg** [comment]
Im "clever Feedback" von `RepairCd` tauchen solche Formulierungen nicht auf. Trickreicher ist es bei `SelectValidCd`, da hier Änderungen auftreten können, aber diese betreffen immer einen Fehler im Klassendiagramm, der das Klassendiagramm ungültig macht. D.h., wenn eine Beziehung irgendwo hinzugefügt würde, die identisch zu einer vorhanden ist, würde sie nicht referenziert werden, weil sie den eigentlichen Fehler nicht beheben würde. Der Fall, in dem das meines Erachtens am ehesten auftreten könnte, wäre ein Kompositionszyklus. Wenn aber eine Komposition zusätzlich parallel zu einer vorhanden Komposition eingefügt würde, würde das Entfernen einer dieser beiden den Zyklus nicht beheben und daher eine andere Änderung präsentiert werden.

**Comment by jvoigtlaender** [comment]
Okay. Ich hatte an einen anderen Fall gedacht, wo tatsächlich eine der beiden Kanten "aus dem Doppelpack" das Problem ist bzw. ihr Entfernen das Problem beheben würde:
> Was ist wenn es zwei Kompositionen sind, was ja ein zu findender Fehler wäre, und diese beiden Kompositionen sehen bis auf den Namen exakt gleich aus? Dann würde "entferne die Komposition" nicht so viel Sinn machen wie "entferne eine Komposition", weil "die Komposition" nicht klar ist

aus https://github.com/jvoigtlaender/modelling-tasks-internal/pull/210#issuecomment-1931803558.

Aber so ein Fehler wird durch den Generator gar nicht eingeführt bzw. "als Fehler gesehen". Das hat dann wohl auch mit #215 zu tun: auf solche Konstellationen wird gefiltert, um "weniger ansonsten korrekte Kandidaten" anzuzeigen, nicht um "weitere inkorrekte Kandidaten" zu erhalten.

Mit diesem Wissen kann dieses Issue hier denke ich geschlossen werden, und für #240 mache ich dort einen Vorschlag.
