### ISSUE TITLE
ggfs. Analyse zu verwendender Artikel

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#240]
Übrigens selbst wenn im Moment nie zwei identische Beziehungen generiert werden, heißt das nicht, dass eine Bezugnahme mit bestimmtem Artikel immer reicht. Denn zwei Assoziationen/Aggregationen/Kompositionen `x` und `y` mit gleicher Richtung und jeweils den gleichen Multiplizitäten an den Enden sind in dem Sinne nicht identisch, könnten also zusammen auftretend generiert werden. Wenn aber auf sie ohne Namen Bezug genommen wird, heißt es dann doch jeweils "Beziehung zwischen ... und ... mit Beteiligung so-und-so", und die Formulierung ist für beide gleich, ergo potentiell Ungewissheit vorhanden, welche jeweils gemeint ist.

Kann sein, dass der Aspekt "Distanz maximal 1" das ausgleicht (in generierten Aufgaben), aber vielleicht nichtmal das? Was ist wenn es zwei Kompositionen sind, was ja ein zu findender Fehler wäre, und diese beiden Kompositionen sehen bis auf den Namen exakt gleich aus? Dann würde "entferne die Komposition" nicht so viel Sinn machen wie "entferne eine Komposition", weil "die Komposition" nicht klar ist (und auch "wenn es keine Komposition gäbe" über das Ziel hinausginge, weil tatsächlich Entfernung von einer der beiden Kompositionen reichen würde).

_Originally posted by @jvoigtlaender in https://github.com/jvoigtlaender/modelling-tasks-internal/issues/210#issuecomment-1931803558_

**Comment by jvoigtlaender** [comment]
Auch in Kommentaren dort:
> Falls es genau bei den ursprünglich intendierten bleibt, wäre wohl auch denkbar, per Analyse zu überprüfen, ob es eine Dopplung gibt und danach den Artikel (ggf. im speziellen Fall) zu wählen.

**Comment by jvoigtlaender** [comment]
Sowie:
> (Eventuell lassen sich teilweise auch die Config-Checker heranziehen. Zum Beispiel dürfte `Definite` immer okay sein, wenn die Bezugnahme sowieso per Namen passiert, aber wenn Bezugnahme ohne Namen eingestellt wird, und gleichzeitig bestimmte Fehlermöglichkeiten aktiv geschaltet sind, könnte auf Verwendung von `Indefinite` bestanden werden. Diese Checker-Strategie könnte auch noch überarbeitet werden, wenn bei konkreten Aufgaben in Zukunft noch Mehrdeutigkeiten zutage treten.)

**Comment by jvoigtlaender** [comment]
Also das sind zwei verschiedene mögliche Herangehensweisen (Kombination wäre auch denkbar):
- Per Config-Checker werden Fälle identifiziert, in denen der eine oder andere Artikel sicher/unsicher für alle aus der konkreten Konfiguration erzeugbaren Instanzen ist.
- Bei der Generierung der Instanzen werden diese konkret daraufhin analysiert, ob in ihnen Dopplungen vorkommen, und dann Artikel geeignet gesetzt.

**Comment by marcellussiegburg** [comment]
Dies ist relevant für `NameCdError` (siehe https://github.com/jvoigtlaender/modelling-tasks-internal/issues/239#issuecomment-1953898878).

**Comment by jvoigtlaender** [comment]
Vorschlag:

In `NameCdErrorConfig`, `RepairCdConfig` und `SelectValidCdConfig` wird jeweils statt `articleToUse = DefiniteArticle | IndefiniteArticle` eine leicht andere Unterscheidung eingestellt, von der Art: `UseDefiniteArticleWherePossible | UseIndefiniteArticleEverywhere` (aber in den Instanz-Typen bleibt es bei Verwendung konkret von `DefiniteArticle` und `IndefiniteArticle`).

Wurde in einer Konfiguration `UseIndefiniteArticleEverywhere` gewählt, wird das so behandelt wie wenn aktuell `IndefiniteArticle` gewählt wurde.

Wurde in einer Konfiguration `UseDefiniteArticleWherePossible` gewählt, dann:
- wird bei generierten Vererbungen `DefiniteArticle` benutzt,
- wird bei generierten anderen Beziehungen in `RepairCd`- und `SelectValidCd`-Aufgaben `DefiniteArticle` benutzt,
- wird bei generierten anderen Beziehungen in `NameCdError`-Aufgaben, wenn `useNames == True` gesetzt wurde, `DefiniteArticle` benutzt (was konkret im Moment wahrscheinlich keine Auswirkungen hat, da bei Verwendung von Namen überhaupt kein Artikel geschrieben wird),
- wird bei generierten anderen Beziehungen in `NameCdError`-Aufgaben, wenn `useNames == False` gesetzt wurde, vorerst `IndefiniteArticle` benutzt (bis vielleicht irgendwann eine Analyse überlegt wird, gemäß derer an einigen Stellen gesichert auch `DefiniteArticle` passend ist).

Interessant wäre noch, eine konkrete `NameCdError`-Instanz festzuhalten, die generiert werden könnte und bei der die Vorsicht aus dem letzten Fall oben wirklich nötig ist.

**Comment by jvoigtlaender** [comment]
Der erste und zweite Punkt obiger Aufzählung bedeuten letztlich (wenig überraschend angesichts deiner vorherigen Analyse, auf der der Vorschlag ja beruht), dass es für `RepairCd`- und `SelectValidCd`-Aufgaben bei der bisherigen Konfigurationsoption `articleToUse = DefiniteArticle | IndefiniteArticle` und dem bisherigen Verhalten bleiben kann.

**Comment by jvoigtlaender** [comment]
Allerdings wäre eventuell auch für `RepairCd` und `SelectValidCd` die Verwendung von `DefiniteArticleWherePossible | IndefiniteArticleEverywhere` im Konfigurationstyp doch klarer, da ja etwa `DefiniteArticle` sonst suggerieren könnte, dass überall der bestimmte Artikel benutzt wird, was ja aber nicht stimmt bezüglich der Phrasierung von Ersetzungen, weil da für die neu eingeführte Beziehung trotzdem immer der unbestimmte Artikel genommen wird.

**Comment by marcellussiegburg** [comment]
Dieser Teil
> (bis vielleicht irgendwann eine Analyse überlegt wird, gemäß derer an einigen Stellen gesichert auch DefiniteArticle passend ist)

ist noch ausstehend.

**Comment by jvoigtlaender** [comment]
Das umfasst wohl auch noch, bzw. setzt zur Motivation vielleicht voraus:
> Interessant wäre noch, eine konkrete `NameCdError`-Instanz festzuhalten, die generiert werden könnte und bei der die Vorsicht aus dem letzten Fall oben wirklich nötig ist.

(also ein Beispiel, warum man nicht einfach auch bei generierten Assoziationen/Aggregationen/Kompositionen in `NameCdError`-Aufgaben mit `useNames == False` den `DefiniteArticle` benutzen kann)

**Comment by marcellussiegburg** [comment]
Mit folgender Konfiguration:
```haskell
config = NameCdErrorConfig {
  allowedProperties = AllowedProperties {
    compositionCycles = False,
    doubleRelationships = True,
    inheritanceCycles = False,
    reverseInheritances = False,
    reverseRelationships = False,
    selfInheritances = False,
    selfRelationships = False,
    wrongAssociationLimits = True,
    wrongCompositionLimits = False
    },
  articleToUse = UseDefiniteArticleWherePossible,
  classConfig = ClassConfig {
    classLimits = (3, 3),
    aggregationLimits = (0, Just 0),
    associationLimits = (2, Just 3),
    compositionLimits = (0, Just 0),
    inheritanceLimits = (0, Just 0),
    relationshipLimits = (2, Just 3)
    },
  maxInstances = Just 1000,
  objectProperties = ObjectProperties {
    completelyInhabited = Just True,
    hasLimitedIsolatedObjects = True,
    hasSelfLoops = Nothing,
    usesEveryRelationshipName = Just True
    },
  possibleReasons = [
    PreDefined CompositionCycles,
    PreDefined DoubleRelationships,
    PreDefined InheritanceCycles,
    PreDefined MultipleInheritances,
    PreDefined ReverseInheritances,
    PreDefined ReverseRelationships,
    PreDefined SelfInheritances,
    PreDefined SelfRelationships,
    PreDefined WrongAssociationLimits,
    PreDefined WrongCompositionLimits
    ],
  printNames = True,
  printNavigations = True,
  printSolution = False,
  reasonsPerInstance = NumberOfReasons {
    customReasons = 0,
    preDefinedInvalid = 6,
    preDefinedValid = 4
    },
  timeout = Nothing,
  useNames = False
  }
```
kann momentan mit dem Aufruf `nameCdErrorGenerate config 0 66` folgende Instanz erzeugt werden:
``` haskell
NameCdErrorInstance {
  classDiagram = AnnotatedClassDiagram {
  annotatedClasses = ["B", "C", "A"],
  annotatedRelationships = [
    Annotation {
      annotated = Association {
        associationName = "y",
        associationFrom = LimitedLinking {linking = "B", limits = (2, Just 1)},
        associationTo = LimitedLinking {linking = "A", limits = (0, Just 2)}
        },
      annotation = Relevant {
        contributingToProblem = True,
        listingPriority = 1,
        referenceUsing = IndefiniteArticle
        }
      },
    Annotation {
      annotated = Association {
        associationName = "x",
        associationFrom = LimitedLinking {linking = "B", limits = (0, Nothing)},
        associationTo = LimitedLinking {linking = "A", limits = (1, Just 2)}
        },
      annotation = Relevant {
        contributingToProblem = False,
        listingPriority = 3,
        referenceUsing = IndefiniteArticle
        }
      },
    Annotation {
      annotated = Association {
        associationName = "z",
        associationFrom = LimitedLinking {linking = "B", limits = (0, Just 1)},
        associationTo = LimitedLinking {linking = "A", limits = (2, Just 2)}
        },
      annotation = Relevant {
        contributingToProblem = False,
        listingPriority = 2,
        referenceUsing = IndefiniteArticle
        }
      }
    ]
  },
  errorReasons = fromList [
    ('a', (False, fromList [(English, "contains at least one pair of classes each inheriting from the other."), (German, "enth\228lt mindestens ein Paar von Klassen, ")])),
    ('b', (False, fromList [(English, "contains at least one self-relationship that is no inheritance."), (German, "enth\228lt mindestens eine Selbstbeziehung, ")])),
    ('c', (False, fromList [(English, "contains at least one inheritance cycle."), (German, "enth\228lt mindestens einen Vererbungszyklus.")])),
    ('d', (False, fromList [(English, "contains at least one multiple inheritance."), (German, "enth\228lt mindestens eine Mehrfachvererbung.")])),
    ('e', (False, fromList [(English, "contains at least one self-inheritance."), (German, "enth\228lt mindestens eine Selbstvererbung.")])),
    ('f', (False, fromList [(English, "contains at least one invalid multiplicity near the whole of a composition."), (German, "enth\228lt mindestens eine ung\252ltige Multiplizit\228t am Ganzen einer Komposition.")])),
    ('g', (False, fromList [(English, "contains at least one composition cycle."), (German, "enth\228lt mindestens einen Kompositionszyklus.")])),
    ('h', (False, fromList [(English, "contains at least two non-inheritance relationships between the same two classes pointing in opposite directions."), (German, "enth\228lt mindestens zwei Nicht-Vererbungs-Beziehungen zwischen denselben beiden Klassen, ")])),
    ('i', (False, fromList [(English, "contains at least two non-inheritance relationships between the same two classes each pointing in the same direction."), (German, "enth\228lt mindestens zwei Nicht-Vererbungs-Beziehungen zwischen denselben beiden Klassen, ")])),
    ('j', (True, fromList [(English, "contains at least one invalid multiplicity at some relationship."), (German, "enth\228lt mindestens eine ung\252ltige Multiplizit\228t an einer Beziehung.")]))
    ],
  showSolution = False,
  taskText = [
    Paragraph [Translated (fromList [(English, "Consider the following class diagram, "), (German, "Betrachten Sie folgendes Klassendiagramm, ")])],
    Paragraph [TaskSpecific IncorrectCd],
    Paragraph [Translated (fromList [(English, "It contains the following relationships between classes:"), (German, "Es enth\228lt die folgenden Beziehungen zwischen Klassen:")])],
    Paragraph [TaskSpecific RelationshipsList],
    Paragraph [Translated (fromList [(English, "Choose what you think is the single reason that this class diagram is incorrect, "), (German, "W\228hlen Sie aus, ")])],
    Paragraph [Translated (fromList [(English, "Possible reasons are:"), (German, "M\246gliche Gr\252nde sind:")])],
    Paragraph [Translated (fromList [(English, "The class diagram ..."), (German, "Das Klassendiagramm ...")])],
    Paragraph [TaskSpecific ReasonsList],
    Paragraph [Paragraph [Translated (fromList [(English, "Please state your answer by providing a letter for the reason, "), (German, "Bitte geben Sie Ihre Antwort an, ")])],
    Paragraph [Code "due-to:\n- 3\n- 4\nreason: b\n"],
    Paragraph [Translated (fromList [(English, "would indicate that the class diagram is invalid because of reason b and that the relationships 3 and 4 make the problem appear."), (German, "bedeuten, ")])]]],
  withDirections = True,
  withNames = False
  }
```
Der gerenderte Aufgabentext sieht so aus:
```
It contains the following relationships between classes:
1  an association from B to A where B participates 2..1 times and A participates 0..2 times
2  an association from B to A where B participates 0..1 times and A participates exactly twice
3  an association from B to A where B participates 0..* times and A participates 1..2 times

Choose what you think is the single reason that this class diagram is incorrect, and mention all relationships that definitely contribute to the problem, i.e., removing any of them would fix the problem.
Possible reasons are:
The class diagram ...
a  contains at least one pair of classes each inheriting from the other.
b  contains at least one self-relationship that is no inheritance.
c  contains at least one inheritance cycle.
d  contains at least one multiple inheritance.
e  contains at least one self-inheritance.
f  contains at least one invalid multiplicity near the whole of a composition.
g  contains at least one composition cycle.
h  contains at least two non-inheritance relationships between the same two classes pointing in opposite directions.
i  contains at least two non-inheritance relationships between the same two classes each pointing in the same direction.
j  contains at least one invalid multiplicity at some relationship.
```
In diesem Beispiel sind die Multiplizitäten unterschiedlich, daher ist unterscheidbar, welche Beziehung gemeint ist. Hätten 2 und 3 aber (zufällig) dieselben Multiplizitäten, wäre die Formulierung für diese beiden Beziehungen mit bestimmtem Artikel problematisch.

**Comment by jvoigtlaender** [comment]
Da wäre wahrscheinlich nicht nur die Bezugnahme mit bestimmtem Artikel problematisch, sondern einfach auch schon die Auflistung:
```
2  an association from B to A where B participates 0..1 times and A participates exactly twice
3  an association from B to A where B participates ... exactly as above ...
```
Das wäre als Teil der Aufgabenstellung sehr verwirrend. (Nachfrage von Studierenden: "Welche der Beziehungen im Diagramm ist denn nun `2`, und welche `3`? Kann ich so nicht bearbeiten." - selbst wenn es in Wirklichkeit für die Bearbeitung nicht relevant ist, ob nun so-oder-so-herum gemeint.)

Im Gegensatz zu etwa:
```
2  the association x
3  the association y
```

Also vielleicht ist die angemessene "Reparatur" wie folgt: Wenn `useNames == False`, dann dürfen bei `NameCdError`-Aufgaben keine bis auf den Namen identische Beziehungen erzeugt werden. (Notfalls einfach Verwerfen solcher Instanzen nach einem `Eq`-module-Name-Check.)

Das wäre unabhängig von der Wahl von `articleToUse` der Fall. (Weil es ja eben auch bei Setzen von `UseIndefiniteArticleEverywhere` schon ein ungewünschter Aufgabentext ist.)

**Comment by marcellussiegburg** [comment]
Das heißt letztlich wohl auch, dass in diesem Fall hier:
> - wird bei generierten anderen Beziehungen in NameCdError-Aufgaben, wenn useNames == False gesetzt wurde, vorerst IndefiniteArticle benutzt (bis vielleicht irgendwann eine Analyse überlegt wird, gemäß derer an einigen Stellen gesichert auch DefiniteArticle passend ist).

der bestimmte Artikel verwendet werden kann.

**Comment by jvoigtlaender** [comment]
Ja, das Verbot von "all zu identischen" Beziehungen wäre eine globale Lösung (für ein "anderes Problem"), die eine lokale Analyse (für das "ursprüngliche Problem") gleich mit überflüssig macht.
