### ISSUE TITLE
fine-tuning layout of class diagrams

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#25]
I made https://github.com/jvoigtlaender/alloy-cd-od/commit/214416ffa2c9b32270c362fbf56174b26985472b to not draw the big boxes for classes despite not much content. However, now things get very cramped together in class diagrams, see this example:

[output-2.pdf](https://github.com/jvoigtlaender/alloy-cd-od/files/2950959/output-2.pdf)

Is it possible to make GraphViz space out things a bit more, without making the boxes themselves larger?

**Comment by jvoigtlaender** [comment]
Possibly also relevant for object diagrams (now).

**Comment by marcellussiegburg** [comment]
There seems to be no obvious way to achieve this. My best attempt on this has been reducing the font size.
