### ISSUE TITLE
Feedback-Kritik bei `NameCdError`

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#250]
bei https://autotool.fmi.uni-due.de/route/aufgabe/444/student/688/testen

Tutorin meint:
> finde ich, dass a auch als Grund gelten würde, da die Kompositionen über die Vererbung quasi in entgegengesetzte Richtungen zeigen, könnte schnell falsch verstanden werden

![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/99522bb2-6513-41bd-9649-314d6a7078f2)

![image](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/1a3da049-e88f-4552-9da9-55cb03a2cbe2)

**Comment by jvoigtlaender** [comment]
Hat mit https://github.com/jvoigtlaender/modelling-tasks-internal/issues/219 zu tun?

**Comment by marcellussiegburg** [comment]
Ja, das liegt an #219
