### ISSUE TITLE
Remove redundant configuration option on `DifferentNames`

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#251]
Veranlasst durch Rückfrage einer Tutorin zu einer Instanz:
> hat die Verbindung a keinen Partner, ist das beabsichtigt?

... ja, war so konfiguriert.

Allerdings wurde mir gerade nicht mehr klar, welcher der Parameter aus der Konfiguration https://github.com/fmidue/modelling-tasks/blob/e1d859e8c5787ff4d02f032b93e811181e6b95e9/example/src/Modelling/CdOd/DifferentNames/Config.hs#L19-L46 dafür verantwortlich ist.

Ist es die Zeile
```
usesEveryRelationshipName = Just False
```
oder die Zeile
```
ignoreOneRelationship = Just True
```
?

Oder liegt hier sogar eine Redundanz zwischen den Konfigurationsoptionen vor?

**Comment by marcellussiegburg** [comment]
Im Prinzip ist das eine Redundanz. Momentan forciert der Checker sowieso, dass beide gegensätzlich definiert sind: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/e1d859e8c5787ff4d02f032b93e811181e6b95e9/src/Modelling/CdOd/DifferentNames.hs#L222-L227
Grund ist vermutlich, dass der Parameter `usesEveryRelationshipName` ursprünglich gar nicht existierte und erst mit Einführung der `ObjectProperties` aufkam.

`ignoreOneRelationship` sollte entfernt werden!
