### ISSUE TITLE
Tutorrückmeldung bei AD-zu-PN-Aufgabenstellung

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#258]
zu Aufgaben wie https://autotool.fmi.uni-due.de/route/aufgabe/550

> Klarifikation zu Folien 217/19 verkürzen. "Stellen, die für die Realisierung von Verzweigungs- und Verbindungsknoten genutzt werden, gelten nicht als Hilfsstellen."

**Comment by jvoigtlaender** [comment]
Könnte sich erledigen, wenn die Folien angepasst sind und dieser Hinweis gänzlich rausgenommen wird. (Ist im Moment ja hard coded. Haben wir das schon irgendwo auf "Wiedervorlage"?)

**Comment by marcellussiegburg** [comment]
Das war scheinbar noch nicht festgehalten.

@jvoigtlaender Kannst du hier Bescheid geben, wenn sich die Folien aktualisiert haben? (Vielleicht ist es möglich in den Quellen dazu einen Verweis zu setzen.)

**Comment by jvoigtlaender** [comment]
Folien 217 und 219 sprechen jetzt von *Stellen* statt *Hilfsstellen*. Außerdem ist in den Untertiteln der Videos ergänzt: https://github.com/fmidue/Modellierung-Untertitel/commit/de1c377baf751012999df48ae2fadd5dc05f759a
