### ISSUE TITLE
emitting label info into the `svg`s

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#260]
For the external use in the BA thesis, the student needs to know which labels from the algebraic data correspond to which parts of a generated image.

For example, he has obtained this image: 
![petrid1275ea9040a8a212a4e2efbae9a2dcdb844d4a840c10b53f32cf0a09f552ed10010](https://github.com/jvoigtlaender/modelling-tasks-internal/assets/5853832/aff4bda6-6608-47b9-88e4-7f0d684a5ca3)
and now wants to be able to have the user click into the image and know which transition or place was clicked on. So he needs to know what the nodes "mean".

He has identified that the labels are currently rendered as svg paths. For example, the `7` in the picture is this piece in the svg file:
```svg
<g fill="rgb(0,0,0)" fill-opacity="0.0" stroke="rgb(0,0,0)" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10.0" stroke-opacity="1.0" stroke-width="0.36646144825564353"><path class="rect" d="M 148.0823,186.9906 l -0.0000,-14.6585 h -14.6585 l -0.0000,14.6585 Z" fill="none" fill-opacity="0.0"/><path class="" d="M 138.5320,183.8121 ZM 140.1560,178.7013 c -0.3057,-0.0000 -0.6209,0.0669 -0.8311 0.8311c -0.1051,0.0124 -0.2016,0.0010 -0.3057 -0.0287c 0.0764,-0.4968 0.1815,-1.0699 0.1911 -1.5285c 0.0000,-0.0287 0.0096,-0.0287 0.0382 -0.0287c 0.1720,0.0382 0.1528,0.1337 0.4776 0.1337h 1.9679 c 0.3630,-0.0000 0.5732,-0.0573 0.7356 -0.1051l 0.1528,0.1146 c -1.0699,2.6080 -1.5953,4.1937 -2.1399 5.8177l -0.6496,0.0287 l -0.0764,-0.0669 c 0.6496,-1.4520 1.4043,-3.3149 2.1494 -5.1681h -1.7100 Z" fill-opacity="1.0" stroke-width="0.0"/></g>
```
There's nothing obvious in there that signals `7`.

Is it possible to emit such information into the `svg` file, via hidden attributes or some such?

**Comment by jvoigtlaender** [comment]
An alternative (trick I used for the other BA thesis) would be to use color-coding. Basically, emitting a rainbow version of the svg, where each text label uses a different color. And when outputting the algebraic data type value, the relevant colors used per label are also included (possibly kind of "easy" here, since the type is already abstracted over the node key type?), so that the connection can be reconstructed after the fact by looking for the unique colors in the `svg` file.

That's what all the ["rainbow" stuff in the `sd-generate` repo](https://github.com/search?q=repo%3Afmidue%2Fsd-generate%20rainbow&type=code) is about.

**Comment by marcellussiegburg** [comment]
In fact, information can be hidden under the `class` attribute. Currently it is set to `class="rect"` in order to store information that is currently used for the hovering hack. Maybe it's not a good idea to interact with it? On the other hand, it's probably controlled by a parameter anyway, so it's likely irrelevant because highlighting is not needed in this case anyway?

Amending the `class` information would be trivial, but might destroy SVG structure which is reconstructed by the highlighting hack. I will dive deeper into the "rainbowing".

**Comment by jvoigtlaender** [comment]
> highlighting is not needed in this case anyway?

Yes, that's the case.

**Comment by marcellussiegburg** [comment]
I implemented the naive approach of just adding a label. As predicted this destroys SVG structure (i.e. label and node are separated). Is this enough? (This cannot be added to the dev/main branch before the exam because it changes central data types). Should I push this branch to the public repo?

**Comment by jvoigtlaender** [comment]
> As predicted this destroys SVG structure (i.e. label and node are separated). Is this enough?

I guess the criteria for "success" are:
- Is it still a valid `svg` that can be handled by other libraries, particularly displayed? (The student will use something from the JS/NodeJS ecosystem.)
- Can the label information be used to do a lookup and find geometric information about "where in the picture is transition `7`"?

Maybe you can simply send a generated example file in Slack and let the student try out whether the format is sufficient.

> Should I push this branch to the public repo?

No objection.

**Comment by marcellussiegburg** [comment]
The student seems to be happy with the outcome. This issue will resolve once this branch is merged. Note that one side effect is that all configurations which include the `DrawSettings` will then also provide the (mandatory) `withAnnotatedLabels` Option, which destroys the structure for highlighting. Therefore a new checker needs to be introduced for each such configuration, that prevents setting this option to `True` (in Autotool). (@jvoigtlaender Please indicate if that defeats external usage.)

**Comment by jvoigtlaender** [comment]
About the last point: One a bit sheepish solution would be to name the option `withHighlighting` instead of `withAnnotatedLabels`, negate its meaning, and have Autotool-using lecturers set it to `True` (unless they really want to turn highlighting off for some reason, which they get - though a bit accidentally - by setting it to `False`, because that would correspond to `withAnnotatedLabels = True`).
