### ISSUE TITLE
use of indefinite articles

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#262]
As is the case for https://github.com/jvoigtlaender/modelling-tasks-internal/commit/b5dbd4be1b9be0e25c55ed8f8cea5755621376ef#r143819282, go through all places in commit b5dbd4b where `DefiniteArticle` was added and consider whether in context the use of `IndefiniteArticle` would be more appropriate.

**Comment by marcellussiegburg** [comment]
This is the only place where it is more appropriate at the moment, other task types where it is required are the reach tasks, but this has to happen during #181.
