### ISSUE TITLE
Syntax-Überprüfung bei CD-OD-Matching

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#268]
Tutorenfrage:

> Aufgabe 14 b
> - doppelte Nennung ist syntaktisch Korrekt, ist das gewollt?
>
> ![image](https://github.com/user-attachments/assets/01bebe38-702e-4e5b-a9b9-e21185500d68)

**Comment by marcellussiegburg** [comment]
> doppelte Nennung ist syntaktisch Korrekt, ist das gewollt?

Ja

Ich sehe keinen Handlungsbedarf. Vielleicht wird diese Eingabemodalität irrelevant durch eine Anklick-Matrix mittels Flex-Task.
