### ISSUE TITLE
eventuell mehr Vorabprüfung bei Eingabe von Transitionen und Stellen?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#269]
Tutorenanmerkung:

> Aufgabe 23 b / 24 b
> - t0 und t100 wird akzeptiert
>
> ![image](https://github.com/user-attachments/assets/4b24d23b-1492-4f65-b61e-1abcf605ea4d)

**Comment by jvoigtlaender** [comment]
Analoger Kommentar bei Eingabe einer Stelle (konkret der konfliktauslösenden):

> Aufgabe 26 b
> - s0 und t0 wird akzeptiert

**Comment by marcellussiegburg** [comment]
Das Feedback dazu gibt es:
![image](https://github.com/user-attachments/assets/57ba74c7-0236-40e4-b411-0ae003aa2840)

Hier geht es darum, dass es kein reject gibt. Falls #265 bearbeitet wird, sollte darauf geachtet werden, dass dieses Verhalten nicht auftritt!
