### ISSUE TITLE
follow-ups to #101 / 2fd6161710fdef1442ac9e91421af74ab3ab304c

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#272]
Would the new configuration option `anyCompositionCyclesInvolveInheritances :: Maybe Bool`  also make sense for `NameCdError`?

Should it be prevented to be set to `Just` when other configuration options already prevent the introduction of composition cycles in the first place?

**Comment by marcellussiegburg** [comment]
Yes, both makes sense.
