### ISSUE TITLE
Gedanken zu "Alloy-CD-to-OD-transform"

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#273]
Ich habe im Branch https://github.com/jvoigtlaender/modelling-tasks-internal/tree/refactor-cd-od-alloy ein paar Refactorings auf dem Code aus https://fmidue.slack.com/archives/DP6ACM4S2/p1728578908895419 durchgeführt.

Die Änderungen in der Commit-Sequenz https://github.com/jvoigtlaender/modelling-tasks-internal/compare/40125c16df60dbf12a9e4c84c111ae54c25a989e...9d5d3e8b069778185a4d6eff1adfd3e9d97d05d6 sollten eigentlich "nur aufhübschend" sein, also sollten nichts an der Funktionalität ändern, insbesondere dürften die erzeugten Alloy-Instanzen nicht anders aussehen (also höchstens durch den Nichtdeterminismus beim Erzeugen anders, aber nicht hinsichtlich der Signaturen und Parsebarkeit mit aktuellem Parser-Code). Ob der erzeugte/vereinfachte Alloy-Code zu schnellerem Lösen führt, lässt sich bestimmt nicht so einfach sagen. Der Alloy-Compiler macht ja sicher auch diverse Inlinings etc. Bei meinem Ausprobieren ging es auch wirklich "nur" um die Lesbarkeit durch Menschen.

Der (letzte) Commit https://github.com/jvoigtlaender/modelling-tasks-internal/commit/6a823f34ac3badceef8a9d432055fcb376deee5a ist tiefgreifender, da er die Form der Instanzen ändert (es gibt keine dreistellige `get`-Relation mehr). Für das Anschauen des erzeugten Alloy-Codes (durch Menschen) wäre er aber denke ich auch gut.

**Comment by jvoigtlaender** [comment]
Während alle Änderungen hier an konkretem Alloy-Code gemacht wurden, entspricht denke ich jeder Commit in dem Branch einer auch auf der den Alloy-Code erzeugenden Haskell-Seite ziemlich klar identifizierbaren Anpassung.

**Comment by jvoigtlaender** [comment]
Gestolpert bin ich bei der Sache auch (wieder) über die Gerichtetheit der Beziehungen, insbesondere (im Beispiel) der Aggregation und Komposition.

Irgendwie dachte ich, das wäre bereits mal umgedreht worden. Aber tatsächlich ist es das auf der Alloy-Seite noch nicht, richtig? #40 ist ja noch offen.

**Comment by marcellussiegburg** [comment]
> Irgendwie dachte ich, das wäre bereits mal umgedreht worden. Aber tatsächlich ist es das auf der Alloy-Seite noch nicht, richtig?

Ja, genau. Die Anpassung wurde bis jetzt nicht vorgenommen. Es wäre wohl sinnvoll, das demnächst anzugehen (birgt aber auch viel Fehlerpotenzial).

**Comment by jvoigtlaender** [comment]
Hinsichtlich des Fehlerpotenzials haben wir ja aber im Wintersemester die größte Test-Crowd. :smile:

Im Ernst, das sollte jetzt "umgedreht" werden. Ich hoffe, dass es nicht all zu viele Stellen sein werden. Ich sehe es doch richtig, dass im Moment *alle* Nicht-Vererbungsbeziehungen entgegen der Richtung aus der Vorlesung gepolt sind? Also sollte es machbar sein, die Änderung genau nur im Alloy-Code und beim Einlesen der Alloy-Instanzen in Haskell-Code einzubringen?

Und konkret der Compositions-Constraint sollte sich eigentlich vereinfachen lassen. Ich sehe zumindest auf Anhieb nicht, warum man nicht statt https://github.com/jvoigtlaender/modelling-tasks-internal/blob/6a823f34ac3badceef8a9d432055fcb376deee5a/example.alloy#L70-L73 in der aktuell am meisten refaktorierten Version (und es sollte auch auf den anderen Versionen analog gehen) einfacher dies schreiben kann:
```alloy
  // Compositions
  all r : Object | #{l : Object | r in l.y} =< 1
```
Und wenn es mehr als eine Kompositionsbeziehung im Diagramm gibt, dann eben so etwas:
```alloy
  // Compositions
  all r : Object | plus[#{l : Object | r in l.y}, #{l : Object | r in l.z}] =< 1
```
Und wenn die Links umgedreht werden, dann gibt es auch hierzu sicher eine äquivalente Version mit umgekehrter Navigationsrichtung.

**Comment by marcellussiegburg** [comment]
> Also sollte es machbar sein, die Änderung genau nur im Alloy-Code und beim Einlesen der Alloy-Instanzen in Haskell-Code einzubringen?

Ja, das sollte so funktionieren. Bzw. sollte beim Zeichnen der Objektdiagramme nicht mehr `Back` verwendet werden, sodass das Einlesen bzgl. des Umdrehens gar nicht geändert werden müsste.

Deute ich das richtig, dass das Vorgehen im vorherigen Kommentar die Reihenfolge erst #273 (dieses Issue) und dann #40 (das Umdrehen) vorschlägt?

**Comment by jvoigtlaender** [comment]
> Deute ich das richtig, dass das Vorgehen im vorherigen Kommentar die Reihenfolge erst https://github.com/jvoigtlaender/modelling-tasks-internal/issues/273 (dieses Issue) und dann https://github.com/jvoigtlaender/modelling-tasks-internal/issues/40 (das Umdrehen) vorschlägt?

Ich denke ja, weil man dann eventuell doch noch tieferes Nachdenken (über das korrekte Ausdrücken des Composition-Constraints etwa) direkt auf der Ebene/Darstellung investiert, die auch für die Zukunft (etwa das Paper) die relevante ist.

**Comment by marcellussiegburg** [comment]
Die Commits stellen den jeweiligen Schritt analog her (modulo Kommentaren / Spacing / Reihenfolge). Das sollte reproduzierbar sein.

Dabei ist der ausgeführte Befehl
``` haskell
matchCdOd defaultMatchCdOdConfig { Modelling.CdOd.MatchCdOd.classConfig = ClassConfig { classLimits = (4, 4), aggregationLimits = (1, Just 2), associationLimits = (0, Just 1), compositionLimits = (1, Just 2), inheritanceLimits = (1, Just 2), relationshipLimits = (4, Just 6)}, Modelling.CdOd.MatchCdOd.maxInstances = Just 500} 0 0
```

Wobei hier https://github.com/jvoigtlaender/modelling-tasks-internal/blob/641bd55cc963a17309cedacbd24ef93a53d75d7e/src/Modelling/CdOd/MatchCdOd.hs#L675-L677 noch die folgende Zeile eingefügt worden ist:
``` haskell
  () <- return $ unsafePerformIO $ sleep 1 >> writeFile "example.alloy" (combined1and2 ++ cd1and2)
```
(und entsprechende Imports)

**Comment by jvoigtlaender** [comment]
Nicht nur die Compositions-, auch andere Constraints sollten am Ende noch weiter vereinfachbar sein (insbesondere auch den generierenden Haskell-Code vereinfachend). Zum Beispiel im Kontext https://github.com/jvoigtlaender/modelling-tasks-internal/blob/6a823f34ac3badceef8a9d432055fcb376deee5a/example.alloy#L57-L60 lässt sich ja https://github.com/jvoigtlaender/modelling-tasks-internal/blob/6a823f34ac3badceef8a9d432055fcb376deee5a/example.alloy#L66-L68 ersetzen durch
```alloy
  Object.z in C
  all o : B | #o.z >= 1
  all r : C | #(z :> r) >= 2
```

**Comment by jvoigtlaender** [comment]
Bzw. in der letzten Zeile auch einfach
```alloy
  all r : C | #z.r >= 2
```

**Comment by marcellussiegburg** [comment]
Es gibt einen Bug, der mir gerade aufgefallen ist, der durch die Kombination von https://github.com/jvoigtlaender/modelling-tasks-internal/blob/94cdc03a61268db43306baae68125676c939613f/src/Modelling/CdOd/CD2Alloy/Transform.hs#L524-L525 mit diesem Parameter https://github.com/jvoigtlaender/modelling-tasks-internal/blob/94cdc03a61268db43306baae68125676c939613f/src/Modelling/CdOd/CD2Alloy/Transform.hs#L442-L443 entsteht. Als hier noch https://github.com/jvoigtlaender/modelling-tasks-internal/blob/ad9dd4b10dea6ee76148c72d961abdad886997c8/src/Modelling/CdOd/CD2Alloy/Transform.hs#L514-L515 stand, war es kein Problem, wenn der Code-Generierung nicht alle Beziehungsnamen (der anderen Klassendiagramme) bekannt waren. [Das ist jetzt nicht mehr so, weil wenn `CD1` `y` nicht enthält, aber `CD2`, dann wird `y` in `CD1` nun nicht mehr verboten.] `transform` braucht daher einen neuen Parameter dafür (spätestens mit der kommenden Anpassung hier, wird das aber auch relevant: https://github.com/jvoigtlaender/modelling-tasks-internal/commit/6a823f34ac3badceef8a9d432055fcb376deee5a#diff-73335b6ba2fec6a2e49f834dc31c55c5ee0b1f3eef27c9ee734cb34e8367a3ffL16-R14)

**Comment by jvoigtlaender** [comment]
Ja, ich verstehe das Problem. Man hat nicht mehr das `FieldName` als "Container", in den die unabhängig übersetzten "Module" jeweils ihre Namen injizieren und gleichzeitig selbst über unbekannte Reste quantifizieren können.

**Comment by jvoigtlaender** [comment]
Weitere Vorsicht ist wohl geboten bei Aspekten, die in meinem Beispiel in dem Branch gar nicht vorkommen (weil nicht in der Default-Config) aber allgemein natürlich trotzdem behandelt werden müssen. Also etwa das vorletzte `Nothing` hier (aber auch die anderen?): https://github.com/jvoigtlaender/modelling-tasks-internal/blob/94cdc03a61268db43306baae68125676c939613f/src/Modelling/CdOd/MatchCdOd.hs#L196-L201 unterdrückt die Erzeugung bestimmten Alloy-Codes, der aber von der Änderung der Modellierung betroffen ist.

**Comment by jvoigtlaender** [comment]
Es sollten am Ende noch weitere, und vor allem gut symmetrisierende, Vereinfachungen in den Sachen aus https://github.com/jvoigtlaender/modelling-tasks-internal/issues/273#issuecomment-2417306261 möglich sein.

Also sagen wir mal, wir würden aktuell etwas in dieser Art erzeugen:
```alloy
  no A.(z + u)
  no B.(y + u)
  no C.(y + z + u)
  no D.(y + z + u)

  A.y in D + B + C
  all o : A | #o.y =< 2
  all r : D + B + C | #{l : A | r in l.y} =< 1
  B.z in C
  all o : B | #o.z >= 1
  all r : C | #{l : B | r in l.z} >= 2
```
wobei `u` ein Beziehungsname aus einem anderen Klassendiagramm ist, der in den `no`-Constraints mit erwähnt werden musste, damit es keine Problem bei `MatchCdOd` gibt.

Dann ließe sich obiger Code denke ich auch einfacher ausdrücken wie folgt:
```alloy
  no u

  y.Object in A
  Object.y in D + B + C

  z.Object in B
  Object.z in C

  all o : A | #o.y =< 2
  all o : D + B + C | #y.o =< 1

  all o : B | #o.z >= 1
  all o : C | #z.o >= 2
```

**Comment by marcellussiegburg** [comment]
Es wäre noch bei den Assoziationen möglich, generell, wenn `=<` verwendet wird, `Object` statt der zu spezifischen gehörenden Objekte zu verwenden, also etwa könnte
``` alloy
all o : D + B + C | #y.o =< 1
```
als 
``` alloy
all o : Object | #y.o =< 1
```
geschrieben werden.
Außerdem kann es bei Kompositionen zu Dopplungen der Constraints kommen, die vermieden werden könnten (einmal wird das Constraint bei den Nicht-Vererbungen erzeugt und einmal ein äquivalentes bei den Kompositionen (in anderen Fällen ein sehr ähnliches)). Beide Änderungen führen aber möglicherweise zu schlechterer Lesbarkeit des Haskell-Codes (insbesondere letzteres), daher lohnt sich der Aufwand wohl nicht?
Ob die Änderung bei ersterem besser ist – sei auch noch dahin gestellt. Meine Vermutung ist, dass Alloy mit dem Allquantor über `Object` beim Suchen von Instanzen besser zurechtkommt (trotz dass mehr Variablen und längere Formeln erzeugt werden).

**Comment by jvoigtlaender** [comment]
> Beide Änderungen führen aber möglicherweise zu schlechterer Lesbarkeit des Haskell-Codes (insbesondere letzteres), daher lohnt sich der Aufwand wohl nicht?

Ja, das würde ich auch vermuten. Lassen wir das erstmal.
