### ISSUE TITLE
not omitting multiplicities that are used for reference in verbalizations

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#274]
> I think that means that for tasks which verbalize associations (only `RepairCd`?), when their setting is such that reference is made to multiplicities of stuff in the diagram (this might not always be the case, due to referencing existing associations by name), the config checker should make sure that all default multiplicities are set to `Nothing`, so that they are not suppressed in the diagrams.

_Originally posted by @jvoigtlaender in https://github.com/jvoigtlaender/modelling-tasks-internal/issues/106#issuecomment-2387888871_

**Comment by marcellussiegburg** [comment]
Should this replace #57, suggest an alternative approach, or propose an intermediate fix (to be applied before #57)?

**Comment by jvoigtlaender** [comment]
I think it's either independent, or the last of the mentioned options:
> propose an intermediate fix (to be applied before https://github.com/jvoigtlaender/modelling-tasks-internal/issues/57)

Or maybe #57 cannot really be done without causing confusion, at least for deletions?

In any case, this here should be done first.
