### ISSUE TITLE
structure / module names

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#43]
I think these should be together in some subdirectory:
* `NaiveTasks.hs`
* `RandomTask.hs`

And these as well, in some other subdirectory:
* `cd2alloy.hs`
* `cd2pic.hs`
* `instance2pic.hs`

And these, in yet another subdirectory:
* `different-names.hs`
* `random-task.hs`

Moreover, the following (at least these) should get a more meaningful name:
* `RandomTask.hs`
* `random-task.hs`

**Comment by marcellussiegburg** [comment]
When changing the structure I would suggest further moves:
All files that are part of the Haskell library into a common subdirectory (for convenience I would suggest `src`).

**Comment by jvoigtlaender** [comment]
Sure. Maybe this also means that `different-names.hs` and `random-task.hs` do not actually need to be moved out of root. They could stay there, as the "main executable entries" to what we have.

The `cd2alloy.hs`, `cd2pic.hs`, and `instance2pic.hs`, on the other hand, should probably still be moved "away". Largely, they are only there for legacy reasons. Actually, `Lexer.x` and `Parser.y` could be moved to live directly beside them as well.

And, of course, you will want to use the new `call-alloy` package, but I do not know how "urgent" it is to refactor the current repo into using that package.
