### ISSUE TITLE
make source code public

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#60]
Along the lines Oliver proposed in another, similar situation:
> I would suggest creating a new public repo and moving the master branch there. Locally we set this new public repo as the remote for the master branch and keep pushing experimental changes to the private repo. This way we also do not have to worry about "leaking" information about other private repos through old issues, for example.

In the course of this, we can also rethink the repo name. Maybe "alloy-cd-od" is not really the best possible name. Could think of a new one, and then name the public repo "XYZ" but the private repo "XYZ-internal".

**Comment by jvoigtlaender** [comment]
I created the "fmidue" organization. The proposal now is to have a public repo "fmidue/XYZ" as well as a private repo "user/XYZ-internal", the latter possibly being a fork of the former.

**Comment by jvoigtlaender** [comment]
The "forking" part of the proposal is probably obsolete.

**Comment by jvoigtlaender** [comment]
Do we have a name "XYZ" for this now?

**Comment by marcellussiegburg** [comment]
I suggest `cd-od-tasks`. I do not know if there is a better name as we are providing tasks for class and object diagrams. (Variants could be `uml-cd-od-tasks`, `class-and-object-diagram-tasks`; but maybe we do not require `alloy` as part of the repository name)

**Comment by jvoigtlaender** [comment]
No, `alloy` is not needed in the title.

But eventually one might want to be more generic than `cd-od`?

For example, Petri net tasks might share enough infrastructure with the material here that one could later want to put them in the same repository.

**Comment by marcellussiegburg** [comment]
Indeed, this could be possible. How about `modelling-tasks`?

**Comment by jvoigtlaender** [comment]
Yes, better in that way.

Now, for some reason, the repo for Oliver's project is called `IOTasks` instead of `io-tasks`. Well, the actual reason probably is that `IOTasks` is the top-level hierarchy name of all modules there.

Would something similar make sense here?

Or conversely, should the other repo have been called differently? (If only to make repo names under the `fmidue` organization somewhat systematic/consistent.)

**Comment by marcellussiegburg** [comment]
I think there is no general correct or wrong with any approach.
Haskell libraries are called differently all over the place (https://hackage.haskell.org/packages/browse). When creating new projects on github, it suggests dashes (`-`) and uses lower case names. I personally prefer this approach. Potentially uppercase letters could create hassle between case-sensitive / insensitive file systems (as did for instance within the petri-tasks repo with the haskell module names).
It somehow makes sense to write IO uppercase as it is usual within the Haskell world. I do not think it makes sense in this case. One could argue if haskell module names should (not) be the same as repository names. For consistency reasons you can decide anything - you are the boss. :grin:
