### ISSUE TITLE
rename 'sameRelationship'

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#63]
I think there is confusion about the meaning of "same". This is related to https://github.com/marcellussiegburg/alloy-cd-paper/commit/4e38381080cbca5a038077c4d5b47ca5febd87d8. Maybe there are other places in the Alloy code where "same" or "identical" or "equal" or "different" are used confusingly.

**Comment by jvoigtlaender** [comment]
I'm afraid https://github.com/jvoigtlaender/modelling-tasks-internal/commit/9da0d03b979200420893a7d5591d1fe6b91b4c0f goes in the wrong direction. The renaming of `sameRelationship` to `identicalRelationship` confounds the issue. Maybe we are not on the same page about what "identical" means.

I would say that `pred identicalRelationship [r, r2 : Relationship]` would have to be defined as simply `{ r = r2 }`.

That's clearly not the meaning in your interpretation.

But to me it seems to only meaning that is consistent with the change of wording in the commit referenced above: https://github.com/marcellussiegburg/alloy-cd-paper/commit/4e38381080cbca5a038077c4d5b47ca5febd87d8

**Comment by jvoigtlaender** [comment]
Specifically, this part in the current code: https://github.com/jvoigtlaender/modelling-tasks-internal/blob/0b2254659976c0c5673144e329e4251c8306301e/src/Modelling/CdOd/CdAndChanges/Transform.hs#L177-L178 seems to be what the paper is talking about when deliberately phrasing:
> we prohibit two non-identical changes being equal.

To me, the "`no disj x, y : NonInheritance`" part is the "we prohibit two non-identical ..." part, and the "`identicalRelationship[x, y]`" part would have the be the thing that is prevented, i.e., the "... being equal" (and specifically not "... being identical"; after all, that's exactly the phrasing that the commit in the paper removed).

**Comment by marcellussiegburg** [comment]
I would say, `{ r = r2 }` would check that they are the same relationships; and that the `no disj x, y : NonInheritance` prevents that `x` and `y` are the same relationship.

Whereas: `identicalRelationship[x, y]` should check that they are nonetheless identical (like twins), i.e. in every property equal.

But I guess there is a certain ambiguity between the words same and identical. (Which probably this issue was about in the first place?)
So instead of identical (in my aforementioned sense), I should refer to it as equal? Would this clear things up?

**Comment by jvoigtlaender** [comment]
I think "same" and "identical" are synonyms for one concept. And "equal" is another concept. For usage in OOP (which could be considered relevant here), see https://stackoverflow.com/questions/1692863/what-is-the-difference-between-identity-and-equality-in-oop and I guess countless other places.

Yes, I think `equalRelationship` would be appropriate. It would agree with what people do via `equals` in Java, and it would also be consistent with the wording in the paper after the  referenced commit.
