### ISSUE TITLE
don't use Applicative on standard lists

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#64]
I highly dislike using `<$>` instead of `map` on lists. Partly because lists have more than one reasonable `Applicative` instance (https://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Applicative.html#t:ZipList) and thus seeing `<$>` always makes me think "what exactly is going on here?"

Please replace `<$>` on lists by `map`. (I started doing it by find-and-replace, but it does need some more care, due to interaction with other infix operators, so I aborted it. You better know what rules you use when mixing infix operators in a line. So please go through the code yourself.)

**Comment by marcellussiegburg** [comment]
I think, I do not (yet) share that view and I am not convinced that this is bad praxis (If one would want the behaviour of ZipList it is required to introduced it somewhere (e.g. wrapping a List into a ZipList)). (And I am also no fan of having two different names for map in Haksell (fmap, map (,...).)

However, I will make these replacements, especially when it helps understanding the code.

**Comment by jvoigtlaender** [comment]
Well, your point about `ZipList` is logically "backwards". Yes, the two applicative instances for lists have been artificially separated in Haskell, making one the "preferred" one. But that is not mathematically justified. Both instances are equally applicative. So when I see `<$>`, I think about "applicative", and consider both possibly behaviors reasonable. That Haskell prefers one while hiding the other is a defect. If there isn't one clearly preferrable (or a unique, under mild assumptions) `Applicative` instance for lists, then lists themselves should not be applicative (but there could be *two* newtypes for it that provide the two instances, `ZipList` and some other newtype). While arbitrarily singling out one as "default" and only hiding the other behind a newtype seems bad taste to me.

Anyway, you can also consider making those changes a warm up practice for ProPa, where that view is made law (see the Lehrprocedere repo). :smile:
