### ISSUE TITLE
CI keeps failing

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#69]
... for varying reasons:
- https://github.com/fmidue/modelling-tasks/runs/615362206
- https://github.com/fmidue/modelling-tasks/runs/615560244

**Comment by marcellussiegburg** [comment]
- There is no reason for the abortion available for the first case given.
- For the second run, which actually fails, there is a suggestion which I will apply (in case it does not break anything within my evaluation instance).

**Comment by marcellussiegburg** [comment]
@jvoigtlaender Reopen this ticket, if you think the problem is not resolved yet.
