### ISSUE TITLE
delete 'master' branch here?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#70]
After all, that's what we have the public repo for (playing the role of `master`).

**Comment by marcellussiegburg** [comment]
Yes, please, I accidentally created this branch (by missing the option to match my local master to the `dev` branch). I could not find an option to delete this branch myself.

**Comment by jvoigtlaender** [comment]
I have only one directory/repo locally, with a `master` branch that is matched to `master` of the public repo and a `dev` branch that is matched to `dev` of the internal repo.
