### ISSUE TITLE
problematic verbalization of self-associations

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#71]
Verbalizations like this could be ambiguous and/or confusing:

![image](https://user-images.githubusercontent.com/5853832/101370260-924bc600-38a9-11eb-94de-ca38b6bc9252.png)

Displayed graphically, self-associations are clear enough (probably) even with multiplicities. But in verbalized form, it is pretty awkward.

**Comment by marcellussiegburg** [comment]
How about something like:
```
add a self-aggregation for As where 2..* wholes are in relation to 2..* parts
```
or is this still too confusing?

**Comment by jvoigtlaender** [comment]
Explizit von Selbst-... zu sprechen, macht es in der Tat klarer. Aber etwa "2 wholes in relation to 2 parts" (wenn man mal eine Situation ohne das "..*" betrachtet) ist ja semantisch nicht korrekt, weil es etwa die Ausprägung "(a1,a4), (a1,a5), (a2,a4), (a2,a6), (a3,a5), (a3,a6)" nicht erfasst (wo sind da die genau 2 wholes, die mit genau 2 parts in Beziehung stehen?), obwohl diese Ausprägung durchaus die Multiplizitäten erfüllt.

Und für Assoziationen statt Aggregationen würde eine Umschreibung per wholes/parts (wie oben oder noch weiter angepasst) leider auch nicht helfen.

**Comment by marcellussiegburg** [comment]
Ich sehe das Problem. Es ist nicht klar, ob von der Beziehung oder dem Link gesprochen wird.
Eine andere Möglichkeit wäre
```
add a self-aggregation for A where the multiplicities at the diamond side are 2..* and 2..* on its other side
```
in diesem speziellen Fall könnte es vereinfacht werden zu
```
add a self-aggregation for A where the multiplicities are 2..* at both ends
```
`end` und `side` könnte auch konsistent verwendet werden, wenn ein Wort klarer ist?
Für Relationen bleibt dann natürlich nur eine andere Formulierung, z.B.:
```
add a self-association for A where the multiplicities are 2..* at one side and 0..* at its other
```
Oder ist das auch noch missverständlich?

**Comment by jvoigtlaender** [comment]
So würde das Ursprungsproblem gelöst. Dann stellt sich natürlich die Frage, ob man nur in diesem Fall der Selbst-Assoziation/Aggregation/Komposition explizit von "Multiplizitäten an den Enden" sprechen möchte statt von "participates that many times", oder ob man dann gleich über all, also bei allen Assoziationen etc., fortan Formulierungen über Multiplizitäten wählt.

Oder, umgekehrt, warum man das konkrete Problem in diesem Issue hier nicht löst, ohne zur Nennung von "multiplicities" überzugehen, sondern die "participates"-Sprachregelung beibehält. Im Sinne von:
```
add a self-association for A where it participates 2..* times at one end and 2..* times at the other end
```
