### ISSUE TITLE
offer configuration options for additional structural constraints in CD/OD tasks?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#72]
For example, lecturer might want to create a task where definitely no self-associations will be present.

**Comment by marcellussiegburg** [comment]
This should already be covered by
- #118
- #85

(And the major concern of this issue should already be addressed. Unless control should also be there to say, e.g. must not have self-aggregations but may have self-associations?)

**Comment by jvoigtlaender** [comment]
I don't remember whether in the initial comment above by "no self-associations" I meant this on the class diagram level or the object diagram level.

If it was meant on the object diagram level, then #118 covers it directly.

If it was meant on the class diagram level, then I'm not sure it is covered for all tasks.

**Comment by marcellussiegburg** [comment]
> If it was meant on the class diagram level, then I'm not sure it is covered for all tasks.

Good point. I think this should be addressed via #61

**Comment by jvoigtlaender** [comment]
Meaning that it might not yet be addressed for `DifferentNames` and `MatchCdOd` tasks, but could be when their CD generation is switched from Haskell to Alloy, right?

On the other hand, it is possible (even likely?) that specifically the constraint "definitely no self-associations" is already built into the Haskell-based CD generator. That would then need to be retained in the switch to Alloy-based CD generation.

**Comment by marcellussiegburg** [comment]
> Meaning that it might not yet be addressed for DifferentNames and MatchCdOd tasks, but could be when their CD generation is switched from Haskell to Alloy, right?

Right.

> On the other hand, it is possible (even likely?) that specifically the constraint "definitely no self-associations" is already built into the Haskell-based CD generator. That would then need to be retained in the switch to Alloy-based CD generation.

Yes. Probably most of these might already be enforceable by using the configuration options provided by 53a459800ab7320bd39ca86307c57dddc033b59b.
