### ISSUE TITLE
use different verbalizations in RepairCD-Tasks when navigation directions are printed?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#73]
Could use wording like "from/to" then.

**Comment by marcellussiegburg** [comment]
This should apply to aggregations and compositions as it does for associations? 
Should there be an alternative phrasing for inheritance as well? It is not beneficial to write something like `an inheritance pointing from A to B`, or is it?

**Comment by jvoigtlaender** [comment]
The printing of navigation directions only has an effect on plain associations, not on aggregations and compositions. So I guess the suggestion was meant only for plain associations. (Aggregations and compositions already use "special" wording?)

For inheritance arrows, there is always a direction, so again the option "print navigation directions" should not change anything. The current wording is something like "... inherites from ..."?

**Comment by marcellussiegburg** [comment]
> The printing of navigation directions only has an effect on plain associations, not on aggregations and compositions.

yes (but at the moment there is no advice on navigation directions of aggregations/compositions printed at all)

> So I guess the suggestion was meant only for plain associations.

These have already "special" wording

> (Aggregations and compositions already use "special" wording?)

no

> The current wording is something like "... inherites from ..."?

Current wording is `an inheritance where A inherits from B`

**Comment by marcellussiegburg** [comment]
Current example phrases:
```
add an association from A to B where A participates 0..* times and B participates 0..* times
add an association where A participates 0..* times and B participates 0..* times
add a relationship that makes A an aggregation of Bs where A participates 0..* times and B participates not at all
add a relationship that makes A a composition of Bs where A participates 0..* times and B participates exactly once
add a self-association for B where it participates 0..* times at its beginning and 0..* times at its arrow end
add a self-association for B where it participates 0..* times at one end and 0..* times at the other end
add a self-aggregation for B where it participates 0..* times at the part end and 0..* times at the whole end
add a self-composition for B where it participates 0..* times at the part end and 1..* times at the whole end
```
(i.e. directions influence associations, it influences nothing else yet)

*Edit: for completeness-sake added different phrasings for self-associations*
