### ISSUE TITLE
Always print navigation directions in Match-CD-OD tasks

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#78]
Make it impossible to configure the navigation directions to not be printed.

Also, document (here in this issue), why it is important that navigation directions are printed. That is, include the encountered counterexample, along with information about all "pieces" that went into it. (So, also include what CD0 and CD3 looked like, including navigation directions, during the generation of that task instance).

**Comment by marcellussiegburg** [comment]
This is the complete generated task:

CDs
0: ![debug-0](https://user-images.githubusercontent.com/531939/105518324-71fc8d00-5cd8-11eb-8b74-729524b547b6.png) 1: ![output-cd1](https://user-images.githubusercontent.com/531939/105518457-9d7f7780-5cd8-11eb-86fa-42397d16f9e1.png) 2 ![output-cd2](https://user-images.githubusercontent.com/531939/105518556-b8ea8280-5cd8-11eb-939f-3d907fa1c944.png) 3: ![debug-3](https://user-images.githubusercontent.com/531939/105518607-cbfd5280-5cd8-11eb-93fb-cac16065984b.png)

ODs
a: ![output-od-a-not1not2](https://user-images.githubusercontent.com/531939/105518940-2696ae80-5cd9-11eb-8235-ec6d1d5e840d.png) b: ![output-od-b-not1not2](https://user-images.githubusercontent.com/531939/105519001-3adaab80-5cd9-11eb-87b6-f2eb29c923da.png) c: ![output-od-c-1not2](https://user-images.githubusercontent.com/531939/105519106-56de4d00-5cd9-11eb-87c9-8c521dfac345.png) d: 
![output-od-d-1not2](https://user-images.githubusercontent.com/531939/105519196-6c537700-5cd9-11eb-9814-e0881a80f757.png) e: ![output-od-e-2not1](https://user-images.githubusercontent.com/531939/105519246-7bd2c000-5cd9-11eb-932b-46f83b75cfe0.png)


[debug-0.pdf](https://github.com/jvoigtlaender/modelling-tasks-internal/files/5857167/debug-0.pdf) [output-cd1.pdf](https://github.com/jvoigtlaender/modelling-tasks-internal/files/5857208/output-cd1.pdf) [output-cd2.pdf](https://github.com/jvoigtlaender/modelling-tasks-internal/files/5857212/output-cd2.pdf) [debug-3.pdf](https://github.com/jvoigtlaender/modelling-tasks-internal/files/5857215/debug-3.pdf)

[output-od-a-not1not2.pdf](https://github.com/jvoigtlaender/modelling-tasks-internal/files/5857244/output-od-a-not1not2.pdf)
[output-od-b-not1not2.pdf](https://github.com/jvoigtlaender/modelling-tasks-internal/files/5857252/output-od-b-not1not2.pdf)
[output-od-c-1not2.pdf](https://github.com/jvoigtlaender/modelling-tasks-internal/files/5857257/output-od-c-1not2.pdf)
[output-od-d-1not2.pdf](https://github.com/jvoigtlaender/modelling-tasks-internal/files/5857264/output-od-d-1not2.pdf)
[output-od-e-2not1.pdf](https://github.com/jvoigtlaender/modelling-tasks-internal/files/5857268/output-od-e-2not1.pdf)

generated by `stack exec -- match-cd-od 3664892711` on 9a2cb33098dcc428538c3cc43bef5d7dc1d374f5

**Comment by marcellussiegburg** [comment]
This issue is due to adding reversed aggregations. This could be tackled by checking additions for CDs 1 (and 2 respectively), and 3. And prohibit "reversions" of any kind for these additions.
Special attention needs to be put on reversed edges to child classes as well: in this case for instance an aggregation from C to D (with D being the whole) in CD3 could as well raise such issues as above.

**Comment by jvoigtlaender** [comment]
You mention "reversed aggregations" etc., but the issue is not specific to aggregations, right?

**Comment by jvoigtlaender** [comment]
More specifically, what about plain associations? If they would not be a problem, then one could have a remedy by always printing navigation arrows in the object diagrams, but not in the class diagrams (except that aggregations and compositions already have an implicit navigation arrow in the class diagrams).

But the above counterexample seems like it could just as well have emerged with normal associations.

That suggests that indeed we should simply forego the omission of navigation directions and instead let them always be printed.

(The other ideas, about restricting modifications in order to "save" the opportunity of omitting navigation directions, https://github.com/jvoigtlaender/modelling-tasks-internal/issues/78#issuecomment-765553443, could come with its own problems. How are we certain that indeed we catch all possible problems/confusions? It also reminds of the "thick edges" aspect that we already have and that complicates the situation both for the generator and for the students. Let's not pile upon this.)

**Comment by jvoigtlaender** [comment]
If we do go for "navigation directions are always printed from now on in this task", we might revisit some other decisions/restrictions made earlier.

For example, maybe the decision that names should always be printed was in some sense predestined by an earlier, now rescinded, decision that navigation directions might not always be visible. That specific point might not apply, since the example from https://github.com/marcellussiegburg/alloy-cd-paper/issues/29#issuecomment-586992035, first part, seems to show that even if we print navigation directions, the names are required.

But there are two other possible points I can think of right now:
1. The previously used argument that navigation directions need not be printed was building on the fact that when relationships are flipped, they get a new name. If we are going to print navigation directions anyway, does that mean we do not need to assign new names when flipping a relationship?
2. We previously allowed flipping for aggregations and for compositions, but not for plain associations. Presumably because for associations without navigation direction it would not be visible when they are flipped. But if we are going to print navigation directions anyway, then this caution is not necessary - we might as well allow flipping an association (for this task! - the story for other tasks could be different).

**Comment by jvoigtlaender** [comment]
As an aside (but relevant here): Is it the case that what was described in the SACLA paper as permitted mutations of class diagrams is still exactly what the implementations supports?

![image](https://user-images.githubusercontent.com/5853832/105682002-2ae9e400-5ef2-11eb-8545-6dc45b5709e5.png)

**Comment by marcellussiegburg** [comment]
> As an aside (but relevant here): Is it the case that what was described in the SACLA paper as permitted mutations of class diagrams is still exactly what the implementations supports?

Yes, this is still the case

**Comment by marcellussiegburg** [comment]
> 1. The previously used argument that navigation directions need not be printed was building on the fact that when relationships are flipped, they get a new name. If we are going to print navigation directions anyway, does that mean we do not need to assign new names when flipping a relationship?

Yes, if we print navigation directions, keeping the name should be safe.

> 2. We previously allowed flipping for aggregations and for compositions, but not for plain associations. Presumably because for associations without navigation direction it would not be visible when they are flipped. But if we are going to print navigation directions anyway, then this caution is not necessary - we might as well allow flipping an association (for this task! - the story for other tasks could be different).

I agree with both decisions and will implement them.
