### ISSUE TITLE
Mehr Kontrolle über Veränderungen des Klassendiagramms

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#85]
Vorwiegend in `RepairCD` und `SelectValidCD`, und zu gewissem Grade vielleicht auch in `MatchCdOd`, könnte man sich als Aufgabensteller noch mehr Konfigurationsoptionen wünschen, über welche sich steuern lässt, welche Veränderungen des Klassendiagramms in Betracht gezogen werden sollen.

**Comment by jvoigtlaender** [comment]
Zum Beispiel wenn man durch eine Aufgabe "trainieren" möchte, wie korrekte Multipizitäten auszusehen haben, könnte man dann konfigurieren, dass nur "Verfälschungen" von Multiplizitäten durchgeführt werden sollen, während alle strukturellen Anforderungen an Klassendiagramme überall erfüllt sein sollen.

In dem konkreten Beispiel gibt es wahrscheinlich zwei Ansatzpunkte, so etwas durchzusetzen:
1. Entweder durch Einfluss darauf, welche der "certain change operations/mutations on CDs [modelled] as conceptual units" (Zitat aus MoHoL-Paper) bei der Erzeugung gewählt werden können.
2. Oder durch Einfluss darauf, welche "illegal structural weakenings" (Zitat aus MoHoL-Paper) herangezogen werden sollen/dürfen.

Bei anderen Aspekten könnte es sein, dass nicht beide obige Wege offenstehen. Es ist daher nicht völlig klar, was das richtige API für die Konfiguration ist.

**Comment by jvoigtlaender** [comment]
To some extent, this here is already addressed by https://github.com/jvoigtlaender/modelling-tasks-internal/issues/101 / https://github.com/jvoigtlaender/modelling-tasks-internal/commit/837b6693d593645712751ec4c5e63f91ed1f15c8.

**Comment by marcellussiegburg** [comment]
The usage of the configuration is prepared. What remains missing is actually introducing the configuration option `allowedCdMutations` for `MatchCdOd`, `SelectValidCd` and `RepairCd`.
