### ISSUE TITLE
Petri net display

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#88]
Would be nicer if Petri net places looked like this:
![image](https://user-images.githubusercontent.com/5853832/107940158-16948680-6f88-11eb-82f5-26394aea564d.png)

Like in the Pipe-Tool, the display could switch to displaying a number (here, along with a token symbol) from a certain number onwards (for example, if there are more than three tokens on a place).

**Comment by jvoigtlaender** [comment]
Also, highlighting functionality would be desirable to make it possible to uniquely determine:
- which place name belongs to which place,
- which weight belongs to which arc/arrow,
- ... (something else?)

**Comment by marcellussiegburg** [comment]
Places part is addressed by marcellussiegburg/modelling-tasks#1

**Comment by marcellussiegburg** [comment]
Highlighting is handled here marcellussiegburg/modelling-tasks#2
