### ISSUE TITLE
Common display functions for Petri net tasks with different origins?

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#89]
Maybe this isn't for this repo, but maybe it is, since adapting Petri net tasks from Leipzig might mean to make a copy of them and change that copy (if the behavior/display of the original versions should remain unchanged).

It would be nice if all Petri net tasks we use have the same "look" to students. That would mean to use the display functions from here (and with changes such as suggested in https://github.com/jvoigtlaender/modelling-tasks-internal/issues/88) also for the existing `Petri_Deadlock-Quiz` and `Petri_Reach-Quiz` task types.

**Comment by jvoigtlaender** [comment]
Eventuell wären die `Petri_Deadlock-Quiz` und/oder `Petri_Reach-Quiz` Aufgaben ja doch schon etwas für die Klausur? (Als Ersatz für Aufgabe mit Zeichnen eines Erreichbarkeitsgraphen.)

**Comment by marcellussiegburg** [comment]
> Eventuell wären die Petri_Deadlock-Quiz und/oder Petri_Reach-Quiz Aufgaben ja doch schon etwas für die Klausur?

Nur als Bemerkung: Die Aufgaben wären vermutlich relativ schnell mit PIPE-Tool zu lösen. Aber auch dabei können natürlich Fehler passieren.

**Comment by jvoigtlaender** [comment]
Das trifft auch auf bisherige Klausuraufgaben (und Übungsaufgaben) zu. Pipe erzeugt auf Knopfdruck einen gesamten Erreichbarkeitsgraph, den man nur abmalen muss.

Ob das im Übungsbetrieb (für Bonuspunkte) schon mal ausgenutzt wurde?

**Comment by marcellussiegburg** [comment]
Prinzipiell durch 4fd4d38 bereitgestellt
