### ISSUE TITLE
Im Petrinetz-FindConflict task auch nach der "problematischen" Stelle fragen

### ISSUE THREAD

**Issue by jvoigtlaender** [fmidue/modelling-tasks#92]
... oder einen separaten Aufgabentyp haben, bei dem neben den beiden in Konflikt stehenden Transitionen auch nach der diesen Konflikt auslösenden Stelle gefragt wird?

Wäre das denn sinnvoll umsetzbar (trotz dann anderen Antworttyps), diese "extra Abfrage" per Konfigurationsoption in den aktuellen Aufgabentyp einzubauen?

Eine Nebenbedingung wäre, dass wenn diese Option eingestellt ist, auch `uniqueConflictPlace` auf `Just True` stehen sollte. Oder, flexibler wäre wohl, dass man für die Einstellung von `uniqueConflictPlace` alle Freiheiten lässt, und die Aufgabenstellung nach *einer* (statt *der*) den Konflikt auslösenden Stelle fragt.

Kurzfristig wäre von Interesse, für die Klausur die Möglichkeit zu haben, die Angabe einer/der den Konflikt auslösenden Stelle zu verlangen.

**Comment by jvoigtlaender** [comment]
Man könnte auch noch konfigurierbar machen, ob den Studierenden in der Aufgabenstellung "verraten" werden soll, ob es genau eine "problematische" Stelle gibt oder nicht.

**Comment by marcellussiegburg** [comment]
> Wäre das denn sinnvoll umsetzbar (trotz dann anderen Antworttyps), diese "extra Abfrage" per Konfigurationsoption in den aktuellen Aufgabentyp einzubauen?

Umsetzbar wäre das, indem unterschiedliche Konstruktoren verwendet werden und zwei Alternative Parser verwendet werden.

Aber vielleicht wäre das verwirrend, wenn als Typ der Lösung
![image](https://user-images.githubusercontent.com/531939/149547061-c9f1c5a4-f529-4fc2-9643-63ca04dff3c8.png)
Einfach nur `ConflictWithOrWithoutPlace` stehen würde anstatt
z.B. `(Transition, Transition)` und `((Transition, Transition), Place)`
Also vielleicht doch lieber ein eigener Aufgabentyp!?

**Comment by jvoigtlaender** [comment]
Ich weiß es natürlich nicht belastbar, vermute aber, dass unsere Modellierung-Studierenden nicht auf die Typangabe schauen, sondern auf Beispiel-Eingaben. Andernorts mag das aber anders sein.

**Comment by jvoigtlaender** [comment]
Eigener Aufgabentyp hieße ja aber wahrscheinlich sowieso auch, dass es im Wesentlichen eine Implementierung/Modul gibt, mit viel Wiederverwendung und „Dopplung“ fast nur in Definition des Konfigurationsdatentyps.

**Comment by marcellussiegburg** [comment]
> Eigener Aufgabentyp hieße ja aber wahrscheinlich sowieso auch, dass es im Wesentlichen eine Implementierung/Modul gibt, mit viel Wiederverwendung und „Dopplung“ fast nur in Definition des Konfigurationsdatentyps.

Ja, da wäre mit geschickter Parametrisierung sehr viel Wiederverwendung möglich.

**Comment by jvoigtlaender** [comment]
Dann tun "zwei Aufgabentypen" wohl auch niemandem weh, es muss also nicht zwanghaft vereint werden. Zumal sich ja noch ergeben könnte, dass die beiden Aufgabentypen sich doch etwa auch in der Konfiguration noch leicht unterscheiden sollen (nicht nur im Antworttyp). Etwa indem die Option
> Man könnte auch noch konfigurierbar machen, ob den Studierenden in der Aufgabenstellung "verraten" werden soll, ob es genau eine "problematische" Stelle gibt oder nicht.

nur für einen der beiden Aufgabentypen relevant ist.
